### ISSUE TITLE
Stable release downloads broken

### ISSUE THREAD

**Issue by rctgamer3** [BernardoGiordano/PKSM#101]
Removing v3.1.2 from the releases/downloads page broke both FBI and Homebr3w's CIA download option since there is no publicly available stable .cia file. Please consider readding v3.1.2 or a newer stable version to the downloads page.

**Comment by BernardoGiordano** [comment]
I know. A stable release will be added as soon as I complete 4.0.0stable. Until this happen, just wait.

**Comment by DHowett** [comment]
There is no point in using the Github Releases feature or even marking a version as "stable" if you're going to remove old ones ☹️. It'd be neat if we could access the 3.x line until the 4.x line reaches feature parity.

**Comment by BernardoGiordano** [comment]
I don't really care, there's a reason if I took down all the old releases. Also, the new stable one is coming within the next 12 hours, so just wait.

**Comment by BernardoGiordano** [comment]
they're coming

**Comment by Samuel8488** [comment]
The new vercion?now?

**Comment by greenDarkness** [comment]
I'm excited for the new stable release. Thanks for all your work! I'm sure everyone understands that programming is no easy task, and that the more time that is put into the release the more stable it will be.
Happy New Years!
Cheers!

**Comment by Samuel8488** [comment]
Happy new year! n n
