### ISSUE TITLE
DS Titles From FlashCard

### ISSUE THREAD

**Issue by AngelSora** [BernardoGiordano/PKSM#103]
I only have a SuperCard DSONE Working on my New 3ds XL Using TWloader and it would be really awesome if it can take the .sav file from the Flash Card Micro SD.

**Comment by LinkofHyrule89** [comment]
He told me on gba temp he would never support loading games from flash cards but that maybe he would support improve save files from the regular SD card. I'm really hoping he does it do I can move my heart gold Pokemon over to my Pokemon Moon game card.
