### ISSUE TITLE
won't open the bank

### ISSUE THREAD

**Issue by lavitz525** [BernardoGiordano/PKSM#106]
the v4.0alpha don't open the bank feature for me.

**Comment by BernardoGiordano** [comment]
Absurd, check better

**Comment by lavitz525** [comment]
when i try to use the bank the 3ds freeze

**Comment by Samuel8488** [comment]
You say the new PKSM is here In 12 hours 
and i'm dont see the new vercion.

**Comment by lavitz525** [comment]
re-downloaded the alpha and now the bank works fine. keep up the great work!
