### ISSUE TITLE
Improve d-pad support when creating pokemon in editor

### ISSUE THREAD

**Issue by Xikes** [BernardoGiordano/PKSM#109]
When using the editor in PKSM and clicking on an empty space, two arrows appear allowing you to cycle through every pokemon, so you can pick which pokemon you'd like. You can press L/R to change the speed, but cycling through _every_ pokemon is a fairly lengthy process. 

As of now, it doesn't appear that you can use the d-pad to do this or other actions within the creation flow. Having to hit and hold the small arrow on the touch screen for a fairly considerable amount of time to get to the end, and it doesn't appear you can cycle backwards from bulbasaur to quickly get to the end either. Additionally, the remainder of the creation flow is heavily reliant on the touchscreen which can be uncomfortable with extensive use. Adding d-pad support throughout the creation flow would vastly improve the app's experience.

Creating pokemon should be a quick experience if desired, and I feel like a small change could vastly improve the feel of this specific flow.

----
Personally, I think that swapping pokemon creation to start with a flow similar to move selection (a large scrollable table-like screen with d-pad support) would be more usable by being able to quickly find the exact pokemon you want instead of going through them one by one.  That is outside the scope of this issue, however.

**Comment by Natsuru3** [comment]
I would like to see other ways to search for the pokemon you want to add. i.e. by name, type, region, ID or if a pokemon can learn a specific move .etc

**Comment by dsoldier** [comment]
Pokemon generation has been improved, now 40 Pokemon are shown at the same time on the top screen and you can move with the d-pad and change pages with L/R.
