### ISSUE TITLE
Pokemon editor option selector remains open after making changes

### ISSUE THREAD

**Issue by Xikes** [BernardoGiordano/PKSM#111]
When making changes to various options (nature, held item, etc) in the pokemon editing flow, the bottom screen frequently says 'Select a ______ with A in the top screen.' When you go ahead and press 'A' to make a change, the selector remains open and it is not immediately obvious that the change was made successfully. I was fumbling around with the controls until I noticed that the option was changing in the background of the bottom screen, but it was not immediately apparent.

I feel that pokemon editing would be more clear if either the label on the bottom screen mentions pressing 'B' when you are done, or if the selector closes itself after making a change.

**Comment by BernardoGiordano** [comment]
fixed
