### ISSUE TITLE
Goodwork!!

### ISSUE THREAD

**Issue by lass914** [BernardoGiordano/PKSM#112]
Hello,

Honestly this is great. And been waiting for this in ages. This is a good start of the year.

the following comment is just suggestion or minor adjustments. we can live without it but will be great if added. :) Thanks a bunch!
* after clearing a box the cursor automatically enters swap mode.
* randomize or enable SID, TID editing. this should avoid identification of a hack mon.
* generating pokemon can be replaced with enter pokedex ID rather than searching manually

**Comment by HadesComet** [comment]
I agree with suggestion 3, I would like to be able to type in a name for the pokemon. This is a really good hack but I'll be sticking with pkhex for the time being.

**Comment by NinjaBoyLao** [comment]
I second this request. @lass914 can you please change the title of this issue to "[Feature Request] SID and TID editing]

I dont think that searching by pokedex number for the mon you want to generate is feasible until the national pokedex comes out (with the pokebank and sun update)

**Comment by BernardoGiordano** [comment]
fixed
