### ISSUE TITLE
Mega Evolution Symbol

### ISSUE THREAD

**Issue by Krenk0** [BernardoGiordano/PKSM#113]
Hi!

I made some changes on some pokemons (made them shiny and stuff like that) and, when I used them ingame, they had the mega evolution simbol next to the HP bar. Don't know why and if it is a bug.

Sorry for my english btw.

**Comment by kwsch** [comment]
This is usually indicative of corrupted party stat values (ie, all the bytes after 232/0xE8), as status bitflags/counters are used for battle to keep track of things like Mega Evolution status.

Depositing and withdrawing them from the PC should reset the values ingame.

**Comment by Krenk0** [comment]
Thank you :+1:

**Comment by BernardoGiordano** [comment]
this refers to an older version, newer ones have this feature unlocked until the problem is solved. Closing
