### ISSUE TITLE
Issues Compiling

### ISSUE THREAD

**Issue by laxex** [BernardoGiordano/PKSM#114]
Earlier today, I tried compiling the latest version (4.0.0) by cloning the current repository.  There are a number of issues I ran into when compiling:

- error: 'pokemon' undeclared (first use in this function)  : This error first arises in graphic.c when trying to compile without making any changes to the code.  Meanwhile, it also complains about static char* species[] in graphic.h being defined but unused.  Perhaps these are meant to be the same variable?

-  error: expected expression before ',' token
     /* */,
          ^
   : This issue is also located in main.c, in defining the path[] and url[] arrays.  Is this a syntax error?

- Failed to open /home/fluffy/Documents/3ds_homebrew/Projects/By_Others/PKSM/assets/cia.rsf : It appears the necessary RSF file isn't included in the repository.

Even after getting rid of these issues (by renaming species[] to pokemon[], removing the commas, and putting an RSF file from another source, see here: https://github.com/MarcuzD/PyShell27/blob/master/assets/cia.rsf), the program crashes when loading the assets.

Are the "fixes" made above incorrect?  Does it have anything to do with the RSF file?  How would one go about getting the app to compile correctly?

**Comment by BernardoGiordano** [comment]
I know, because I didn't had the time to upload the commit I made later. Those were only a placeholder, that's why you had the issue

**Comment by BernardoGiordano** [comment]
[Fixed](https://github.com/BernardoGiordano/PKSM/commit/da80cf1c52f3acebe92b28490d132fa7ee12550d)
