### ISSUE TITLE
Clone 

### ISSUE THREAD

**Issue by iRukario** [BernardoGiordano/PKSM#115]
One thing that changed from 3.2 to 4.0 is that at the time of cloning it got a bit more time consuming. Before it was just press Y + -> + A and ready, now besides having to press A, select the cloning option the cursor always returns to the first slot. It would be very interesting if you could leave the Y for cloning again.

Thank you

**Comment by TheImmortal** [comment]
Can we get a mass cloning option like the one in PCHex++?

**Comment by Vexslasher** [comment]
It would be nice if there was a faster way of mass cloning like iRukario said. I'm not sure the best way but some faster options would be nice.

**Comment by BernardoGiordano** [comment]
Now that the cursor has been fixed to not return to the first slot, you only have to press A - A - -> - A to clone. It's the best compromise possible right now.

**Comment by iRukario** [comment]
Thanks so much
