### ISSUE TITLE
Bulbasaur showing on pokemon center.

### ISSUE THREAD

**Issue by ObliSopraffare** [BernardoGiordano/PKSM#117]
Hi, great job with the tool its really awesome!

I have some issues:

- Some modified pokemon show as bulbasaur when healing them on pokemon center
- I modified a Mimikyu and the passive stoped working

Thanks for everything in advance!

**Comment by Iccyiccy** [comment]
This seems to happen if you modify a Pokemon in your Team. Modified Pokemon in boxes don't show this behaviour.

**Comment by ObliSopraffare** [comment]
Yeah they where on my team, but with some it did'nt happen... well I'm going to only modify the ones on boxes from now, thanks!

**Comment by BernardoGiordano** [comment]
this should have been fixed
