### ISSUE TITLE
Not battle legal.

### ISSUE THREAD

**Issue by Ralph891** [BernardoGiordano/PKSM#118]
If the pokemon existed in an earlier generation it won't have the black clover(Same as the blue pentagon) making it automatically illegal. An option to change date and location met would fix it. Seems to only be with Generating. Editing pokemon that already have the clover hasn't caused me any problems yet.

**Comment by Xerono** [comment]
Some (all?) Pokemon that are generated via the app aren't legal. As far as I can tell, if you generate a new pokemon, it injects a already created version (which is usually not legal in SuMo right now). For example, I generated a Lucario, which I couldn't trade. Upon inspecting it with [PKHeX](https://github.com/kwsch/PKHeX/tree/master/PKHeX) it told me that it came from Y, with a met date as 25.11.2013, which is obviously not possible without Bank. I think the easiest solution is either 

-Inject them as blank and let the user configure them themselves completly

- or, more user-friendly: Do it like PKHeX and insert a legality check which tells what part of the pokemon causes problems.

**Comment by downspath** [comment]
the pre-created pokemon are legit in the other games, only the new pokemon are legit, 

(is the met date the date when i tradet it or the date when it got catched?

**Comment by Pickendorf** [comment]
Actually , it is not possible to get some pokemons legally in Sun , as the National Dex is not implemented yet, so I suppose it makes pokemon that can not be found in Sun instantly illegual atm. Retry it when the National Dex update is out , maybe they would become legal (or not , then try to re-inject them) ;)

**Comment by BernardoGiordano** [comment]
fixed
