### ISSUE TITLE
Doesn't honor 3DS' proxy settings

### ISSUE THREAD

**Issue by rctgamer3** [BernardoGiordano/PKSM#119]
I have all 3DS data routed through a local proxy to control what my 3DS can access or not. However, PKSM doesn't check at all for a set proxy while trying to downloading the assets.

**Comment by Hyperom** [comment]
I could see that possibly causing problems down the line with other users, if some proxy check is in effect when it shouldn't be

**Comment by rctgamer3** [comment]
I don't see why it should. This only applies to a particular case when a user has **explicitly** set a proxy in System Settings. PKSM doesn't honor this setting.

**Comment by BernardoGiordano** [comment]
no idea how to solve this. Also, is this really a big deal?
