### ISSUE TITLE
Pokemon Moon

### ISSUE THREAD

**Issue by EthanCentaurai** [BernardoGiordano/PKSM#123]
I'm having problems getting this to work with my physical EU copy of Pokemon Moon.

I am using the 3DSX version of the app on stock firmware 11.2.0.35-E using Freakyhax as my entrypoint.  I downloaded it about 10 minutes ago so I'm pretty sure I've got 4.0.0-stable rather than 4.0.0-alpha.

When I select Pokemon Moon in the titles list, the app says "Incorrect size for game!" but allows me to progress anyway.  I then select Pokemon Editor but this is where the app completely freezes.

I am not very far into the savegame at all, but I have unlocked the Festival Plaza and have access to the PC in Pokemon Centres.  Is there something I've missed?

**Comment by BernardoGiordano** [comment]
You must select the correct game with the DPAD.

**Comment by EthanCentaurai** [comment]
I did.

**Comment by BernardoGiordano** [comment]
You have to do it both before opening the application, both IN the application. That error is made to prevent that the user makes the same mistake you did, not selecting the same, correct game both inside and outside the application.

**Comment by EthanCentaurai** [comment]
I got it.

I was selecting Pokemon Bank as the target title in the Homebrew Launcher, not Pokemon Moon. Old habits die hard I guess. :P

**Comment by BernardoGiordano** [comment]
tell me if it works now

**Comment by EthanCentaurai** [comment]
Everything appears to be working now from what I can tell. Thanks! :)
