### ISSUE TITLE
question(s)

### ISSUE THREAD

**Issue by downspath** [BernardoGiordano/PKSM#125]
are the event Pokemon you can inject (like the 10 anniversary Pokemon) legit?
if yes, is it possible to edit their ot? or would this make them illegal?

PS: PKSM is awesome

**Comment by BernardoGiordano** [comment]
Yes; It depends on how you're supposing to do it; Yes

**Comment by downspath** [comment]
wow thank you for your quick answer

**Comment by downspath** [comment]
is there a way to donate? i want to support this Programm

**Comment by BernardoGiordano** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/BernardoGiordano) :)
