### ISSUE TITLE
i cant pick 510 ev

### ISSUE THREAD

**Issue by downspath** [BernardoGiordano/PKSM#129]
i can only pic 508 ev points,i know i dont need to set the extra 2 evs, but it looks way better with it,

**Comment by BernardoGiordano** [comment]
Fixed in the latest commits.

**Comment by downspath** [comment]
when will the update be released? :)

**Comment by downspath** [comment]
oh i found the part in the code, it was 4 hours ago ty :D

**Comment by downspath** [comment]
how do i update it? it is still 4.0.0, what file do i have to change?

**Comment by BernardoGiordano** [comment]
Until I release a new update, you can't access to the new version. If you don't want to wait, you have to compile everything by yourself

**Comment by downspath** [comment]
oh ty :)

**Comment by BernardoGiordano** [comment]
Thank you too for your contribution :)
