### ISSUE TITLE
compiling issue?

### ISSUE THREAD

**Issue by ericjwg** [BernardoGiordano/PKSM#130]
can't compile on neither win10 nor ubuntu...

below is the log for win10:
linking PKSM.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/lib/armv6k/fpu/3dsx_crt0.o: In function `ClrLoop':
(.crt0+0x8c): undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/e/Desktop/PKSM/PKSM.elf] Error 1
make: *** [build] Error 2

**Comment by BernardoGiordano** [comment]
It seems you don't have setup your path correctly with all the dependencies. It's not an issue related to PKSM itself, since it compiles on a well-setup environment

**Comment by ericjwg** [comment]
eh.... still missing rsf for building cia file... only built elf and 3dsx

**Comment by BernardoGiordano** [comment]
You can find templates on the internet, I don't have to provide them directly
