### ISSUE TITLE
Failed to receive a status code! 

### ISSUE THREAD

**Issue by ron2708** [BernardoGiordano/PKSM#133]
Hello!

The error (Failed to receive a status code!) appears when you open the application. After this error the application is restarted and the Homebrew launcher is returned. Login to Homebrew Launcher via SoundHax.

**Comment by BernardoGiordano** [comment]
I think you should read release notes, it seems you don't have internet access.

**Comment by ron2708** [comment]
jaja Sorry :D Thx!
