### ISSUE TITLE
Add search bar for items and attacks

### ISSUE THREAD

**Issue by Rewar17** [BernardoGiordano/PKSM#135]
One very useful thing I've seen in other editors is the function of looking for objects and attacks within those lists by typing the name into a search bar, would this be possible in a future revision? Sometimes it took me almost an hour to search and edit the 4 movements, this is very uncomfortable

**Comment by Krenk0** [comment]
If you know the abecedary order is not that hard :stuck_out_tongue:

**Comment by BernardoGiordano** [comment]
No point
