### ISSUE TITLE
Feature request: edit using only touch controls

### ISSUE THREAD

**Issue by WebChromium** [BernardoGiordano/PKSM#138]
Is it possible to click on a Pokemon and have the Dialogs open and click on them with the stylus?

**Comment by BernardoGiordano** [comment]
?

**Comment by Demirramon** [comment]
I think he means if it would be possible to do the same we do with the A button but using the touch screen instead, not just for draggind and dropping pokemon.

**Comment by WebChromium** [comment]
You're not wrong, it's exactly what I meant. Thanks for making it clearer!

**Comment by BernardoGiordano** [comment]
fixed
