### ISSUE TITLE
Feature Request: Change TID & SID?

### ISSUE THREAD

**Issue by jhuebert95** [BernardoGiordano/PKSM#141]
So i noticed changing the trainer name for newly created pokemon is already implemented, but even changing the trainer name to your own doesn't affect the TID or SID. Pokemon will not listen to you if their level is too high and you are still early game. Any chance you could implement automatically pulling the TID and SID from your save and applying it to all newly created pokemon. It's already able to read it so i didn't think that'd be too hard?

**Comment by BernardoGiordano** [comment]
added
