### ISSUE TITLE
Friendship usually displaying as 0

### ISSUE THREAD

**Issue by SadisticMystic** [BernardoGiordano/PKSM#143]
Almost all Pokemon in the manager have their friendship stat shown as 0. Most of the rest show a 70, but I recognize those as things that have been traded, so it seems to be that the stat that's showing is being pulled from the field for "friendship value with respect to the most recent handler that isn't you". Clearly, this isn't quite the right behavior.

**Comment by BernardoGiordano** [comment]
Fixed
