### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by ksawerykarwacki** [BernardoGiordano/PKSM#144]
Is there any chance to set correct save language on opening? It keeps setting my game as JPN. And I'm afraid it also will override other data. Maybe flag to not read this other fields when we only want to edit pokemon?

**Comment by BernardoGiordano** [comment]
It's not saving your game as japanese! You MUST press START to change the game's language in that menu,  the JPN that you see is only a placeholder that can be switched by pressing A. Your language will not change if you do nothing related to that.

**Comment by NinjaBoyLao** [comment]
yeah but when i back all the way out in preparation to quit the app, it asks me if i want to save changes, when i havent actively made any.
