### ISSUE TITLE
Compilation Issue, missing 'cia.rsf'

### ISSUE THREAD

**Issue by owenworley** [BernardoGiordano/PKSM#145]
I am trying to compile PKSM but it seems that a file referenced in the makefile 'cia.rsf' is missing from the repo?

**Comment by BernardoGiordano** [comment]
you can find a template [here](https://github.com/Steveice10/buildtools/blob/29ab2234e7376807d154a2a06b5d3d49ad50f631/3ds/template.rsf)

**Comment by owenworley** [comment]
Thanks for the quick reply, much apreciated.

**Comment by BernardoGiordano** [comment]
set enable compress to false, otherwise you will not go after the 'homebrew' screen. That series of settings should go as 'true, true, false, false, false'

**Comment by owenworley** [comment]
Great thanks

**Comment by owenworley** [comment]
Sorry to bother you again, but is there a reason that this file is not in the repo? (legality or something?)

**Comment by BernardoGiordano** [comment]
There should not be legality problems, since this kind of file can be found basically everywhere on the internet. It's only a personal choice

**Comment by owenworley** [comment]
Also, I have compiled with the parameters you suggested in the template .rsf, but I just get the 'homebrew' black screen. Are there any other changes needed for the rsf file?

**Comment by BernardoGiordano** [comment]
Category is Application
Process settings:
 * Memory Type: Application
 * System Mode : 64MB
New 3ds category:
 * 124MB / 804MHz / true / true

and remove SeedDB from FileSystemAccess, but it's not really needed

**Comment by owenworley** [comment]
Awesome, that got it working for me. Thanks for the help.
