### ISSUE TITLE
Game cart not found

### ISSUE THREAD

**Issue by Slade0120** [BernardoGiordano/PKSM#149]
No matter what I do, my game cart cant be found, I'm on the newest FW and using homebrew only. Tried it with all my 3ds Pokemon games and none worked.

**Comment by BernardoGiordano** [comment]
MOVE THE DPAD!

**Comment by Slade0120** [comment]
What do you mean? I selected Pokemon Sun while my Pokemon Sun was in my 3ds.

**Comment by BernardoGiordano** [comment]
you actually have to move your dpad both before opening the app, both AFTER the app is loaded, when it shows you the various games. It's written, too

**Comment by Slade0120** [comment]
Moving it like crazy now, not working. Sorry if Im just too stupid to see it.

**Comment by BernardoGiordano** [comment]
After you're with the selector on the game you want to edit, press A. It's not so difficult

**Comment by Slade0120** [comment]
Guess what Im doing. It just cant find the game.

**Comment by Slade0120** [comment]
I have Pokemon X in my 3ds now, so I dont have to move the selector at all, just select it, because its the first game in the list. Yet it cant find it, even tho Im doing all the things you tell me to do.

**Comment by BernardoGiordano** [comment]
do you have PKSM.xml located at /3ds/PKSM/ ?

**Comment by Slade0120** [comment]
Yep, the one from the Zip file I downloaded from your page.

**Comment by BernardoGiordano** [comment]
so do you confirm that you actually select X twice? this is fucking weird

**Comment by Slade0120** [comment]
Im gonna describe exactly what happens now. I boot up PKSM, it loads the graphics and backs up the bank, then I get to the first game selection, I select X, which is in my 3ds and then it tells me that the game cant be found.

**Comment by Slade0120** [comment]
I found my problem btw. I used a different boot.3dsx, to support custom themes, because the normal one from the starter pack wasnt working. I tested it again on my o3ds, with the boot.3dsx from the starter pack, and now it works. Sorry for bothering you so much.

**Comment by Nivean** [comment]
Hey, I know its been 3 years, and I have updated everything, including homebrew and the PKSM files, and I have the problem. I moved the d-pad to Pokemon Sun, my current updated version. When I press it, it says Game Not Found!. I have the XML file and the 3dsx in my SD Card in the PKSM folder. I dont know how to fix it.

**Comment by Nivean** [comment]
> I found my problem btw. I was using a different boot.3dsx, to support custom themes, because the normal one from the starter pack wasnt working. I tested it again on my o3ds, with the boot.3dsx from the starter pack, and now it works. Sorry for bothering you so much.
