### ISSUE TITLE
CLONE make my pokemons event

### ISSUE THREAD

**Issue by iRukario** [BernardoGiordano/PKSM#150]
I have a problem;

I clone a normal pokemon and when i try trade on GTS its say "Its a special Pokemon cant be traded"

Its a normal game pokemon. Not a event.

**Comment by BernardoGiordano** [comment]
How did you generate it?

**Comment by iRukario** [comment]
I no generate, i just Clone one existent, and try past on GTS

**Comment by BernardoGiordano** [comment]
it's weird you can trade it, then.

**Comment by iRukario** [comment]
Oh. Sry, my mistake, its holding a mega stone and i dont see..

Its tradeable now

Can remove this post
