### ISSUE TITLE
Generating pokemon from #18- #31 is off.

### ISSUE THREAD

**Issue by TimmyHuang** [BernardoGiordano/PKSM#151]
For pokemon #18 - #31, you're generating pokemon is offset by +1 in most cases and some in +2, This causes generating the wrong pokemon.

For example, if I were to generate #18, Pidgeot, it gives me #19 rattata.

**Comment by BernardoGiordano** [comment]
Well weird, it works correctly for me. SM or XYORAS?

**Comment by TimmyHuang** [comment]
Pokemon X

**Comment by BernardoGiordano** [comment]
fixed
