### ISSUE TITLE
Bulbasaur Bug still existing

### ISSUE THREAD

**Issue by pattax** [BernardoGiordano/PKSM#152]
Edited my Event Munchlax a little. Made it shiny and edited it's level from 26 to 27.
Yes I used the 4.0.1 Update!

**Comment by udelgadochio** [comment]
Is there anyway to return them to normal? I have the same problem!! :(

**Comment by BernardoGiordano** [comment]
Do not edit them in your party. Restore one of the automatic backups if you want it back normal

**Comment by pattax** [comment]
You can either load a backup or save them in PKHex to normal.

**Comment by BernardoGiordano** [comment]
this refers to an older version, newer ones have this feature unlocked until the problem is solved. Closing
