### ISSUE TITLE
Is it possible to move pokemon from B/W and B2/W2 to the bank?

### ISSUE THREAD

**Issue by apassiou** [BernardoGiordano/PKSM#153]
When I load up B/W there are only 2 selections "Events" and "Other". No option to move pokemon to the bank.

There are tools out there to read/dump saves from DS carts (twlsavetool for example) so reading the save shouldnt be an issue?

While we're at it same support for Pearl/Diamon/Platinum would be nice.

**Comment by BernardoGiordano** [comment]
Not possible yet.
