### ISSUE TITLE
v4.0.1 Date strings for auto-backups lacking leading 0 on month and day.

### ISSUE THREAD

**Issue by AnalogMan151** [BernardoGiordano/PKSM#155]
The date string created in https://github.com/BernardoGiordano/PKSM/blob/master/source/main.c#L289 lacks leading 0's for month and day making dates like January 11th and November 1st the same. Also recommend re-organizing to YYYY-MM-DD_HHMMSS format so the saves are listed in proper order when sorted alphabetically. 

The saves also cannot be imported directly through JKSM to be restored without renaming them and putting them into a folder. Suggest maybe creating a folder based on \GAMETYPE_YYYY-MM-DD_HHMMSS\main to make it easier to import backups with JKSM. 

Ex: \M_2017-01-10_105500\main

**Comment by BernardoGiordano** [comment]
currently fixed for the automated backup only (which are made at startup). I don't know why this don't want to work through setting menu.
