### ISSUE TITLE
Incorrect tid

### ISSUE THREAD

**Issue by swimmath27** [BernardoGiordano/PKSM#156]
The tid being shown is the g7tid, not the tid, rendering it useless.

**Comment by BernardoGiordano** [comment]
why useless?

**Comment by swimmath27** [comment]
Because you can't gen a pokemon with your ot (using pkhex or whatever else) using your g7tid, you need your tid. The calculation from tid and sid to g7tid is straightforward, but the calculation to get tid from g7tid and sid is not, and could potentially have multiple solutions. Could you at least add the option to view tid as well? Currently I have to run a script to calculate it from the two values given whenever I want to find out someone's tid
