### ISSUE TITLE
Wont work for me 

### ISSUE THREAD

**Issue by SolgaleoLunala** [BernardoGiordano/PKSM#157]
when i download the pksm 4.0.1   i click through everytrhing just like in the video and it shows  /3ds/PKSM-4.0.1/PKSM/3ds/PKSM/ and the only thing there is  region free launcher ,i click region free launcher and it shows the gamecard i click and it just loads the  normal game. i dont get any special  menu to choose which game or anything  or the  pksm logo at the top wat am i doing wrong  :( im on the old 3ds if that makes a difference :/

**Comment by BernardoGiordano** [comment]
video? which video? I don't make or support videos to download my product. Videos says wrong informations, mostly. You can find releases [here](https://github.com/BernardoGiordano/PKSM/releases)

**Comment by SolgaleoLunala** [comment]
the video by joedor the one you commented on. i downloaded pksm from the link u provided but it doesnt work for me  in my first comment that is whats happening. ive tried the 4.0.0 one and the 4.0.1 one on ur site. i dont get any pksm menus or anything pop up it just loads my regular game ,idk how to upload pics on here so i cant show u what the 3ds looks like , what am i doing wrong ?  :(

**Comment by SolgaleoLunala** [comment]
still doesnt work.. im racking my brain  :/

**Comment by BernardoGiordano** [comment]
What did you download?

**Comment by SolgaleoLunala** [comment]
https://github.com/BernardoGiordano/PKSM/releases/download/4.0.0/PKSM_400.zip

https://github.com/BernardoGiordano/PKSM/releases/download/4.0.1/PKSM.zip

https://github.com/BernardoGiordano/PKSM/releases/download/4.0.2/PKSM.zip

i tried all of them.the only one that actually shows up in the homebrew menu was the 4.0.0 but they all give me the same result. i extract the files and put them on my 3ds ,i load up homebrew through soundhax click pksm and nothing.it shows /3ds/PKSM-4.0.1/PKSM/3ds/PKSM/ then some region changer then pokemon moon ,i click and it loads my regular game it doesnt take me to pksm . i dont understand what im doing wrong

**Comment by BernardoGiordano** [comment]
3ds folder in the zip file goes into the root. After that you're fine.

**Comment by SolgaleoLunala** [comment]
i will try it again :/  which one am i using 4.0.0 or 4.0.1?

**Comment by SolgaleoLunala** [comment]
but just so i understand i am putting it in the file that says 3ds or the actual name of my sd card? SD Card (H:)
