### ISSUE TITLE
PKSM editor not working properly.

### ISSUE THREAD

**Issue by Enlil7** [BernardoGiordano/PKSM#161]
So, I created an account here just to get help with this because I can't seem to find answers elsewhere. Anyways, the problem is the editor is screwing up my pokemon in a way that I can't see. All I want to do is battle my friend Austin, and I couldn't because the game was saying two of my pokemon were illegal. All of their moves checked out, the OT and SSID all looked good, and I compared them both to a legality checker and everything was fine. I heard that you can screw your pokemon up if you edit them from within your party, so I re bred them and edited them from within the boxes. Everything was going good until I went to edit minior. At level 100 he's still showing level one stats in the edit screen. The only thing that seemed to change his stats was bumping his EV's. What's going on?

**Comment by BernardoGiordano** [comment]
Did you edit them in your party?

**Comment by hellupline** [comment]
@Enlil7 Could you extract your savefile and open it with PKHEX ? pkhex may show you what is wrong with your Minior.

**Comment by Favna** [comment]
@Enlil7 It might be that your Minior is in Meteorite form illegal outside of battle. In PKHeX Forms 0 through 7 are all Meteorite forms whereas forms 8 through 14 are Core forms (as index numbers).

That said - I'm not sure how PKSM handles forms but judging from #166 it doesn't support it at all yet.

**Comment by Anty-Lemon** [comment]
Fixed in 456aa24bba3309bccd230b5f10e99d84dc3249ac
