### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Rizerceo** [BernardoGiordano/PKSM#163]
When I use pksm Ver 3.1.2, it works just fine, but when I use 4.0, everytime I select something, it either freezes or is unresponsive. Any help? I am using and o3ds 11.2. with soundhax.

**Comment by Rizerceo** [comment]
*an

**Comment by BernardoGiordano** [comment]
Which version do you use?

**Comment by Rizerceo** [comment]
For homebrew, 1.1.1( I think)

**Comment by Rizerceo** [comment]
If that is a version

**Comment by BernardoGiordano** [comment]
I mean, for PKSM.

**Comment by Rizerceo** [comment]
Oh, 3.1.2

**Comment by BernardoGiordano** [comment]
You're fucking outdated. Use 4.0.3 and make sure you download the latest homebrew starter kit

**Comment by Rizerceo** [comment]
OK thanks
