### ISSUE TITLE
how do i update from 4.0.0 to 4.0.3?

### ISSUE THREAD

**Issue by downspath** [BernardoGiordano/PKSM#164]
nothing happens when i press the update button

**Comment by BernardoGiordano** [comment]
that button works only if you have CFW. If you are on homebrew, you have to update manually.

**Comment by downspath** [comment]
if i install a cfw can i still play online? and what cfw do you recomand?

**Comment by owenworley** [comment]
Http://3ds.guide

Yes you can on 11.2
