### ISSUE TITLE
Why are Pokemon Generating as SPA for the Default Region?

### ISSUE THREAD

**Issue by Superviral** [BernardoGiordano/PKSM#165]
![spasmer](https://cloud.githubusercontent.com/assets/17048125/21910012/4b8bd7b6-d8e8-11e6-965c-5454145832d8.jpg)

Is there a way to change the Pokemon's Region?

**Comment by kelsonr93** [comment]
Having same issue as well. All Pokemon default to SPN.

**Comment by BernardoGiordano** [comment]
It's not an issue, it's because they're stores as SPN in the built-in database. You can give your save's infos by clicking the purple button.

**Comment by HuXu77** [comment]
If you select the Pokemon, click Edit and then click the Purple button it will close the menu and the region will be fixed.

**Comment by mitchclay** [comment]
@BernardoGiordano I am noticing the ones that I do click the purple button for are getting rejected for trading.  If I keep the SPA region then it can be traded, but if I change it, then it is rejected from trading.

**Comment by BernardoGiordano** [comment]
thanks for letting me know

**Comment by BernardoGiordano** [comment]
it should be solved, now

**Comment by HuXu77** [comment]
Awesome! Looking forward to the next release!
