### ISSUE TITLE
Support for Different Forms

### ISSUE THREAD

**Issue by Superviral** [BernardoGiordano/PKSM#166]
As per:

http://www.serebii.net/sunmoon/forms.shtml

There are forms that cannot be changed with this editor. It would be cool to select and preview what color Minior is before it's generated.

**Comment by riotalternis** [comment]
Generate an eggxecutor
Generate an another one at the same position
Enjoy

**Comment by Superviral** [comment]
Thank you!

**Comment by Krenk0** [comment]
Does not work for me @riotalternis

**Comment by BernardoGiordano** [comment]
in fact that's not a solution.

**Comment by Anty-Lemon** [comment]
Form editor implemented as of 35f717c81daa4a0d6dc466ffdd1c7587b62ecb17
