### ISSUE TITLE
"Failed to Download Status Code"

### ISSUE THREAD

**Issue by ImperfectLion** [BernardoGiordano/PKSM#168]
Hello,

I have read all the release notes and looked online but have not found an answer.
I am connected to the internet and everytime I open the app, it has to "download graphics" but it always comes back with an error saying "Failed to download status code"
After a few taps of A, I have to restart the app?

Am I doing something wrong?
P.s. I downloaded the app via QR code

**Comment by BernardoGiordano** [comment]
Follow manual instructions as described in the readme

**Comment by ImperfectLion** [comment]
I put the SD card in my computer and found the problem.

The "additional assets" folder was empty. So I downloaded it (from the link in the "readme" file) and placed it in the correct place.

Everything worked fine after that :)

**Comment by YourUncleGreen** [comment]
What readme file! where do I download the readme file
