### ISSUE TITLE
Some Pokemons (Generated) will not Trade!

### ISSUE THREAD

**Issue by Ferrjimenez** [BernardoGiordano/PKSM#169]
Some Pokemons that are generated (Clicking "generate" and leaving it as it is) will not trade!

list of Pokemons that won't trade no matter what you do if it is generated using PKSM: (Wonder Trade)

Bulbasour (including) it's evolutions, 
Charmander (including evolutions), 
Squirtle (including evolutions) 
Articuno, Zapdos, Moltres (none of the legendary pokemons for the most part) (Lunala & Solgaleo works for some weird reason) 
etc....

So these are the random pokemons I chose to test it on, and none of them are tradeable. (2nd gen starters do work)

is there a setting that fixes this? or this an actual issue

**Comment by Ferrjimenez** [comment]
Actually I think I just figuredd it out. If th epokemon that you are generation DOES NOT have a pokedex number it won't trade! (so is this a game thing then?)

**Comment by BernardoGiordano** [comment]
try're not officially available pre-bank, it's normal!

**Comment by Ferrjimenez** [comment]
So when it is available, it will be tradable???
