### ISSUE TITLE
An Only Bank Version without any cheat

### ISSUE THREAD

**Issue by korosu** [BernardoGiordano/PKSM#171]
I think a lot of pk fan love the game not only for its battle 
So is possible an Only Bank Version?

**Comment by hellupline** [comment]
@korosu cant you just store then, without editing ?
About cloning then, you can delete then.

As I can see, this would be a really useless feature.

**Comment by BernardoGiordano** [comment]
PKSM is meant to be an all-in-one tool. You can always use only the storage function without using the other ones.

**Comment by korosu** [comment]
An Only Bank Version
1.less bugs
2.simple to use
3.loved by not cheat player
4.and other

**Comment by BernardoGiordano** [comment]
1) point me bugs
2) the actual one is not easy to use? It would be the exactly same thing
3) I think not cheat players loves PKSM, too
4) clarify what is 'ther' for you.

I would be happy seeing actual motivations rather than these

**Comment by korosu** [comment]
I find clone bug and I can clear the box only a single time
ver.4.0.3
<blockquote class="imgur-embed-pub" lang="en" data-id="a/FInVj"><a href="//imgur.com/FInVj"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by korosu** [comment]
now I know why I can only clear the box  a single time
I need to press a button after box is erased and if now press a on a pkm it will be erased

**Comment by korosu** [comment]
sorry for my poor english

**Comment by korosu** [comment]
[[URL="https://gbatemp.net/threads/wip-phbank-pok%C3%A9mon-homebrew-bank.398718/page-85#post-6987376"][WIP]  PHBank - Pokémon Homebrew Bank[/URL]](url)
