### ISSUE TITLE
Looping EV Values

### ISSUE THREAD

**Issue by Eric-Jackson** [BernardoGiordano/PKSM#176]
When an EV is at 0 and decreased, it should loop back to 252, same with the opposite direction.

https://github.com/BernardoGiordano/PKSM/blob/master/source/editor.c#L1199

Should just need something like:

```c
else
    setEV(pkmn, 252, lookup[i]);
```

**Comment by HuXu77** [comment]
I think this would worsen the user experience.  Most people aim for a 0 or 252 maxed stat.  With Fast scroll on its easy to do those changes, just press the plus in like 2 seconds its maxed.  If it looped you would have to pay more attention and have to switch to slow mode and slowly increment to get to that stat.

**Comment by MrPotatoGaming** [comment]
I agree with HuXu77. though a happy-medium would be allowing pausing for a second or two, at 0 and 252. This would allow people to stop at those values instead of continuously looping.

**Comment by Eric-Jackson** [comment]
I mainly meant for the slow mode, but I can certainly understand why it would be a bad experience on fast scrolling.

**Comment by HuXu77** [comment]
Oh yes, in Slow scroll mode would be a good idea!

**Comment by BernardoGiordano** [comment]
I removed the circular scroll to avoid having to pay attention if maxing a value, I think I'll not put it back another time.

**Comment by Eric-Jackson** [comment]
If you're on slow mode you have to pay attention anyway, as touch-holding does nothing.
