### ISSUE TITLE
Just some ideas???

### ISSUE THREAD

**Issue by OfficialBrony** [BernardoGiordano/PKSM#180]
So I see that when you press an option on the touchscreen, you can't press it again to select it. You have to press "A". I was hoping if you could let us select it with the touchscreen???

Also, I was hoping for some other edits like the location of the Pokemon and TID/SID and other trainer info as well. And hoping if we can make Pokemon seem like they were hatched from an egg at a location and give it egg moves and such.

**Comment by BernardoGiordano** [comment]
Yes but don't propose ideas when you seem to not be at least on the latest release. TID/SID has been added ages ago

**Comment by BernardoGiordano** [comment]
Edited, I totally misunderstood

**Comment by OfficialBrony** [comment]
`All good! I probably should've worded more properly. 
So I am sorry I caused the misunderstanding!

**Comment by BernardoGiordano** [comment]
Added in the latest commit. It will be extremely tricky to use, but it exists and it works.
