### ISSUE TITLE
Cannot compile on Linux

### ISSUE THREAD

**Issue by Anty-Lemon** [BernardoGiordano/PKSM#182]
```
Building for 3DS...
build/3ds-arm/source/sha1.o
build/3ds-arm/source/graphic.o
source/graphic.c:20:18: fatal error: sf2d.h: No such file or directory
 #include <sf2d.h>
                  ^
compilation terminated.
buildtools/make_base:585: recipe for target 'build/3ds-arm/source/graphic.o' failed
make: *** [build/3ds-arm/source/graphic.o] Error 1
```

I then tried the hacky solution of adding these lines to the makefile:

```
PORTLIBS_PATH := $(DEVKITPRO)/portlibs
PORTLIBS := $(PORTLIBS_PATH)/armv6k $(PORTLIBS_PATH)/3ds
CTRULIB ?= $(DEVKITPRO)/libctru
```

These changes allow PKSM to compile successfully, but attempting to open it on a 3DS results in an error saying "An error has occurred, forcing the software to close. The system will now restart."

**Comment by owenworley** [comment]
There is a list of required libraries in the readme. Go clone these and 'make', 'make install' them.

This worked for me on ubuntu 16

**Comment by Anty-Lemon** [comment]
I have all the proper libraries installed. This is a regression.

**Comment by BernardoGiordano** [comment]
try enabling errdisp on Luma3DS and see if the exception that it gives to you is 'prefetch abort'

**Comment by BernardoGiordano** [comment]
calling @Favna here, too

**Comment by Anty-Lemon** [comment]
Exception type: data abort

**Comment by Favna** [comment]
sf2d is from xerpi's [libsf2d](https://github.com/xerpi/sf2dlib). Try doing another `make install` for sf2d.

**Comment by BernardoGiordano** [comment]
I got problems with paths yesterday, too. I updated my devkitarm environment to the latest release and I had to reinstall all the libraries by zero. sf2d is not part of Xerpi's portlibs, so just try reinstalling it alone

**Comment by Favna** [comment]
as for this:

> I then tried the hacky solution of adding these lines to the makefile:
> 
> PORTLIBS_PATH := $(DEVKITPRO)/portlibs
> PORTLIBS := $(PORTLIBS_PATH)/armv6k $(PORTLIBS_PATH)/3ds
> CTRULIB ?= $(DEVKITPRO)/libctru

I can imagine this is a linux issue sadly because on Windows it is a must to add system environment variables PORTLIBS to <path-to-devkitpro>/portlibs/armv6k and a CTRULIB variable for <path-to-devkitpro>/libctru. 

While it has been a very long time since I have touched Ubuntu I believe you can set data to PATH for Linux as well. I suggest googling for it because I know 100% sure it's possible. I also remember that after adding it there was a command to refresh the file (I even forgot what it is called)

**Comment by Anty-Lemon** [comment]
> I can imagine this is a linux issue sadly because on Windows it is a must to add system environment variables PORTLIBS to /portlibs/armv6k and a CTRULIB variable for /libctru.
> 
> While it has been a very long time since I have touched Ubuntu I believe you can set data to PATH for Linux as well. I suggest googling for it because I know 100% sure it's possible. I also remember that after adding it there was a command to refresh the file (I even forgot what it is called)

I'm on Debian stretch, actually.

I can set the environment variables PORTLIBS and CTRULIB, if that's what you're referring to. You're thinking of $HOME/.bashrc, probably. I personally set environment variables in $HOME/.config/openbox/environment.

> sf2d is from xerpi's libsf2d. Try doing another make install for sf2d.

No change

**Comment by BernardoGiordano** [comment]
Try making something trickier, ast least for now, and add manually sf2d to PKSM's source. It consts in 4 or 5 files, so it's not a problem at all. If it's only a sf2d issue, you should be able to get the build working in this way

**Comment by BernardoGiordano** [comment]
try also adding only $(DEVKITPRO)/libsf2d as path definition. At leats for my case, libsf2d is located here

**Comment by Favna** [comment]
> I can set the environment variables PORTLIBS and CTRULIB, if that's what you're referring to. You're thinking of $HOME/.bashrc, probably. I personally set environment variables in $HOME/.config/openbox/environment

Yes bashrc is indeed the one I meant. Guess you did that already. I did a `make` with the 3 lines you initially shared and it still builds fine here so another option if the issue doesn't get solved on your side locally would be to add them to makefile - that's up to Bernardo of course. 

Might I just ask, what is the portlibs/3ds? I've never seen a 3ds folder next to the armv6k folder. Mostly just curious.

**Comment by Anty-Lemon** [comment]
I'm not sure we're on the same page here. It compiles with no errors, given I'm using one of a few hacks. Those few lines in the makefile are probably the best solution.

The bigger problem is when I install the build to my 3DS, it crashes with a "data abort" exception.

**Comment by BernardoGiordano** [comment]
[lines added in the makefile](https://github.com/BernardoGiordano/PKSM/commit/87e868f3919373f030d12f7b265d2f030bd7f6b5)

I think we're still on the same page, trust me. That kind of error appears when it can compile the code successfully, but when it tries to execute it, it doesn't find it at all. The error appears right after he 'Homebrew' screen disappears? If so, I experienced it yesterday too, it was due the fact I updated my devkitarm and I didn't install all the libraries but only part of them. I don't know if this is the case for you too or it's just the change to buildtools, but, well, this remains weird. Did you try this way, too?

>Try making something trickier, ast least for now, and add manually sf2d to PKSM's source. It consts in 4 or 5 files, so it's not a problem at all. If it's only a sf2d issue, you should be able to get the build working in this way

**Comment by BernardoGiordano** [comment]
btw, last case situation, I can still make a branch with the old makefile and the up-to-date code, so you're able to get a working build to make tests

**Comment by Anty-Lemon** [comment]
Adding sf2d to the source produces the same error.

Compiling 760d35646eaabdb1f0eb62067214b1da6e91c3e5, which I have previously compiled, also produces the same error.

Downgrading to devkitARM r45, installing smealum/ctrulib@396d341a8f8430c2724c6e9d596488f0160a6062, then recompiling all libraries solved the issue. I'm leaving this issue open for now in case you want to try and solve the underlying issue. Otherwise, feel free to close.
