### ISSUE TITLE
servpkx wont connect to my PKSM

### ISSUE THREAD

**Issue by Slade0120** [BernardoGiordano/PKSM#184]
Even though I think I have everything set up the way I should, it wont work ( http://imgur.com/a/UHu3y )

**Comment by BernardoGiordano** [comment]
did you leave the application in listening mode?

**Comment by Slade0120** [comment]
Listening mode? I dont understand.

**Comment by BernardoGiordano** [comment]
You need to press Y into the viewer to effectively be in listening mode. It will say in the upper screen that the application is waiting for a client to connect

**Comment by Slade0120** [comment]
Oh, yeah, I did that.

**Comment by BernardoGiordano** [comment]
so it worked now, or..?

**Comment by Slade0120** [comment]
No, that's why I asked in the first place. :/

**Comment by BernardoGiordano** [comment]
is the IP shown in PKSM the same that I can see in the pic, right?

**Comment by Slade0120** [comment]
![img_20170119_175316](https://cloud.githubusercontent.com/assets/25014890/22121946/3c361c9c-de86-11e6-9641-37c8bf94fc5e.jpg)
Precisely.

**Comment by BernardoGiordano** [comment]
do you succeed if you use the python version of servepkx?

**Comment by Slade0120** [comment]
I don't. Edited the file with my IP, (tried with and without the %* at the end) but it just closes upon opening.

**Comment by BernardoGiordano** [comment]
you have to drag&drop pk6/pk7 on that file to make it work. The %* is obligatory, it's needed to accept and parse the files.

**Comment by Slade0120** [comment]
Still the same result, closes upon opening.

**Comment by BernardoGiordano** [comment]
let's see if it gives you logs on your pc, then.

open a command prompt in servepkx folder, and type `python servepkx.py [ip address] [file.pk6 path] , it will say you something if there are errors

**Comment by BernardoGiordano** [comment]
Also, are they connected on the same network?

**Comment by Slade0120** [comment]
![shrug](https://cloud.githubusercontent.com/assets/25014890/22124760/6df03c94-de91-11e6-966d-0d9a55bc30a0.png)
Is that what I need? Never done much coding.

**Comment by Slade0120** [comment]
Also, yes, both my Notebook and my 3ds are connected to my Wifi. I tried it with my PC earlier, which is connected to the Router via a Ethernet cable.

**Comment by BernardoGiordano** [comment]
![image](https://cloud.githubusercontent.com/assets/17624378/22124951/2660fade-de92-11e6-9a0b-f67409e6f4dc.png)

**Comment by MO35AB** [comment]
same problem here, any solution yet ?
