### ISSUE TITLE
All generated pokemon are in SPA. 

### ISSUE THREAD

**Issue by Tw1stedN8** [BernardoGiordano/PKSM#185]
Im using the latest 4.0.3 and all the pokemon generated are SPA versions. Is it possible to add support to select what region the pokemon is from? Example: JPN,ENG,SPA or have it generate based off the version of your game?
Not sure how to word this so forgive me.

Thanks

**Comment by Anty-Lemon** [comment]
Tapping the purple button after selecting that mon will set its nationality to your own, along with setting its TID and SID to your own.

Setting the nationality manually is currently not implemented

**Comment by Tw1stedN8** [comment]
Im sorry. I was not aware of that. Thank you for the information.
