### ISSUE TITLE
List of small things for your consideration.

### ISSUE THREAD

**Issue by Hyperom** [BernardoGiordano/PKSM#186]
This is a list of small things that i thing would make the editor more versatile, this is not me demanding anything and its not a criticism, i just would like to see some or maybe all of them at some point in the future.

1. Color code the Natures: This isn't even a big thing, but it might be useful at a glance for figuring out which stat is which, maybe the colors could work like bulbapedia's [Here.](http://bulbapedia.bulbagarden.net/wiki/Nature#Stat-focused_table)

2. Have an option in the setting to automatically set a generated Pokemon to the trainer ID of the save its being created on: Because you said you have a database of Pokemon that the app generates from, this might be impossible, but I feel like it would make the process of generating Pokemon for a new game easier.

3. Have an option to give all the clothing options: I have no strong reasons for why you should add this, but it would make the fashionista in me very happy. :)

4. The ability to switch from the box to the Team Box without having to touch the screen: I don't know if thats possible or easy to do, but it is a little weird that it needs to be pressed when most of the rest of the app works with solely the buttons, but what ever, it out there if you care.

5. Highlight or at least bring notice to all the legal moves a pokemon can learn when generating it: this one i can understand not being added, it would require going through ever pokemon in Sun and Moon and figuring out every possible move it could learn, and putting that into the database, but its another suggestion, so yeah.

6. And lastly, when a Pokemon is shiny, maybe it could show the shiny sprite? Just an idea? :D

**Comment by BernardoGiordano** [comment]
2) it's already implemented, did you try at least once that purple button?
5) this requires too much work for me
6) I removed shiny sprites, I don't have enough memory to store them in the ram

**Comment by BernardoGiordano** [comment]
closing because none of the remaining things to do interests me or are important for the application's usage.
