### ISSUE TITLE
Game not found

### ISSUE THREAD

**Issue by adrigabri** [BernardoGiordano/PKSM#188]
Hi! I have a 3ds with rxtools, and when i use pksm on the digital Pokémon Sun i can use the program, but i can't use pksm with my physical cartridge of Pokémon Moon, what could it be? I have the last version..

**Comment by BernardoGiordano** [comment]
Are you selecting the correct game moving with dpad and then pressing A?

**Comment by adrigabri** [comment]
Yes, i have moon and i selected moon

**Comment by BernardoGiordano** [comment]
Move to Luma3DS and see if the problem is still present. Also, make sure you're updated to the latest firmware

**Comment by adrigabri** [comment]
Ok, i try it. Thanks

**Comment by BernardoGiordano** [comment]
how is it going?

**Comment by adrigabri** [comment]
Im changing from rxtools to Luma, when i have it all i give you news.

**Comment by adrigabri** [comment]
Hi! I finally installed Luma, and install pksm, but still appears the same error, game not found

**Comment by BernardoGiordano** [comment]
can you say to me the exact same steps you're doing?

**Comment by adrigabri** [comment]
Of course, i turn on the 3ds, then i go to pksm, i open it, select pokemon moon, and it appears the error

**Comment by BernardoGiordano** [comment]
try seeing if you can access to the cartridge if using the homebrew launcher build

**Comment by adrigabri** [comment]
Well, now it worked! I installed an actualization of the firmware (i thought i was on the last version) and now it works. Thanks and sorry for the apologizes!
