### ISSUE TITLE
DS Games not showing.

### ISSUE THREAD

**Issue by zoosty** [BernardoGiordano/PKSM#190]
Hi, I don't have a whole ton of knowledge about the ds games' support past the fact that Sinnoh games aren't supported. I've tried Heartgold, Black and Black 2. When I select PKSM from Homebrew, I scroll through the applications that are shown and none of the DS games show up. I have an older 3Ds and the 3DS games always show up, I'm also on the latest version of PKSM.

**Comment by BernardoGiordano** [comment]
You have to trigger PokeTransfer in that screen, in order to achieve DS games access.
