### ISSUE TITLE
Crashing When trying to make Mons shiny

### ISSUE THREAD

**Issue by GhastlyFlame** [BernardoGiordano/PKSM#196]
I checked through the feed first this time to make sure it wasn't reported first... Anyways, upon me trying to make any pokemon shiny, it will instantly freeze, and stay frozen until I hold down the power button.

**Comment by BernardoGiordano** [comment]
Does this appear with EVERY mon you're editing? It's basically improbable.

**Comment by GhastlyFlame** [comment]
I tinkered around with it some more, hrs currently only occurring with a
select few boxes of pkmn, 1-3 the rest work fine

**Comment by Vexslasher** [comment]
I had no issues for many days until I tried with this Groudon it completely froze like he said above and I had to power off without saving. I'm pretty sure it is a legit Groudon I traded for it on the GTS.
[383 - Groudon - B79855202A24.zip](https://github.com/BernardoGiordano/PKSM/files/775630/383.-.Groudon.-.B79855202A24.zip)
