### ISSUE TITLE
Not all items are injectable

### ISSUE THREAD

**Issue by altxna** [BernardoGiordano/PKSM#20]
I noticed most evolution items and a lot more are missing. Do you need help finding the values? If you point me in the right direction I can do that gruntwork of it.

**Comment by BernardoGiordano** [comment]
I know, items injected are only a part of the all available. Items available right there are the ones useful in the story (i.e. leftovers, life orbs, etc) but if you want to help to port all the available (I mean in the game now) you can check PKHeX code and how it generates item values. There should be a cycle that generates item's value

**Comment by altxna** [comment]
The list is here apparently:
https://github.com/kwsch/PKHeX/blob/43cf2370f2e32f059a9f8e5840fed20bad9749d8/PKHeX/Resources/text/en/text_Items_en.txt

In your code I notice you have:
`char *ballsList[BALLS] = {"Master Ball", "Ultra Ball", "Great Ball", "Poke Ball",.....`
and
`u32 balls[BALLS * 2] = {0x01, 0x00, 0x02, 0x00, 0x03, 0x00, 0x04, 0x00,.......`

So the correlation is there and not too difficult. I will have some free time today and I'll try to work through them. Do you need it in any specific format?

**Comment by BernardoGiordano** [comment]
My code only presents a selected list of items, there isn't a particular algorithm that chooses the values listed in those arrays (that's why I currently filled the array by hand and not automatically). If you're willing to write the code, just do a subfunction and we'll see later how to insert it within the app

**Comment by BernardoGiordano** [comment]
closed because it's fixed in the last commit
