### ISSUE TITLE
Bag Editing Suddenly Not Working for S/M

### ISSUE THREAD

**Issue by DrSalvador555** [BernardoGiordano/PKSM#202]
Suddenly the support for editing the bag seems to be absent, it simply gives an error saying it's not currently available for Sun and Moon. Is this a bug, is there some sort of problem relating to the code, or was this disabled for some reason? I'm just not quite sure what the reason is.

**Comment by BernardoGiordano** [comment]
it's not implemented yet, that's why that popup.

**Comment by DrSalvador555** [comment]
That's very strange, I managed to get it working before. I used it in Sun a little over a week ago and I got 999 rare candies and bottle caps and more. I can provide a photo if that'll help O.o
