### ISSUE TITLE
Redirection failed

### ISSUE THREAD

**Issue by Shet1981** [BernardoGiordano/PKSM#204]
Hello!

Every time I launch PKSM, I a=have a "redirection failed" message, and I can just keep on pushin A until it closes...

My wifi is on, and I tried to manually put the additionalassets on the sdcard, without any change...

What else could I try?

Thanks, Julie

**Comment by BernardoGiordano** [comment]
Online resourcea has been updated, so you have to wait for a new PKSM release, that will appear in a couple hours.

**Comment by Shet1981** [comment]
ok thanks I'll wait and try!
