### ISSUE TITLE
Species Not Obtainable Prior to Bank Release?

### ISSUE THREAD

**Issue by SolgaleoLunala** [BernardoGiordano/PKSM#206]
whats does this mean?  im trying to make a ralts to send to moon and it keeps saying that.ispecies is not obrainable prior to bank release,bank just came out though so im confused  , i thought the update was supposed to make pokemon from other gens legal?

**Comment by BernardoGiordano** [comment]
Why are you reporting PKHeX old version's messages?

**Comment by SolgaleoLunala** [comment]
im on the new version just released and thats what it says   for every non gen 7 pokemon

**Comment by BernardoGiordano** [comment]
New version of what?

**Comment by SolgaleoLunala** [comment]
of your program

**Comment by SolgaleoLunala** [comment]
4.0.1

**Comment by SolgaleoLunala** [comment]
i mean 4.1.0

**Comment by BernardoGiordano** [comment]
Why are you reporting this here, WHEN YOU CLEARLY HAVE A OLD PKHEX VERSION INSTALLED?

**Comment by SolgaleoLunala** [comment]
i dont know  D:  i thought it auto updates when you put it in the computer   :(     i thought u did the pkhex program im a noob sorry  where do i find the latest version?

**Comment by SolgaleoLunala** [comment]
i think i found the latest version but how do i open it it looks different from the other one   theres no exe. type thing for me to click on
