### ISSUE TITLE
EXTRA STORAGE

### ISSUE THREAD

**Issue by Tobyheiam** [BernardoGiordano/PKSM#207]
SOMETHING WRONG IN 4.1, CAN'T TRANSFER WHOLE BOX OF POKEMON TO BANK, ONLY HALF POKEMON WILL BE PUT TO THE UPER SCREEN, THE TRANSFER OF REST POKEMON SHOULD DONE BY HAND.

**Comment by BernardoGiordano** [comment]
I put cheks to avoid gen7s going to gen6s and check to don't touch battle boxed elements.

**Comment by Tobyheiam** [comment]
Sorry for my bad English, but actually it's not about checks because I'm doing on my AS, and you can test it just by click the switch whole box button.

**Comment by BernardoGiordano** [comment]
it works fine for me, weird

**Comment by Tobyheiam** [comment]
My bad, just delete it and install 4.1 again it seems fine now, sorry for bothering you.
