### ISSUE TITLE
Save file keeps corrupting on Pokemon PL

### ISSUE THREAD

**Issue by TheCodPunch696** [BernardoGiordano/PKSM#208]
My Pokemon Platinum Keeps telling me save file is corrupt. And im not using gifts from a other reigon Please let me know how to fix this or if its a flaw.

**Comment by BernardoGiordano** [comment]
This is impossible. You must have selected the wrong game in the title selection screen.

**Comment by Orionsilver** [comment]
@TheCodPunch696 
If you're on HBL: you need to trigger PokeTransfer to be able to use DS games.
