### ISSUE TITLE
security function or some kind of error?

### ISSUE THREAD

**Issue by Striderxs** [BernardoGiordano/PKSM#212]
Always i start pksm asks for parental control password...why?

**Comment by BernardoGiordano** [comment]
it's your system that is fucked up

**Comment by Striderxs** [comment]
Putting aside your contemptible way of responding.
I asked because this trouble appear in 4.1.0 and 4.1.1. I used the old version without problem. 
Recently a few hours ago i was install other h.b, games and 0 problems. Anyway if you think that is the system maybe and  it is,thanks.

**Comment by BernardoGiordano** [comment]
PKSM doesn't have any kind of code that could trigger parental control password. Do you have that function enabled, in general?

**Comment by Striderxs** [comment]
That's the weird point because all the restrictions are disabled, always try to made a clean installation of  every version and now i don't know the mistake.
Whatever, after put the password all is functionally good in pksm. And from here to who knows i'll put the pass. 
Thanks for your time.

**Comment by BernardoGiordano** [comment]
I hope that's not related to the buildtools setup; I didn't reach to reproduce the error. Sorrg if being a bit rude at the beginning but it's been a hard day in the issue tracker, today.

**Comment by Striderxs** [comment]
Ok, no problem, keep the good job and  patience.
Thanks again.
