### ISSUE TITLE
Red Cross = Legality issue?

### ISSUE THREAD

**Issue by StreakArrow** [BernardoGiordano/PKSM#213]
does a red cross mean its illegal?

And how would i fix it?

**Comment by BernardoGiordano** [comment]
go read changelog

**Comment by StreakArrow** [comment]
@BernardoGiordano Yeah, i read its disabled, but does this mean they're illegal? (not legal?)

**Comment by BernardoGiordano** [comment]
It means that they have not been transferred with official methods and MAY cause legality issues. It's a warning.

**Comment by StreakArrow** [comment]
I use PKSM to transfer PK files from PKHEX to PKSM and insert easily ingame. Is there like a ribbon or smth i have to add to show as the "official method"?? thanks

**Comment by BernardoGiordano** [comment]
You have to wait.
