### ISSUE TITLE
Problem with Handling Trainer Data

### ISSUE THREAD

**Issue by Ewolfy7** [BernardoGiordano/PKSM#214]
Hi! There seems to be a problem with the way PKSM handles Handling Trainer Data every time I have edited Pokemon data. I have edit once by changing a Pokemon's nature and the second time by changing three Pokemon's  moves to ones found in their official Move Remainder list. I thought to run them through PKHeX's legality checker and discovered that each Pokemon I've edited with PKSM have a male trainer listed as "ù!" without quotation marks as their Handling Trainer and thus causing PKHeX to consider them to be illegal. I know I can fix this issue within PKHeX itself by changing back to blank or current HT's name if it's a traded Pokemon but I'd rather not have to do that because I like having PKSM as somewhat of a portable version of PKHeX. Everything else seems to be solid. Thanks for creating such an awesome program!

**Comment by Anty-Lemon** [comment]
Known and fixed
