### ISSUE TITLE
Issues with Pumpkaboo and Gourgeist

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#216]
Ever since the update, I can't extract any Pumpkaboo or Gourgeist from m extra storage. I can place mine inside the extra storage boxes, but then I can't take them out. No matter what I try. Upon further investigation, it seems that they aren't supported by the forme changer like other Pokemon are. I don't know if the program can't be recognize a different formed one (mine are Super-Sized) but now I can't move Pumpkaboo or Gourgeist around the bank

**Comment by BernardoGiordano** [comment]
no worries, we'll fix it in the next update :)

**Comment by PKMWM1** [comment]
Thank you your swift response. If you could, could I get a rough eta? Later today? a few days? A week?  Just curious? Thank you so much for this program. It makes managing all my games so much easier and convenient.

**Comment by Anty-Lemon** [comment]
Fixed in afcff3f644aee036106a5992b8fce2ee5c8066d1

It's hard to say when the next update will come. Maybe a few days, maybe a few weeks. If you would like to have this fix early, you can [compile it](https://github.com/BernardoGiordano/PKSM#compiling).

**Comment by PKMWM1** [comment]
How do I compile it?

**Comment by Anty-Lemon** [comment]
Never mind, I'll just compile it for you. [Here](https://www.dropbox.com/s/mhgo5rouji2jcbh/PKSM.zip?dl=0)'s a build with the fix
