### ISSUE TITLE
How to compile??

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#218]
I want to compile the latest version but I have no idea how. I downloaded all the files it said that were necessary, but I don't know how to install them, where to place them all in relation to each other etc. Any help would be greatly appreciated.

**Comment by Anty-Lemon** [comment]
Assuming you're on Windows, compiling a 3DS app is very counter-intuitive. If you're not the tinkering type it isn't worth learning how to compile it just to get a bug fix early.

If you're set on compiling it yourself, despite having the build I posted on the other issue, you can get started by [installing devkitpro](http://devkitpro.org/wiki/Getting_Started/devkitARM). The libraries you downloaded should have instructions included about installing them
