### ISSUE TITLE
Feature request: edit save's OT name

### ISSUE THREAD

**Issue by designgears** [BernardoGiordano/PKSM#22]
It would awesome if you could add the ability to change the trainers name. I have lots of saves with the same name, it would be nice to be able to rename them so I can better identify which one I have loaded.

**Comment by BernardoGiordano** [comment]
I was already thinking about this, it should not be difficult. It will be added in the near future

**Comment by MattOlivoto** [comment]
Question ! I started using your software here at version 4.2.1,
I edited some stuff from pokemon OR, i wanna know where is the option to change my PID/TID (Don't know which one of those) can allow me to nickname the pokemon from inside the game (Nickname NPC). I know it's necessary the same number for the game to know that pokemon as yours.
Is this possible?
Sorry for my bad english btw

**Comment by samisathenaaa** [comment]
universal scripts has one

**Comment by GriffinG1** [comment]
@samisathenaaa please do not post on almost 5 year old closed issues, thanks.

**Comment by eliotwaddell** [comment]
bruh i dont know how to do it, dont shit on my boy for tryna help
