### ISSUE TITLE
Cloning legal 'mon results in illegal 'mon on 4.1.1

### ISSUE THREAD

**Issue by cdhowie** [BernardoGiordano/PKSM#221]
Every time I clone a 'mon in 4.1.1, the cloned 'mon is illegal (can't be traded on wonder trade) but the original remains legal.  I spot checked both and can't find any differences, yet one can be traded and one cannot.

I do not have this problem after downgrading back to 4.0.3.

**Comment by Anty-Lemon** [comment]
Have you checked its HT name?

**Comment by cdhowie** [comment]
I would be happy to check that, but do not know how to.  Are there any docs you can point me to?

**Comment by Anty-Lemon** [comment]
There is currently no way to see the HT name in PKSM. You would have to check in PKHeX, by dumping your savedata from your 3DS cart (with svdt, save_manager, etc.)

**Comment by cdhowie** [comment]
BTW, I did some more tests and it seems that any Pokemon created/modified with 4.1.1 is illegal, in my tests.  Taking a valid pokemon and editing a single IV is enough to get flagged.  The same IV change on the same Pokemon with 4.0.3 does not get flagged.

I will take PKHeX dumps of original, modified/cloned with 4.1.1, and modified/cloned with 4.0.3 and see if there are any differences between the 4.1.1 and 4.0.3 files (and against the original in the clone-only case).

**Comment by BernardoGiordano** [comment]
It's the bug with the held trainer that cause the mon to not be tradeable. It'll be fixed in the next release.

**Comment by BernardoGiordano** [comment]
fixed in the last series of commits.
