### ISSUE TITLE
Pksm issue

### ISSUE THREAD

**Issue by TruPa1n91** [BernardoGiordano/PKSM#222]
I'm having an issue with trying to use pksm, I have hombrewed my ds also have fbi and all that other stuff you should need by the 40+ mintue YouTube video I watched (almost bricked my ds in the process but fixed that with a YouTube video), but pksm won't work and I've tried several YouTube videos to see what could be wrong. The top screen just stays at loading graphics please wait and bottom screen well it comes up with a cover of black and white square's over the wallpaper,  kinda like a glitch I think.

**Comment by BernardoGiordano** [comment]
y o u t u b e  v i d e o s ?

Please follow installation instructions as stated in the readme. Youtube tutorials are shit. Here's the right place you need to look for things done in the right way.

**Comment by p410n3** [comment]
Oh my...
