### ISSUE TITLE
Game not found 

### ISSUE THREAD

**Issue by jlh2233** [BernardoGiordano/PKSM#223]
ok so im really new to homebrew but i have a 3ds & a 2ds both on 11.2 using soundhax as a homebrew entry point i pasted the pksm file from into the 3ds folder launched homebrew went into pksm selected my game pokemon moon (cartridge) and it says game not found im using the d pad to select the games in the 3ds but its not finding it i tried this as a alternative to pkhex since neither save manager nor jksm would import my files back into the game after i edited them i tried this in both consoles with both sun and moon and nothing either time it be great if you could helpme out or tell me what im doing wrong im just trynna have a custom team for the playthrough. Ps I moved the dpad

**Comment by Anty-Lemon** [comment]
This is the third time you have posted this issue. Stop.

I will reopen the original issue instead
