### ISSUE TITLE
Suggestions? 

### ISSUE THREAD

**Issue by TruPa1n91** [BernardoGiordano/PKSM#224]
Is there a phone app for Android that will allow the compiling process to be done. I've done all the work so far with my android phone just been removing my sd card from ds to phone and repeat when needed.

**Comment by BernardoGiordano** [comment]
compiling process?

**Comment by TruPa1n91** [comment]
All of this.

Compiling

You need devKitPro, ctrulib, sf2d, sfil, sftd and Xerpi's portlibs to be able to compile this. When cloning the repo make sure to use git clone --recursive in order to also get buildtools.

Lastly in case you're compiling for homebrew usage ensure you also create an xml file with <targets selectable="true"></targets> and put it along side the .3dsx file with matching names.

**Comment by Anty-Lemon** [comment]
Why in the world would you ever want to compile on a phone?

This is not at all what devkitpro was designed for, let alone PKSM. I would highly recommend just compiling it on your desktop and using an SD card reader
