### ISSUE TITLE
Latest (non OT) Handler changed

### ISSUE THREAD

**Issue by substance154** [BernardoGiordano/PKSM#225]
After taking a pokemon with my OT from the external storage, the slot "Latest (non OT) Handler" that should be empty now shows "ù!", 
this is in the same game, left it and took it in Moon

**Comment by BernardoGiordano** [comment]
we know about this bug, we're working to fix it. It will happen every time you edit something with 4.1.1/4.1.0. Will be reverted asap.

**Comment by cdhowie** [comment]
I'm guessing it's the same bug as #221

**Comment by BernardoGiordano** [comment]
yes it is.

**Comment by blackwing182** [comment]
@BernardoGiordano  if you got a chance, can you add an option to set a spesific OT.

Example.

If i use the livin dex option, all pokes will be save as PKSM, can That Be chamged so the OT Be what ever our ING Is As OT? Just for regular pokes not events.

**Comment by substance154** [comment]
@BernardoGiordano thanks for the clarification.

**Comment by BernardoGiordano** [comment]
fixed in the last series of commits.
