### ISSUE TITLE
Error: Living Pokedex generates illegal Pokemon

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#227]
The living Pokedex option which generates one of every Pokemon is close to being legal. However, a lot of Pokemon don't have moves in the relearn section. For example, Bulbasaur has to have at least tackle. Most Pokemon follow this trend. I don't plan to trade them, just keep them in the Pokemon Bank, but fear that they will be flagged.

**Comment by jjaldridge2009** [comment]
Can confirm, this extends to the Generate function in most cases,

I generated 3 or 4 Pokemon to test, and they were all created with blank "Relearn Moves."

**Comment by PKMWM1** [comment]
That being said, Pokemon that originated before gen 6, such as N's Collection and Entree Forest, won't have any relearn moves since that was a feature added in Gen 6 and these Pokemon originated pre gen 6

**Comment by BernardoGiordano** [comment]
are you talking about gen7 living dex or gen6 living dex? because gen7 living dex is legal, every mon have the relearn moves he has to have.

**Comment by PKMWM1** [comment]
The Gen 6 Dex. Most of the Pokemon Have this problem.
