### ISSUE TITLE
Can't edit Pokemon in Team

### ISSUE THREAD

**Issue by Matdu10** [BernardoGiordano/PKSM#228]
There's some kind of bug trying to edit pokemon in my Team : 

First, trying to enter the "Edit" menu is buggy : Pressing A on Edit does nothing, but going in Clone, B, and Edit work. Weird

Then, editing one Pokemon and saving, it reverts back to before editing.

I think that's a bug, or I might do something very wrong here?

**Comment by BernardoGiordano** [comment]
That has been disabled in one of the past releases, go read related changelogs. It's not a bug.

**Comment by Matdu10** [comment]
Ok, thanks :)
