### ISSUE TITLE
Enable Evolution\Hatching in Editor

### ISSUE THREAD

**Issue by jjaldridge2009** [BernardoGiordano/PKSM#230]
Just a feature suggestion that I think will be greatly appreciated for competitive battlers.

In the interest of preserving the legality of my Pokemon as much as possible, I don't typically use the "Generate" function, unless its for breeding parents I currently don't have. (The Generate function scares me, because of the recent ban wave, and the inconsistent Relearn moves that I saw on some of the test mons I generated.)

So when I want a new competitive Pokemon, I breed and hatch the egg, place it in the box, load up PKSM, and then edit the Pokemon's stats\moves\item\nature\ability to my desired values.

However, after doing so, I still need to reload the game, put the newly hatched\edited Pokemon in my party, and gain them levels via Rare Candy\Battling to Evolve.

In order to circumvent this, having an option to "hatch" the egg and "evolve" the Pokemon within the editor would be an awesome feature. Then the only part I'd need to handle in game is the generation of the egg itself.

EDIT: Removed nickname related issue from report.

**Comment by Anty-Lemon** [comment]
> In several cases I tried recently, when I evolved my Cubone "NicholasCage" into Alolan Marowak, his name was changed to just Marowak. I applied the nickname to a Cubone I had hatched in the manner described above, but from within PKSM, rather than when the egg hatched. Seems to be some sort of flag on the nickname field that isn't being applied when the Pokemon's first nickname is given in PKSM.

That is not relevant to this issue. We are aware of #46 already

**Comment by BernardoGiordano** [comment]
I think this would be a ton of work, because we should map every evolution level. You can manually raise the level of things you like with PKSM and give it a rare candy to make it evolve without battling. It's 20 seconds more for you, instead of at least 10 hours of work for me (probably more).
