### ISSUE TITLE
HELP!!! Still won't work on me

### ISSUE THREAD

**Issue by WisnuHZzz** [BernardoGiordano/PKSM#232]
I've already trying to downloading assets from 3rd party, but it failed
So i tried to manually moving all additionalassets' file to sd card, but it still won't work
I've already got latest file

Please help me...

**Comment by BernardoGiordano** [comment]
Do you have 4.1.1?

**Comment by WisnuHZzz** [comment]
Yes, i'm using qr code to download the .cia, and i've checked that it's 4.1.1

**Comment by WisnuHZzz** [comment]
Ahh nvm...the files in this link aren't complete
https://github.com/dsoldier/PKResources/tree/master/additionalassets
I asked my friend to send the assets and some files are missing from that link

**Comment by WisnuHZzz** [comment]
Ahh nvm...the files in this link aren't complete
https://github.com/dsoldier/PKResources/tree/master/additionalassets
I asked my friend to send the assets and some files are missing from that link

**Comment by Anty-Lemon** [comment]
The non-v2 files are obsolete. You are on an outdated version
