### ISSUE TITLE
Does 4.1.1 always create illegal pokemon?

### ISSUE THREAD

**Issue by dustinxiv** [BernardoGiordano/PKSM#233]

**Comment by BernardoGiordano** [comment]
There aren't enough testers to prove it or not. I was able to trade things generated with 4.1.1 but there were a couple isolated cases that could not.

**Comment by dustinxiv** [comment]
thanks for the quick reply! I'll download anyways since i probably won't go online and have no friends.

**Comment by BernardoGiordano** [comment]
We're mostly ready to release a new version eventually in the next days.
