### ISSUE TITLE
Frozen

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#234]
Can you help me. I dowmloaded the 4.1. pksm and it worked fine for 2 days. But now when I go into it and press anything from the management menu for editing pokemon or for the bank the whole thing freezes. It works for the the wondercard injection and for ds games. Also it works when i go back to 4.0 I dont know wjy it wont work. Help me please. I tried deleting it off my sd card and re downloading it on the sd card but it wont work. For pokemon sun and moon

**Comment by BernardoGiordano** [comment]
Try deleting the application from system settings and wiping the /3ds/data/PKSM/additionalassets/ folder manually

**Comment by KofiMatson123** [comment]
Okay ill try

**Comment by KofiMatson123** [comment]
Im using Soundhax hbl to use pksm i dont think that will work. I only have access to my phone. I dont have a computer. How about i try to redownload the whole thing?

**Comment by BernardoGiordano** [comment]
I don't get the problem, can't you use a FTP client on your phone to fix the files on the 3ds ?

**Comment by KofiMatson123** [comment]
Whats FTP?

**Comment by KofiMatson123** [comment]
On my hombrew menu theres an application call FTPD II TURBO

**Comment by KofiMatson123** [comment]
Please help me

**Comment by BernardoGiordano** [comment]
That is a FTP server. You can send files from your phone if you install a FTP client on it. Google for more infos, as they're not related with pksm.

**Comment by KofiMatson123** [comment]
K thanks

**Comment by KofiMatson123** [comment]
I should just redownload everything

**Comment by KofiMatson123** [comment]
I should just redownload everything..... i just downloaded the newest updatr but it didnt work still.

**Comment by BernardoGiordano** [comment]
I still don't get what's the real problem.

**Comment by KofiMatson123** [comment]
I deleted my moon save file and the pokemon editor works. I was only up to hau oli city anyway. But i cant do it on sun because thats my main game and has every thing on it

**Comment by BernardoGiordano** [comment]
Are you sure that #127 isn't the same issue as yours?

**Comment by KofiMatson123** [comment]
It maight be but i havent made any eggs ive modified some eggs to hold items. But thought that was the issue so i releases them. If you could me resolve this problem that would be fanrastic

**Comment by KofiMatson123** [comment]
The problem is when i go and press the pokemon editor or the bank options for sun and moon, pksm just freezes and  i dont know what to do about it.😭

**Comment by BernardoGiordano** [comment]
can you send me your save in some ways? I think there's something messed up with some of your pokemons in the first box.

**Comment by KofiMatson123** [comment]
How do i do that?

**Comment by BernardoGiordano** [comment]
FTP, as explained before.

**Comment by KofiMatson123** [comment]
How do I do that?

**Comment by KofiMatson123** [comment]
How do I do that?

**Comment by KofiMatson123** [comment]
Luke I said before I dont know how to do that you need to explain it to me

**Comment by BernardoGiordano** [comment]
download a FTP client on your phone, connect it with a FTP server on the console (which is available if you have homebrew) and transfer a dump created with JKSM. More infos are available on the pages of the respective softwares.

**Comment by KofiMatson123** [comment]
This problem is happening with all gen6 and gen7 games

**Comment by BernardoGiordano** [comment]
> Try deleting the application from system settings and wiping the /3ds/data/PKSM/additionalassets/ folder manually

**Comment by KofiMatson123** [comment]
But I dont understand what you mean. What application do I delete? How to i wipe it manually

**Comment by BernardoGiordano** [comment]
PKSM! Did you ever deleted a file in your life?

**Comment by KofiMatson123** [comment]
But that isnt in my system settings on my 3ds

**Comment by BernardoGiordano** [comment]
I thought it was obvious that you have to delete it from the sd card.

**Comment by KofiMatson123** [comment]
Okay I deleted it. Sorry for your patience with me. What do i do now. I deleted the additional assets folder manually and deleted pksm. What should i do now

**Comment by BernardoGiordano** [comment]
go into the releases page, download the latest release and use it. Report if the bug's still there or close this issue if everything works now.

**Comment by KofiMatson123** [comment]
Okay thnx ill reply when ive reinstalled it thnx!!

**Comment by KofiMatson123** [comment]
It works thank you so much!!!!!! If it happens again ill just do what i did again!!!!

**Comment by BernardoGiordano** [comment]
thanks god it was easy in the end. enjoy the software :)

**Comment by KofiMatson123** [comment]
Thank you for making it 😁
