### ISSUE TITLE
Which Version

### ISSUE THREAD

**Issue by Zombicrafts** [BernardoGiordano/PKSM#236]
Absolutely Love this by the way as a single father of two its hard to find time to breed and ev pokes for VGC so ty. 
My question is which version should i use right now? Im on 4.1.0 but wondering if i need to wait on updating to 4.1.1 bc i see it wont allow pokes to be legal that are edited or was i reading wrong

**Comment by BernardoGiordano** [comment]
4.1.0 has the same bug. Wait for ghe new version to be safer
