### ISSUE TITLE
[Suggestion] Set Trainer to Self

### ISSUE THREAD

**Issue by DemonGamesXIII** [BernardoGiordano/PKSM#237]
Simple and to the point: Take the Trainer ID, Special ID and Original Trainer name and place it as yourself, provided PKSM uses it's own TID and SID. Otherwise, when genning Pokémon, have it by default set it's OT name to your name.

**Comment by Anty-Lemon** [comment]
Pressing the purple button has this exact effect, sans the OT name

**Comment by DemonGamesXIII** [comment]
Thanks.
