### ISSUE TITLE
PKSM 4.1 error in Pkhex 17.01.31

### ISSUE THREAD

**Issue by Zullivan1987** [BernardoGiordano/PKSM#239]
When editing a pokemon in "PKSM" and then you see the data edited in "PKHEX", rare characters appear in the section: "OT handler", whether you edit the "IVS", "EVS" or "HA" appear Those rare characters, in my case it appears these:  ù! - ??@ù! - **ù!

(Sorry for  my bad enlgish)

![error](https://cloud.githubusercontent.com/assets/25548369/22618429/85d9ff5e-eaa1-11e6-9b5f-8e8440d1da4c.png)

**Comment by BernardoGiordano** [comment]
known and already fixed in the latest commits
