### ISSUE TITLE
Unable to enable godmode 

### ISSUE THREAD

**Issue by Troykaka** [BernardoGiordano/PKSM#241]
I cannot figure it out for the lifetime of me.. am I missing something?

**Comment by giomaher** [comment]
Please where can i find the touch secuence?? @BernardoGiordano thank you very much for PKSM

**Comment by rsanch1** [comment]
I think I found it....go to Pokémon editor. Select a Pokémon to edit and then tap the hex code in the top right corner.

**Comment by giomaher** [comment]
I see, thanks, mejor ni le muevo.

**Comment by DemonGamesXIII** [comment]
Can confirm that godmode IS IN the Hex Editor. Tap the screen corners in this order: top-left, top-right, bottom-left, bottom-right.

**Comment by giomaher** [comment]
Thanks, where did you find that info?

**Comment by DemonGamesXIII** [comment]
I just read the source code for editor.c and look for "pattern". After that, it was a matter of finding the spots. I found out that you don't actually have to tap them in the exact order, but tapping one corner twice is the same as not tapping the corner at all. If it doesn't work, go through each corner and tap it twice to see which one is off. You will find it when your hex editor turns red.

**Comment by giomaher** [comment]
Gg excelent, thanks, the screen turns kind of red.

**Comment by DemonGamesXIII** [comment]
That is intended.

**Comment by SomeWhatInterestingLemon** [comment]
Where do you tap

**Comment by DemonGamesXIII** [comment]
> 
> 
> Where do you tap
> for godmode

Please refer to my post from the 6th of February in 2017:


> 
> 
> Can confirm that godmode IS IN the Hex Editor. Tap the screen corners in this order: top-left, top-right, bottom-left, bottom-right.

**Comment by SomeWhatInterestingLemon** [comment]
thanks it unlocked some gray ones the hex editor did not turn red though

**Comment by DemonGamesXIII** [comment]
As long as it unlocked the gray boxes then you’re good to go.

**Comment by piepie62** [comment]
Please do not reveal the hex editor god mode code openly. It should not be necessary for non-experimental usage. It being so would be considered a bug by me.

**Comment by DemonGamesXIII** [comment]
> 
> 
> Please do not reveal the hex editor god mode code openly. It should not be necessary for non-experimental usage. It being so would be considered a bug by me.

👌
