### ISSUE TITLE
Feature request: batch editing

### ISSUE THREAD

**Issue by Shet1981** [BernardoGiordano/PKSM#242]
Hello !
Id there a way I can edit multiple pokemons at the same time? (for example edit all my pokemons with the same level, trainer name, held item without doing it one by one)

Thanks a lot

Julie

**Comment by lewishack** [comment]
You can use PKHeX to do exactly that, however I agree having a native PKSM variation of a batch edit would be a very very nice feature!

**Comment by BernardoGiordano** [comment]
This could be very tedious to do, closing it for now.
