### ISSUE TITLE
Add Form Changing

### ISSUE THREAD

**Issue by SuperMario64fan** [BernardoGiordano/PKSM#246]
Simple as that. It will be easier to get gen 1 - 6 formed pokémon and change Ash Pikachu's hat

**Comment by BernardoGiordano** [comment]
it is available from ages, man.

**Comment by SuperMario64fan** [comment]
How? What version?

**Comment by Veranek** [comment]
You can edit Pokemon forms in 4.2.0.

**Comment by Anty-Lemon** [comment]
Tap the Pokemon's sprite in the edit menu. This was added in 4.1

**Comment by SuperMario64fan** [comment]
Thanks, just had to reinstall because I can't update in app :)
