### ISSUE TITLE
Are these Pokemon completely legal now. (4.2)

### ISSUE THREAD

**Issue by Veranek** [BernardoGiordano/PKSM#247]
Hey Bernardo, sorry to be _that guy_ but I have to ask:

Does transferring from ORASXY to SM via PKSM result in the same Pokemon that would result when you transfer from the original Pokebank? Thanks!

**Comment by BernardoGiordano** [comment]
I can't assure that. The behaviour is similar but this is not a clone of the official bank, they work differently.

**Comment by Veranek** [comment]
Ok, thank you!
