### ISSUE TITLE
Some pokemon cant be editable

### ISSUE THREAD

**Issue by giomaher** [BernardoGiordano/PKSM#248]
In the last commit of 4.2, i can't edit some pokemons, i'm in the pokemon editor push "A" and nothing happens, this is just with a few pokemon.

**Comment by BernardoGiordano** [comment]
Are they in the battle box?

**Comment by giomaher** [comment]
jejeje, yes.

**Comment by giomaher** [comment]
i saw, all of them are in the battle boxes.

**Comment by BernardoGiordano** [comment]
that's why.

**Comment by giomaher** [comment]
Sorry, i did't know. "No me había pasado antes" , thanks for answer.
