### ISSUE TITLE
Living Dex injection

### ISSUE THREAD

**Issue by lewishack** [BernardoGiordano/PKSM#249]
Living Dex doesn't work right on OR/AS. Most pokemon end up in unhatchable Eggs.

Also all the Living Dex pokemon are from Spain as their origin country, any way to change this en-masse? or do they have to be individually changed?

Thanks!

**Comment by SebPro101** [comment]
Hey I have the same problem, I tried in Pokemon X and OR and both had lots as eggs and wasn't a living dex at that point .
