### ISSUE TITLE
Living dex issues even after installed fix

### ISSUE THREAD

**Issue by SebPro101** [BernardoGiordano/PKSM#251]
It still have unhatchable eggs but now I noticed some mons are now nit eggs and now some are

**Comment by BernardoGiordano** [comment]
But you didn't install any fix. I still have to release it.

**Comment by SebPro101** [comment]
The Thread we did yesterday didn't you give us a fix , I think #249

**Comment by BernardoGiordano** [comment]
I committed the fix, but it's not yet released to the public.

**Comment by SebPro101** [comment]
My bad, good luck on that then :)
