### ISSUE TITLE
Changing Marking? Like clover mark on SunMoon?

### ISSUE THREAD

**Issue by WisnuHZzz** [BernardoGiordano/PKSM#252]
Is there any way to change marking, like removing clover mark so it become non-alola pokemon?

**Comment by Anty-Lemon** [comment]
The region marker is editable by using godmode in the hex editor, then changing Version (0xDF)

**Comment by WisnuHZzz** [comment]
How to enable godmode?

**Comment by Anty-Lemon** [comment]
Currently, it's an easter egg. Tap all four corners of the hex editor menu's bottom screen

**Comment by WisnuHZzz** [comment]
Oh i c...thanks
