### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by giveup** [BernardoGiordano/PKSM#253]
Using  Xerpi's portlibs and latest devkit r46 on Mac.
> output/3ds-arm/PKSM.elf
> /opt/devkitpro/portlibs/armv6k/lib/libfreetype.a(ftbzip2.o): In function `ft_bzip2_stream_close':
> ftbzip2.c:(.text+0x24): undefined reference to `BZ2_bzDecompressEnd'
> /opt/devkitpro/portlibs/armv6k/lib/libfreetype.a(ftbzip2.o): In function `ft_bzip2_file_fill_output':
> ftbzip2.c:(.text+0x10c): undefined reference to `BZ2_bzDecompress'
> /opt/devkitpro/portlibs/armv6k/lib/libfreetype.a(ftbzip2.o): In function `ft_bzip2_stream_io':
> ftbzip2.c:(.text+0x284): undefined reference to `BZ2_bzDecompressEnd'
> ftbzip2.c:(.text+0x2c0): undefined reference to `BZ2_bzDecompressInit'
> /opt/devkitpro/portlibs/armv6k/lib/libfreetype.a(ftbzip2.o): In function `FT_Stream_OpenBzip2':
> ftbzip2.c:(.text+0x4bc): undefined reference to `BZ2_bzDecompressInit'
> collect2: error: ld returned 1 exit status
> make: *** [output/3ds-arm/PKSM.elf] Error 1

And I have manually installed the bzip2

`$(BZIP2): $(BZIP2_SRC)
	@[ -d $(BZIP2_VERSION) ] || tar -xzf $<
	@cd $(BZIP2_VERSION)
	@$(MAKE) -C $(BZIP2_VERSION) CC=arm-none-eabi-gcc AR=arm-none-eabi-ar RANLIB=arm-none-eabi-ranlib CPPFLAGS="$(CPPFLAGS)" CFLAGS="-D_FILE_OFFSET_BITS=64 -Winline $(CFLAGS)" libbz2.a
`

**Comment by Anty-Lemon** [comment]
Try the workaround from #182 

> Downgrading to devkitARM r45, installing smealum/ctrulib@396d341, then recompiling all libraries solved the issue.

**Comment by giveup** [comment]
@Anty-Lemon Where I can find 1.0.6-8+b1? The www.bzip.org can not be found.

**Comment by BernardoGiordano** [comment]
reinstall xerpi's portlibs, because it seems that the zip lib isn't visible into your path

**Comment by giveup** [comment]
@BernardoGiordano Just run make all. I'm sure zlib is installed correctly
`/opt/devkitpro/portlibs/armv6k/lib/libz.a`

> Using arm-none-eabi-ar
Using arm-none-eabi-ranlib
Using arm-none-eabi-nm
Checking for arm-none-eabi-gcc...
Building static library libz.a version 1.2.8 with arm-none-eabi-gcc.
Checking for off64_t... No.

> arm-none-eabi-ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -O3 -mword-relocations -fomit-frame-pointer -ffast-math  -DHAVE_HIDDEN -o example example.o -L. libz.a
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 00008020
arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -O3 -mword-relocations -fomit-frame-pointer -ffast-math  -DHAVE_HIDDEN -I. -c -o minigzip.o test/minigzip.c
arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -O3 -mword-relocations -fomit-frame-pointer -ffast-math  -DHAVE_HIDDEN -o minigzip minigzip.o -L. libz.a
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 00008020
cp libz.a /opt/devkitpro/portlibs/armv6k/lib
chmod 644 /opt/devkitpro/portlibs/armv6k/lib/libz.a
cp zlib.3 /opt/devkitpro/portlibs/armv6k/share/man/man3
chmod 644 /opt/devkitpro/portlibs/armv6k/share/man/man3/zlib.3
cp zlib.pc /opt/devkitpro/portlibs/armv6k/lib/pkgconfig
chmod 644 /opt/devkitpro/portlibs/armv6k/lib/pkgconfig/zlib.pc
cp zlib.h zconf.h /opt/devkitpro/portlibs/armv6k/include

**Comment by BernardoGiordano** [comment]
Did you manage to fix the issue?

**Comment by giveup** [comment]
@BernardoGiordano 
No, I also try different versions of zlib and freetype.
The issue still exists. It looks like a toolchain issues.

**Comment by BernardoGiordano** [comment]
I suggest retrying with Xerpi's portlibs, but installing zlib from there for first.
