### ISSUE TITLE
Living Dex Mass Injector for Pokemon XY/ORAS

### ISSUE THREAD

**Issue by kamuisama** [BernardoGiordano/PKSM#257]
There's a bug with the mass injector function for Pokemon XY/ORAS, I think it's because met location was in Sun/Moon? Because all I can see in my in game PC Box was eggs and PKHex showing red box instead.
![pkhex](https://cloud.githubusercontent.com/assets/21088445/22827890/bbe4a7ae-efcc-11e6-8101-4c8a79ec7610.PNG)
![top_0000](https://cloud.githubusercontent.com/assets/21088445/22827916/df1e373a-efcc-11e6-9d03-c217e2683716.png)

**Comment by BernardoGiordano** [comment]
[known and fixed, wait for a new release](https://github.com/BernardoGiordano/PKSM/issues/249)
