### ISSUE TITLE
Pokemon Extra Storage UNMARKS Pokemon with IVs

### ISSUE THREAD

**Issue by kamenrider-darkglass** [BernardoGiordano/PKSM#258]
You know how marking the shapes on a Pokémon summary are used to determine which perfect IVs it has such as Circle for perfect HP, Triangle for Perfect atk, Square for perfect def, etc.? Well, moving *any* Pokemon's position in the "extra storage" tab *unmarks* them whether you're moving them to and from the bank, or just moving their position within your PC box. 

It took me hours to RE-mark all of my Pokémon's IVs because I was moving so many of them around and it is impossible to keep track of which Pokemon has which perfect IVs. Can you fix this so that they stay marked and I wouldn't have to RE-mark them every time I move them around in the Pokémon extra storage tab?

**Comment by Anty-Lemon** [comment]
You are using gen 6, correct?

PKSM currently wipes the gen 6 markings as a legality check for gen 7. I will add a check for SM shortly, to ensure the gen 6 markings are not wiped when using gen 6 titles.
