### ISSUE TITLE
Godmode 

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#259]
Onnthe description for version 4.2 you said there was a godmode that was unlkcked with a touch sequence. How might I actually do that. How do I add a fatefull encounter to the pokemon?

**Comment by Anty-Lemon** [comment]
As stated on #252:

> Currently, it's an easter egg. Tap all four corners of the hex editor menu's bottom screen

Fateful encounter is the first bit of 0x1D. Just add 1 to 0x1D

**Comment by KofiMatson123** [comment]
Thanks
