### ISSUE TITLE
Eggs

### ISSUE THREAD

**Issue by Shey1531** [BernardoGiordano/PKSM#260]
Is there a way to generate eggs? If yes, how? If not, could you add that feature?

**Comment by Anty-Lemon** [comment]
There are currently no plans to generate eggs

**Comment by Shey1531** [comment]
Ok, thanks for the answer. I hope we could get that feature soon. Thanks for the app.

**Comment by pokecal** [comment]
How to generate eggs. (mon turn into egg)
1. Select mon and EDIT.
2. Touch top right corner.
3. Select 0x77, check "is Egg".
4. Save.

Editing following data will enhance legitimacy. (remain after hatching)
0x1D Fateful Encounter flag
0xD1- Egg Date
0xD8- Egg Location
0xDD Met Level
Ready to hatch, edit 0xCA Egg Cycles.

**Comment by Shey1531** [comment]
Thanks pokecal.

**Comment by BernardoGiordano** [comment]
Before you come another time here and say 'I can't check 'is Egg' in the hex editor, you should be aware of the fact that the option is not available yet to the public.

**Comment by Shey1531** [comment]
Ok, thanks for the information.

**Comment by pokecal** [comment]
Thanks, I forgot that the "is Egg" is BETA.
I am now trying to add "Egg mode" for "GENERATE".
