### ISSUE TITLE
Swap Boxes does not work properly with certain boxes

### ISSUE THREAD

**Issue by SonicBlader** [BernardoGiordano/PKSM#261]
In extra storage, once in a while the Swap Boxes option starts acting weird. It moves only certain pokemon from the first box (in-game box) to the second box (PKSM storage box) and vice versa. The pokemon are moved in a certain patterns like only the 1st, 3rd & 5th columns get moved. The pokemon in other columns stay in the original box. This seems to be a random occurance as I have not be able to reproduce it (atleast not voluntarily).

**Comment by Anty-Lemon** [comment]
This is likely intentional. Pokemon can be held in a box for a number of reasons:

Attempting to withdraw...
- A gen 7 mon into a gen 6 title
- A gen 7 form into a gen 6 title
Attempting to deposit...
- A Pokemon in a battle box
- An illegal species (>721)
- An illegal form

**Comment by SonicBlader** [comment]
Well actually this has happened only with Gen7. I don't use Gen6 games with PKSM. All the pokemon I had were either caught/bred/traded in Gen7. I had a whole box of Lunar Magikarps (event one) and only some of them would be moved. If I changed the box (either the bank/game), I was able to move all of them or they moved in a different pattern.

**Comment by BernardoGiordano** [comment]
I just generated a whole box of lunar magikarps. I'm not able to reproduce your issue in every way.

**Comment by BernardoGiordano** [comment]
which version of the application are you using?

**Comment by BernardoGiordano** [comment]
After you reply to those questions, could you make a video (only if this happens on the latest stable build only)?

**Comment by SonicBlader** [comment]
Well the issue is not limited to Lunar Magikarps. I am having that problem with almost every pokemon I have tried. Usually I am able to move them without any problems but occationally I get this glitch.

I am using the latest version 4.2.0 - http://imgur.com/a/evfSW

Here is the video of it - https://www.youtube.com/watch?v=DvPiXLMZac4&feature=youtu.be

**Comment by BernardoGiordano** [comment]
Send me both

**Comment by SonicBlader** [comment]
Here you go - https://drive.google.com/file/d/0B50ruL2NQr4lMEM0OXBMdy03ZHM/view?usp=sharing

I have included the entire 'PKSM' folder just in case. Please let me know when you have downloaded it so I can delete it. I don't want my personal savefile out in the public.

**Comment by BernardoGiordano** [comment]
downloaded, delete it

**Comment by BernardoGiordano** [comment]
I just made an ad-hoc program who clean your bank slots not directly linked to a valid dex number. The executable will be available to the public in the next release (it wiped your bank file just fine, leaving everything important at the right place)

**Comment by SonicBlader** [comment]
Thats great! Thank you!

**Comment by SonicBlader** [comment]
Hello @BernardoGiordano ! (sorry to revive a closed issue)

I updated my PKSM, downloaded the ad-hoc extra storage program and ran it from the homebrew menu. It fixed some 3600~ sectors. I opened the PKSM, it asked me to restart after it updated and I opened it again. I was able to move entire boxes from my game to bank without any problems (even to the bank boxes which previously had the problem)! But after a few box-swappings, the problem began to start again. I used JKSM to make a save file backup and opened the file in PKHeX and there were many redboxes (in PKHeX they are shown when a particular slot has a something with invalid checksum). So I was wondering if your program can be modified to work with the game savefiles?

Thank you!

**Comment by BernardoGiordano** [comment]
can I have your savefile? I can do this easily, but it will be a pc program, not a 3ds one

**Comment by SonicBlader** [comment]
Here is my Moon savefile - https://drive.google.com/open?id=0B50ruL2NQr4ldXg4d0NRem0wOEk

Mainly the boxes in the middle and later half are affected. PC program will be quite fine with me as long as it fixes the problem! Please let me know when you have downloaded it so I can delete the savefile. Thank you!

**Comment by SonicBlader** [comment]
Helllo @BernardoGiordano I was wondering if you had downloaded my savefile so I could delete it?

**Comment by BernardoGiordano** [comment]
delete it. anyways, no one looks here

**Comment by SonicBlader** [comment]
Okay thank you! I hope you are making good progress with the tool! :)

**Comment by SonicBlader** [comment]
Hello @BernardoGiordano !

Sorry for the bother but I was wondering how the PC version of the ad-hoc extra storage program was coming along. :)
