### ISSUE TITLE
trouble creating a legit mew

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#263]
Hello, I have an issue creating mew. I would like to be able to create a legit faraway island mew from emerald but I don't know the location hex or game version hex. Can you please help me do this?

**Comment by zednero** [comment]
I assume that's the sea map mew? When in SuMo it won't be from a faraway island. It's from Kanto / Hoenn, I can't remember which. When I'm home, if I remember, I'll tell you the values you need.

**Comment by KofiMatson123** [comment]
okay thnx. the values for location and stuff will be at the bottom of the hex editor page where you change the game version

**Comment by KofiMatson123** [comment]
I know wont show up like that in SuMo but I need to know so it would of been from emerald and transferred up through the years so I can make them really legit.

**Comment by zednero** [comment]
I know where the values are. 😂 

Might I recommend you join the OT chat, to discuss this further? This isn't a Q+A page. Thus is to report issues with the app itself. 

https://discord.gg/bGKEyfY

**Comment by KofiMatson123** [comment]
where are they?

**Comment by KofiMatson123** [comment]
can you just tell me here because im using my schools computer so I cant really go on anything related to forums or chats

**Comment by zednero** [comment]
Use your phone/home computer. I am at work now, so can't send the values. I won't be able to for around 9 hours.
