### ISSUE TITLE
DS Pokémon cartridge

### ISSUE THREAD

**Issue by ADMOrange0115** [BernardoGiordano/PKSM#265]
Will DS Pokemon cartridge like Pokémon Diamond and Pearl work on PKSM 4.2.0?

**Comment by ADMOrange0115** [comment]
If im using a 3DS with PKSM on it

**Comment by BernardoGiordano** [comment]
Yes

**Comment by sidlabur** [comment]
When i enter pksm and click on diamond while my Pokemon diamond cartridge is inserted, it says wrong size and doesn't work.

**Comment by Midnightabs** [comment]
I'm having a problem where when I select PKSM from Homebrew, it's not finding my DS cartrages at all, whilst 3ds cartridges work perfectly. I have tried Platinum, Soul Silver and White 2. I'm on the most recent build. Any suggestions?

**Comment by BernardoGiordano** [comment]
You REALLY want to read the readme.
