### ISSUE TITLE
Cartridge not found

### ISSUE THREAD

**Issue by alejara93** [BernardoGiordano/PKSM#266]
I try to work with my Pokemon Heart Gold cartridge but PKSM does not recognize it. What could be happens? Does not it support HG/SS cartridges?

**Comment by Anty-Lemon** [comment]
It works with my copy of HG. Does your 3DS recognize the cartridge at all?

**Comment by BernardoGiordano** [comment]
It would be helpful saying which is your setup. I'll assume you have homebrew launcher and you're trying on that. Trigger PKSM with the poketransporter or dream radar.

**Comment by alejara93** [comment]
Yes, my 2DS recognize it without troubles. Working HBL with SoundHax.

**Comment by BernardoGiordano** [comment]
the issue is solved then. Try with said methods and it will work
