### ISSUE TITLE
Cant select battle tree ribbons

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#267]
Im having an issue trying to select the battle tree ribbons. When i press them they stay ref and dont turn green like the other ribbons. Can you help me resolve this issue please.😐

**Comment by BernardoGiordano** [comment]
[known and fixed, wait for a new release](https://github.com/BernardoGiordano/PKSM/commit/50b4c792acdb2be9c3d9145ebb5bd7d40c8cdc4d)

**Comment by KofiMatson123** [comment]
Thanks
