### ISSUE TITLE
Older Games Not Working

### ISSUE THREAD

**Issue by MaximumLevelGamer** [BernardoGiordano/PKSM#268]
So I entered PKSM as usual to try to edit some 'Mons in my HeartGold and Black Version games.  Normally when I chose a game (Pokemon Y for example), it works, but when I chose HeartGold, an error pops up saying "No Cartridge Inserted", even though it is inserted.  Did I do something wrong with the files, or is older game capabilities not working yet? Thanks.

**Comment by alejara93** [comment]
I tried too and my issue was closing without solving it... @BernardoGiordano talk about "Trigger PKSM with the poketransporter or dream radar." but this is not open and edit my HG save

**Comment by MaximumLevelGamer** [comment]
Hmmm... Maybe he means starting PKSM with a different source. For me, when I select PKSM on the homebrew with HeartGold inserted, it says "This app requires a source". When a 3ds Pokemon game is inserted (sun), the source is sun. But when an older Pokemon game is inserted (Black), Pokemon Bank is selected as a default source. Maybe if the source is changed to PokeTransporter, it would work. I don't know if this is what he means though. Let's just hope for a solution.

**Comment by alejara93** [comment]
I though it too but I have no Pokemon Bank/PokeTransporter installed and I can not install it because I'm on 11.2v Then it is not a solution for me and many others whose opened issues before

**Comment by MaximumLevelGamer** [comment]
So I just attempted to use Dream Radar as a source to boot up PKSM. All I got was a black top screen with white lines and a frozen red bottom screen. This is the first time this happened.

**Comment by BernardoGiordano** [comment]
@MaximumLevelGamer retry
@alejara93 what do you mean for 'this does not open and edit my save?'

**Comment by MaximumLevelGamer** [comment]
@BernardoGiordano I retire using Poke Transporter and it worked. When I accessed my save for these games, all I was able to do was chose "events". Is there anything in extras, like Pokemon editor, etc?

**Comment by BernardoGiordano** [comment]
No, that's all.
