### ISSUE TITLE
Checksum Not Saving

### ISSUE THREAD

**Issue by iViscosity** [BernardoGiordano/PKSM#269]
This is probably a stupid question, but I'm experimenting trying to find the values to switch to gen a GB icon mon, and my experiment involves changing several bytes in the hex editor while in godmode. The issue is, when I enter godmode to change the value of the Checksum, byte 1 and 2, as soon as I exit they don't save. 

I've made a document with the two values for each mon, and these are the differences:

https://www.diffchecker.com/42I4wTjO

Encryption Constant I can change and the last 4 in the second row (PID) I can change, but I can't change the last 2 in the first row (CheckSum) and first 2 in second row (MarkValue) without being in godmode. The only issue is when I'm in godmode, the changes don't save. Are these things that can't be changed or what? And if this isn't how to gen a GB icon mon, what else do I need to change?

**Comment by BernardoGiordano** [comment]
Do you know that checksums are always recalculated when you save your edits to a mon?

**Comment by iViscosity** [comment]
I did not. Did I mention I'm very new to hacking? :P Also, sorry this isn't an actual 'issue' I just didn't know where else to ask.

**Comment by BernardoGiordano** [comment]
checksum is recalculated every time you press the save button. that's all, no point in editing it
