### ISSUE TITLE
How to enable God Mode?

### ISSUE THREAD

**Issue by BetaLeaf** [BernardoGiordano/PKSM#271]
So you mentioned a God Mode that would let us change certain values in your latest release:

> All the values not mentioned above (but still existent), like MarkValues, Experience, Regions and weird stuff like that, can still be edited from within the app. I added a sort of godmode that unlocks all the checks letting you do all sort of vandalisms. This is unlockable by entering a touch sequence.

But you didn't tell us how to enable it. What is this magical touch sequence?

**Comment by BernardoGiordano** [comment]
This is intended. Find it

**Comment by KofiMatson123** [comment]
Thee toich mode is touching all four corners of the bottom screen on the hex changing menu
