### ISSUE TITLE
A Few Suggestions

### ISSUE THREAD

**Issue by Vexslasher** [BernardoGiordano/PKSM#272]
**Main Menu Button Layout**
I think the layout of the first menu would be more advantageous to the average user if the events button was the 2nd button instead of the first button, because most people are using that 2nd button almost every time they run this app.

**Cloning To & From Bank**
Also it would be very convenient if cloning could be done from within the extra data/bank area to and from the boxes.

Those are my suggestions I hope you will consider them. I'm not sure how hard that 2nd one would be but it would be nice.

**Comment by BernardoGiordano** [comment]
adding the cloning option in the bank instead is a choice that will not be changed at least in the near future
