### ISSUE TITLE
How to install backup

### ISSUE THREAD

**Issue by Nooblordzzz** [BernardoGiordano/PKSM#274]
I don't know if this has been resolved already and i tried looking into the closed files. How do i get my backup bank? If this has been solved I would like to see the thread as i can't find anything on this.

**Comment by BernardoGiordano** [comment]
backups are located at 3ds/data/PKSM/bank/bank.bak. A backup is created everytime you boot the application.

**Comment by BernardoGiordano** [comment]
You need to rename it as bank.bin and you're fine
