### ISSUE TITLE
NDS games

### ISSUE THREAD

**Issue by Tyulis** [BernardoGiordano/PKSM#275]
Is there any way to edit nds games' saves without buying poketransporter or dream radar?

**Comment by Rizerceo** [comment]
Just insert it in and select the inserted game on the menu.

**Comment by Tyulis** [comment]
It says "cartridge not inserted" or "incorrect size for this game", depending of the game I selected at launch.

**Comment by BernardoGiordano** [comment]
It's not possible without those games.
