### ISSUE TITLE
getAbility gives bad values

### ISSUE THREAD

**Issue by BernardoGiordano** [BernardoGiordano/PKSM#28]
https://github.com/BernardoGiordano/EventAssistant/blob/master/source/editor.c#L599-L618

**Comment by kwsch** [comment]
Is it considered fixed yet?
https://github.com/BernardoGiordano/PKSM/commit/ad887dec2acefbbde33dd629c04003b8168e42f6

**Comment by BernardoGiordano** [comment]
Theoretically! I'll have to do a few tests to check if the app messes up (but it shouldn't)
