### ISSUE TITLE
Feature Request: Default OT presave

### ISSUE THREAD

**Issue by ZakutoRyu** [BernardoGiordano/PKSM#280]
Now this is just me being a bit lazy but could there be an option in a future update where you can add a setting where all non-event mons genned will have whatever OT and TID and SID you predetermin. Not a huge deal but thought I would request for a future update for more of a convenience factor. Other than that, app is pretty perfect to me.

**Comment by BernardoGiordano** [comment]
do you mean a buk setting? If so, it will be useful in edge-cases only, and it will occupy precious space on screen without many people using it. You can do one-by-one with the purple button, it does the exact thing you're asking for
