### ISSUE TITLE
Generation 6: Living Pokedex Gives mostly Bad Eggs.

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#286]
When I use the Mass Injector with Pokemon Omega Ruby to give myself a living Pokedex, when I save it and open it in-game, it almost all just a bunch of eggs that will never hatch and aren't usable. I suspect that the checksums are invalid as I can't even view them in PKHex. A fix would be very appreciated.

**Comment by BernardoGiordano** [comment]
This is known and already fixed, wait for a new release
