### ISSUE TITLE
Feature Request: Make editable Generation 1 Games, please :'v  

### ISSUE THREAD

**Issue by KrlosxD** [BernardoGiordano/PKSM#290]
Hi :D 
Uh... Well, thats all. 
I'll like to know if you will ever do it. 
An option to edit your Pokémon in Gen 1 would be amazing.

Well... Bye... 
I love and appreciate your great job... 

PD: I'm nervous at writing to you xD
PD2: English is my second language, so if I have any grammar error... Sorry :'c

**Comment by BernardoGiordano** [comment]
I'm trying to find kind ways to tell you I don't really care about gen1 games. I don't even have them: I don't want to spend time and money to something I don't really give a fuck about

**Comment by KrlosxD** [comment]
Oh well. It's ok...
I just wanted to have clear that.

Thank you for your answer

2017-03-01 0:45 GMT-06:00 Bernardo Giordano <notifications@github.com>:
