### ISSUE TITLE
Feature Request: Make Trainer gender editable (Held and Original)

### ISSUE THREAD

**Issue by latias1414** [BernardoGiordano/PKSM#291]
Make this editable please.. when using a female trainer and genned a pokemon using your app they doesn't want to obey or listen to the commands.. please make this happen thank you, your application is good though this really needs to be editable..

![1488348688576136522832](https://cloud.githubusercontent.com/assets/26106117/23447922/04c09e9a-fe89-11e6-8c05-710b4e3f8267.jpg)
![14883487433262135017496](https://cloud.githubusercontent.com/assets/26106117/23447945/269b4e70-fe89-11e6-8438-70d690aadcd4.jpg)

**Comment by BernardoGiordano** [comment]
The OT gender has been fixed. The held trainer gender is changed automatically when saving changes to a pokemon.
