### ISSUE TITLE
Feature Request: Select between Cart and Digital

### ISSUE THREAD

**Issue by MegaManZer0** [BernardoGiordano/PKSM#292]
Currently, the cart has priority over digital versions and those can only be accessed with no cart inserted. JKSM allows you to select if you want to read from the cart or go straight to the digital version without needing to remove the cart, as does PCHex++, so the precedent is already there. It would be a great Quality of Life improvement to do it this way over the current method.

**Comment by BernardoGiordano** [comment]
It's not possible rn to change how that into the routine to get saves. Removing a cart takes half a second, it's not that bad

**Comment by BernardoGiordano** [comment]
Just for saying: if you have a OR cart and a Sun digital copy, and you want to edit sun: it will open Sun directly, not the OR cart. That happens when you have both digital and cartridge for the same game at the same time
