### ISSUE TITLE
Help? Pokemon wont trade In Gen 7

### ISSUE THREAD

**Issue by Blitzle33** [BernardoGiordano/PKSM#293]
All my Pokemon are legal in gen 6 but why not in gen 7?

**Comment by BernardoGiordano** [comment]
details are not consistent

**Comment by Blitzle33** [comment]
For those whom use PKSM I have a question to ask. When you transfer your Pokemon to the Pokemon bank on PKSM and take them out to put them into Sun or moon, when you try to trade a Pokemon is it saying that it can't be traded? All my pokes are legit in gen 6 but when I transfer them they are saying can't be traded

**Comment by BernardoGiordano** [comment]
where are you trading them and which kind of stuff is it?

**Comment by Blitzle33** [comment]
details are not consistent
