### ISSUE TITLE
Request?

### ISSUE THREAD

**Issue by Blitzle33** [BernardoGiordano/PKSM#294]
Any plans on adding import Button? Just like the one PCHex+++ use? It would be extremely helpful

**Comment by Blitzle33** [comment]
I guess  not👻

**Comment by BernardoGiordano** [comment]
I guess you don't even tried the Y button, it's there for a reason.

**Comment by Blitzle33** [comment]
It's say launch client on your PC. Why would I wanna go on my PC when I go get it from my files on my SD Card
