### ISSUE TITLE
4.2.1

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#295]
I dont know how to install this one. I put it on the pksm folder on my 3ds homebrew but it only takes me back to 4.2.0. How can this be fixed?

**Comment by KofiMatson123** [comment]
It wont even come up as downloading assets

**Comment by KofiMatson123** [comment]
I deleted the assets luke before but even using older versions wont work. The redirection of assts have failed is the message i keep getting

**Comment by BernardoGiordano** [comment]
Make sure you delete the old application and copy the new one in the right place

**Comment by BernardoGiordano** [comment]
Clean everything and make sure you actually copy the 4.2.1 release zip.

**Comment by KofiMatson123** [comment]
I cant

**Comment by KofiMatson123** [comment]
Clean everything in the folders?

**Comment by KofiMatson123** [comment]
Ive done that but the assets wont download like normal

**Comment by BernardoGiordano** [comment]
It seems you're still on 4.2.0 maybe?

**Comment by KofiMatson123** [comment]
I deleted it. I downloaded the pksm master zip but dont know what to do with it. The assets from that  folder i copied into the pksm data folder where the assets are stored but still not working

**Comment by BernardoGiordano** [comment]
That is not the release download... You downloaded the source

**Comment by KofiMatson123** [comment]
I know that i did download the release first and entered pksm like normal it would go to 4.2.0 whoch was odd then i deleted thw old relese and assets now it wont let me enter pksm even with 4.2.0 so i thought the assets from that is what i neede but it didnt work either

**Comment by KofiMatson123** [comment]
Its downloading fonts and assets okay. Its done now thank you😁

**Comment by KofiMatson123** [comment]
Btw having the logos as legendaries and game icons is a fantastic addition😁
