### ISSUE TITLE
Red sprites on the version 4.2.0

### ISSUE THREAD

**Issue by Remenabila** [BernardoGiordano/PKSM#299]
Hello. I got some red pokemon sprites inside some of my boxes. All of them are legit.  I sometimes use PKSM only for the natures bit anyway these red sprites were not modified. Someone can help ?

**Comment by BernardoGiordano** [comment]
> We'll not reply to issues related to versions of PKSM different from the latest release currently available.

**Comment by KofiMatson123** [comment]
All you need to do is put them in the bank
