### ISSUE TITLE
Can't choose my cartridge.

### ISSUE THREAD

**Issue by phoen1x74** [BernardoGiordano/PKSM#30]
I'm on an 11.0 homebrew only setup, and when I choose pokemon AS, the game I have in my cart, it still does not detect it. Even when I launch through pokebank, it still does not work.

**Comment by eivanhoe** [comment]
I'm also facing the same issue. I found this comment on reddit by the author.

"11.0 hbonly have a known issue that prevent to load the application correctly. I still have to find a proper solution, sadly"

https://www.reddit.com/r/3dshacks/comments/5dxpw0/pksm_310_full_injector_bank_and_editor_support/da87j8f/

**Comment by BernardoGiordano** [comment]
fixed in one of the latest commits
