### ISSUE TITLE
Liberty Ticket and SPR2012 Zekrom

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#300]
Is it possible for you to create the liberty ticket wondercard for BWB2W2? I would really like to have it please.Also is it possible to add the movie Zekrom along with the movie reshiram please. I think you forgot that Black and Black 2 had separate events from White and White2

**Comment by KofiMatson123** [comment]
Please help me here

**Comment by KofiMatson123** [comment]
CAN YOU PLEASE HELP ME!!!!!

**Comment by KofiMatson123** [comment]
Ive been ewaiting for a response for 5 days

**Comment by Slownic** [comment]
Sorry, but it can't be done, at the moment. Stop spamming so freaking much, ffs.
