### ISSUE TITLE
Pokemon Pearl

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#307]
Whe  i try to ise it it says for pearl that it cant be loaded because snot the right amount of data or something. It works fine with my diamond and platinum

**Comment by BernardoGiordano** [comment]
please report the correct error message

**Comment by KofiMatson123** [comment]
The correct message is "Incorrect size for this game!"

**Comment by KofiMatson123** [comment]
That is the correct message

**Comment by sicdavid** [comment]
How did you get it to work with Pokémon Diamond??

**Comment by KofiMatson123** [comment]
Just ooen pksm using poke transporter or pokemon dream radar. Then choose the 4th or 5th gen game icon

**Comment by sicdavid** [comment]
I've tried that but the PKSM app crashes

**Comment by KofiMatson123** [comment]
Have you installed PKSM properly? Delete pksm off your SD then add it again if it doesnt work then you should ask the creator directly.

**Comment by BernardoGiordano** [comment]
Did you fix the error?

**Comment by KofiMatson123** [comment]
No I didnt I dont know what the message means
