### ISSUE TITLE
TRAINER ID AND SID  sun and moon

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#308]
I would like to make gen 7 event pokemon like from the actual event but I cant get the ID or SID right. I have the ID from the events but since it gen 7 it is 6 numbers instead of the usual 5 so i can only put upto 5 numbers in but I dont now how that will translate into 6 numbers on the actual game. Someone please help me???😣😢😅

**Comment by KofiMatson123** [comment]
Help me please!!!!!!!

**Comment by KofiMatson123** [comment]
PLEASE!!!!!!!!!!

**Comment by KofiMatson123** [comment]
Help

**Comment by MattOlivoto** [comment]
Damn dude, wait for the answer '-'

**Comment by BernardoGiordano** [comment]
Man damn, wait! I'm not a machine who lives coding, I have way more important things to do, please have respect for other people's life

**Comment by KofiMatson123** [comment]
Sorry dude 😅

**Comment by SuperBubbleGumHaZe** [comment]
Hey please help i made some pokemon but even if i change the OT to mine the TID/SID don't match?
