### ISSUE TITLE
Bank changes always saved

### ISSUE THREAD

**Issue by AnalogMan151** [BernardoGiordano/PKSM#31]
If you make any edits to the bank, such as clearing a whole box by mistake or swapping a box to your game, even if you press (X) to exit without saving, your bank changes are still made. One can accidentally wipe an entire bank box this way. 

Please add an apply changes option before exiting the bank screen.

**Comment by BernardoGiordano** [comment]
I'll take this in consideration. Btw, the app makes a bank backup everytime you start a bank session, so when you fuck up something, you can just replace bank with its backup, for now

**Comment by BernardoGiordano** [comment]
added confirmation when erasing a box. This, together with r/w support to SuMo, makes safe working with the bank. closing for now
