### ISSUE TITLE
Issues with Older games

### ISSUE THREAD

**Issue by RiftCreator** [BernardoGiordano/PKSM#310]
I recent started to Homebrew my 3ds and I'm having trouble using PKSM with Homebrew on HeartGold. Read though the usage and similar issues, but the man problem is instead of seeing Poke Transporter as the source to run PKSM for HeartGold I have Swap Note. Help would be appreciated, thank you for your time.

**Comment by BernardoGiordano** [comment]
You have to scroll them with the dpad
