### ISSUE TITLE
Shiny Tapu Koko

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#311]
For the next release could you add the shiny tapu koko event wondecard aswell please

**Comment by Vexslasher** [comment]
For whoever adds the events you can find it [here](https://projectpokemon.org/forums/files/file/1634-melemele-shiny-tapu-koko/) It's a Japanese Event.

**Comment by KofiMatson123** [comment]
Thank you but I need to know the ID and SID of this event so i can use it in PKSM

**Comment by KofiMatson123** [comment]
How can i change pksm to suit the tapus id and SID i only have access to my phone

**Comment by KofiMatson123** [comment]
Thank you
