### ISSUE TITLE
Gen 5 or less

### ISSUE THREAD

**Issue by Zeikin** [BernardoGiordano/PKSM#313]
PKSM can't load or find my gen 4 or 5 games when they are in the console.

**Comment by BernardoGiordano** [comment]
please follow issue reporting guidelines as stated in the readme.

**Comment by 8380716** [comment]
I am having this issue as well. When trying to choose the target app, Pokemon Black 2 will not show up for me.

**Comment by BernardoGiordano** [comment]
Readme states you MUST trigger Poketransfer or Dream Radar to be able to boot DS games. Please READ IT before opening an issue

**Comment by 8380716** [comment]
Just to confirm, I have to download either Poketransfer or Dream Radar from the Nintendo eShop and trigger either one in order to boot DS?

**Comment by BernardoGiordano** [comment]
Yes

**Comment by 8380716** [comment]
Okay cool. My one concern though is that in order to use Dream Radar or Poketransfer, I have to buy them, and if I buy Poketransfer then PKSM kind of becomes pointless since I'm paying for the same service I was trying to get from PKSM in the first place.
