### ISSUE TITLE
Problem with pokedex not updating after injecting living dex

### ISSUE THREAD

**Issue by alex19isfat** [BernardoGiordano/PKSM#315]
This happened on my X and Alpha Sapphire pokemon copies, but worked on my sun copy. I just want the shiny charm, any reason why this is not working?

**Comment by MattOlivoto** [comment]
The pokemons are coming with that octagonal icon right next to where it shows if the pokemon is shiny or not? Cuz I remember that I had the same problem back in the days when I got a hacked 'mon.

**Comment by alex19isfat** [comment]
Yes, they are coming with the correct symbols. All I've done is just injected them in, nothing else.

**Comment by BernardoGiordano** [comment]
XYORAS doesn't have dex updating implemented yet.
