### ISSUE TITLE
Feature Request: Hyper Training

### ISSUE THREAD

**Issue by AnalogMan151** [BernardoGiordano/PKSM#32]
Support for the Hyper-trained modified IVs. Hyper-trained IVs are only used in battle and not when breeding or determining Hidden Power typing. This allows you to have a Pokémon with max IVs in all stats and not be a Dark type Hidden Power.

**Comment by sketchy1** [comment]
Not to be the Noob here, but what is a hyper  trained pokemon? And what gen were they added?

**Comment by rehv** [comment]
> what is a hyper trained pokemon? And what gen were they added?

Read here: [http://www.serebii.net/sunmoon/hypertraining.shtml](url)

They were added in Pokémon Sun/Moon.

**Comment by Morente5** [comment]
That's how PKHeX shows bottle caps used on a stat (green background).
https://archive-media.nyafuu.org/vp/image/1478/85/1478858298641.png

**Comment by dsoldier** [comment]
PKSM will never support the hyper training thingy, sorry.
