### ISSUE TITLE
just a question 

### ISSUE THREAD

**Issue by jmx077** [BernardoGiordano/PKSM#322]
I am trying to use pksm for pokemon white but it is saying wrong file size how do I go about this I looked at the the read me but cant find anything about this.

**Comment by BernardoGiordano** [comment]
How do you boot PKSM?

**Comment by jmx077** [comment]
I go into nintendo 3ds sound and I find it that way I just installed it last night so I don't know any other way

**Comment by BernardoGiordano** [comment]
You must boot PKSM selecting Dream Radar or Poketransporter from the HBL as described in the readme.

**Comment by jmx077** [comment]
sorry I didnt see that in the read me where can I find this?

**Comment by BernardoGiordano** [comment]
check better within the readme
