### ISSUE TITLE
Failed to download assets

### ISSUE THREAD

**Issue by ZeroXortex** [BernardoGiordano/PKSM#323]
Today I'm trying to intal the PKSM but, when I execute it, only download 3 of this assets and the others send the message: "Redirection failed. Failed to download assets".
I tried to download them manually, but stills the same problem. What can I do?

**Comment by BernardoGiordano** [comment]
You're 100% running an outdated version of PKSM.

**Comment by ZeroXortex** [comment]
Where I can download the latest version of PKSM?
Because I download it from this page.

**Comment by ZeroXortex** [comment]
Ok, forget it. I use another files in my computer, when I donwload the file again, it works.
Thanks.
