### ISSUE TITLE
Marshadow?

### ISSUE THREAD

**Issue by skullkeeper94** [BernardoGiordano/PKSM#324]
I know, I know, not an issue within the application itself, but a personal issue never the less.

Ya see, I have no computer, and would really like a Marshadow. 

Is it possible to add Marshadow into the roster of Pokémon that can be generated? 

Or perhaps, there is another reason at he is not included?

Any responses would be appreciated. Thank you ^~^

**Comment by BernardoGiordano** [comment]
It's in the living dex in mass injection.
