### ISSUE TITLE
PKBank Error: Storing a Pokemon erases its Held Trainer Name

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#325]
Whenever I store a Pokemon inside of the PKBank and withdraw it later, the Current Handling trainer is set to nothing. Although this isn't a major issue, it should be the name of the player of the game that its being withdrawn into. This creates errors mainly with how legality handles outsider Pokemon, as those must have that value set.

**Comment by BernardoGiordano** [comment]
can you be more explicit? The element you're storing is caught by you or it's something you're not the OT?

**Comment by PKMWM1** [comment]
Its both. When its my OT, even though it the holding trainer was also set to my name, which is possible by trading it to another game and trading it back or depositing it in Pokemon Bank and withdrawing it, it just erases the value when I store it in PKBank, when I feel that the value should be updated to match the OT Name of whoever withdraws it.

**Comment by GM-Script-Writer-62850** [comment]
I was able to confirm 1/2 of this:
Test case:
Copied crappy pkm i got via wonder trade into the bank (I am NOT the OT)
Copied crappy scizor i got help evolving (I am the OT)
Results:
Crappy pkm from wonder trade shows I amt still the latest (NOT OT) Handler (Correct)
The crappy scizor has NO past handler, this is a problem, a lack of a past trade partner means it could not have evolved (Incorrect)
What should have happened:
When a pokemon is stored in the bank it's last handler is preserved
When said pkm is placed in a save its last handler should be changed to the IGN of that save unless said save is that of the OT

*
