### ISSUE TITLE
DPP, HGSS, BW, BW2 not working 

### ISSUE THREAD

**Issue by SwaggyMudkip69** [BernardoGiordano/PKSM#326]
Im using soundhax on my n3ds and I cant get it to recognize those games please fix if you can and while your here you should add TID/SID edit so the pokemon can look like yours and not have the TID 12345 and SID 54321

**Comment by Naxann** [comment]
DS Games can be edited normally like it is said in the Readme with Dream Radar or Poke Transporter when you launch it with HBL
You can only inject Events Pokémon in Gen IV and Gen V games currently.

As of Dream Radar not working  and displaying a red bottom screen we will look into that.

**Comment by Naxann** [comment]
For TID/SID you can use the icon up to the Edit button when you tap A on a Pokémon in the Pokémon Editor.
It will copy your TID and SID of your Pokémon save in the Pokémon
