### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by sicdavid** [BernardoGiordano/PKSM#327]
When I load up Dream Radar on the PKSM app it crashes. What could be the problem?

**Comment by BernardoGiordano** [comment]
explain the problem better

**Comment by sicdavid** [comment]
My entire 2ds unit freezes whenever I load up Dream Radar on PKSM.

**Comment by Naxann** [comment]
Have you try to use Poké Transporter app instead for DS Games ?

**Comment by sicdavid** [comment]
But wont that mean that I have to buy the poke bank services?

**Comment by Naxann** [comment]
Oh you didn't have it okay.
What is the last color on your bottom screen ? If it is yellow, please update your Hax (SoundHax, OoTHax, ...) and your Homebrew Launcher 3dsx to the last version.

**Comment by sicdavid** [comment]
On the bottom screen the screen turns red.

**Comment by Naxann** [comment]
Yeah it seems that Dream Radar makes the app crash with the new update. We will focus on that after the multi-language support.
Thanks you for the details :)

**Comment by sicdavid** [comment]
Thanks a lot for the help and details! :D
