### ISSUE TITLE
DIY

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#328]
Is it possible for me to add files to my own PKSM to add to my games like wondercards or events using files or whatever? If there is could you pleasr tell me how? Thanks in advance😁

**Comment by BernardoGiordano** [comment]
just put the files in the right place (as it's done officially, by looking to the code) and compile everything by yourself

**Comment by KofiMatson123** [comment]
Hoq do i compile everything by myself
