### ISSUE TITLE
Compile everythjng myself

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#329]
How do I compile everything myself to pksm.  Please give me a link to a website or video for this please if you dont know how to help. Thank you very much.

**Comment by BernardoGiordano** [comment]
download the stuff you need as described in the readme and install them according to each related readme.

**Comment by KofiMatson123** [comment]
But what stuff do I need? Like wondercard files from projectpokemon or serebii?

**Comment by Naxann** [comment]
It is explained in the Readme and it is all the stuff which is needed to compile a Homebrew. 
You can find tutorials on gbatemp in the 3DS Homebrew development section
