### ISSUE TITLE
Digital Version of Sun Not Detected

### ISSUE THREAD

**Issue by Joomla12** [BernardoGiordano/PKSM#33]
I have a copy of Sun from the eShop and PKSM fails to detect it, and closes with an error.

**Comment by BernardoGiordano** [comment]
HBL or cfw?

**Comment by Joomla12** [comment]
Custom firmware. I'm using the latest stable build of Luma.

**Comment by BernardoGiordano** [comment]
Which error do you get?

**Comment by Joomla12** [comment]
"Game not found!" "Press A to continue." Then the app closes.

**Comment by designgears** [comment]
Same thing happening here on CFW.

**Comment by BernardoGiordano** [comment]
Using 3.0.2? It's weird. Unless you have a 'weird' copy with a strange titleID, it has to go well

**Comment by Menoxxx** [comment]
I have the same Problem with 3.1.0.

Pokemon Moon (Freeshop)
Title ID: 0004000000175E00
Media Type: SD
Version: 16
Product Code: CTR-P-BNEA
Region: Region Free
Size: 2,99GB

My System:
O3DS
CakesFW Stable 138
11.2.0-35E

**Comment by Joomla12** [comment]
Updated to the latest release and I still have this issue. Title ID is 0004000000164800.

**Comment by BernardoGiordano** [comment]
Redownload PKSM from TitleDB menu on FBI. It solved this issue to others.

**Comment by pameke** [comment]
hi 

i followed your instruction for titledb.

here is what i have tested
1. retail pokemon y working.
2. sky3ds+ pokemon y working.
3. retail pokemon as not working.
4. sky3ds+ pokemon as not working.
5. digital poemon moon not working.

the error is  game not found !

Im running a9lh luma3ds 11.2.

**Comment by BernardoGiordano** [comment]
Please try to use JK save manager and see if it gives issues, too. JK and me are trying to fix this.

**Comment by Menoxxx** [comment]
I am so sorry it was all my foult.
I didnt select to correct game in start screen.

For all that so stupid like me:
You need to select to right Edition with the D-Pad.
