### ISSUE TITLE
will you be adding more Wondercard

### ISSUE THREAD

**Issue by jmx077** [BernardoGiordano/PKSM#331]
Hello would you be adding more wondercard pokemon for gen 7 and gen 6 and older?

**Comment by BernardoGiordano** [comment]
for example?

**Comment by jmx077** [comment]
umm like if you have time take a look here if you can

**Comment by jmx077** [comment]
http://www.serebii.net/events/

**Comment by Blitzle33** [comment]
So, is that a no?

**Comment by BernardoGiordano** [comment]
you should first say which events are missing, supposed something is missing.

**Comment by jmx077** [comment]
oh I didnt mean it in that way sorry if it sound rude forgive me

**Comment by KofiMatson123** [comment]
Maybe things like Zekrom event and Shiny Hydreigon from generation 5?
