### ISSUE TITLE
Swords of Justice - Wrong Location

### ISSUE THREAD

**Issue by MattOlivoto** [BernardoGiordano/PKSM#332]
Hello,

I'm trying to get the **Swords of Justice**(Keldeo,Cobalion,Terrakion and Virizion) legits on PKSM to play online ( I've tested yesterday on Free Battle - Special pokemons available).
But I was getting that error saying one or more of my pokemons were incorrect, so I've tested every single one of my mons and I saw that the Swords were from a **wrong location** . The game says they came from HOENN (Gen3), when the right information should be from UNOVA(Gen5).
I've trying to edit them from the "bits" corner one by one, but the option "Location" is not available for me to edit, i'm using the 4.2 latest version.
I also uploaded the photo from the event Keldeo, that one seems to have the right info, but I could not use him on free battle as well (I didn't checked if Keldeo is available to play on free battles).

It would be nice if we have the ability to change those location using the bits like I have the ability to change the day they're met and the day the egg was hatched.

If I can add any information to help you understand the problem, just let me know ! 
Amazing job you're doing, keep it up ! 

Screenshots:
![img_20170330_245443317](https://cloud.githubusercontent.com/assets/26417270/24514309/392ca49e-154a-11e7-9f0a-aecc68dfbd5e.jpg)
![img_20170330_245454792](https://cloud.githubusercontent.com/assets/26417270/24514310/392f3d26-154a-11e7-87c8-101ba6489c9f.jpg)
![img_20170330_245502089_hdr](https://cloud.githubusercontent.com/assets/26417270/24514312/395aafce-154a-11e7-8dc9-b70efb48425d.jpg)
![img_20170330_245703944](https://cloud.githubusercontent.com/assets/26417270/24514313/39698968-154a-11e7-8834-83e00024ed75.jpg)

**Comment by KofiMatson123** [comment]
If they have the pentagon that means they came from ORAS (hoenn)

**Comment by KofiMatson123** [comment]
Press the four corners of the bottom screen in hex editor then a pink screen will appear. Using this you can change locations, game tags,

**Comment by MattOlivoto** [comment]
Oh I see. 

What do you mean by four corners ? I should press when after I click "Edit" on the pokemon in PKSM ?

**Comment by PKMWM1** [comment]
When you open a Pokemon to edit its data, there is a small button in the top right corner of the bottom screen that looks like a bunch of digits. Click on that and it will bring you to a screen that is covered in numbers. However, a lot of the digits will be locked. To undo the lock, touch the four corners of hte bottom screen and locate the value you want.

**Comment by BernardoGiordano** [comment]
they're right, instead. They have the pentagon symbol because they were caught in ORAS, not in Unova. Maybe there's something easier to fix for them, like some wrong moveset.

**Comment by BernardoGiordano** [comment]
Checked them, and they are correct in PKSM files. The problem maybe the fact you have a Keldeo with the cross symbol (which means it's gen7 born) when it was only available in <=gen6. You may want to fix that instead.
