### ISSUE TITLE
Could you add this?

### ISSUE THREAD

**Issue by AviatorVence** [BernardoGiordano/PKSM#335]
Hi, i wanted to know if PKSM has the ability to edit pokemon in Gen IV and V games. So far ive only seen wondercards and nothing else. I wanted to know if its possible to create a function (or if it already is in the program and im just a blind idiot please tell me how i can get this to work) to export a savefile to the SD card edit it on a computer and then inject the save file with PKSM.

**Comment by BernardoGiordano** [comment]
it's not possible at the moment.

**Comment by Naxann** [comment]
To export and import DS saves you can use this Homebrew : https://github.com/TuxSH/TWLSaveTool

**Comment by KofiMatson123** [comment]
Thank you Naxann for this because it has helped me make loads of event pokemon from pokegen. THANK YOU SO MUCH!!!!
