### ISSUE TITLE
CLEAN button in Bank

### ISSUE THREAD

**Issue by n2jl** [BernardoGiordano/PKSM#34]
Accidentally pressed the clean button and now all pokemon is gone in box 1, there is no undo as it auto saves.  This is a very dangerous button that is right above the shift button for mass swap. I don't think having a mass delete button is a good idea for a pokemon bank that's meant to save pokemon..
Please remove this button or add a undo just in case its pressed.

**Comment by BernardoGiordano** [comment]
I'll do something to avoid situations like this. I'm sorry you lost your stuff, but if you didn't open your bank after, PKSM has done an automatic backup of the last bank you had. You can find everything in 3ds/data/PKSM/bank/bank.bak

**Comment by BernardoGiordano** [comment]
fixed in the new version
