### ISSUE TITLE
Not generating Pokemons being borned from S/M

### ISSUE THREAD

**Issue by Edug3154** [BernardoGiordano/PKSM#342]
Its a nice work! But like any other work it has its errors. The issue here is it not that when one generates Pokemons,it does not ask for what game do you want it to be born. Of course i know its alot of work but it would be nice if the feature is added onto future updates. Also would be nice if it generated a feature to have their japanesse names.

**Comment by KofiMatson123** [comment]
You can change to japanese names. On the nickname of a pokemon in hex editor you need to put 30 to every second to get japanese chatacter. Example:
D1 30 F5 30 F4 30. The others are for choosing the japanese characters
