### ISSUE TITLE
DS games crash

### ISSUE THREAD

**Issue by Tyulis** [BernardoGiordano/PKSM#344]
To be able to use NDS games on PKSM, I bought Dream Radar, and when I open PKSM with it, the app crashes.

**Comment by BernardoGiordano** [comment]
Try to see of the crash still happens if using TWLSaveTool instead

**Comment by Tyulis** [comment]
TWLSaveTool works.

**Comment by KofiMatson123** [comment]
Maybe try and use poke transporter instead? I use it for nds games and it always works. But when I use Dream Radar it crashes most of the time. So poke transporter is the better option.

**Comment by BernardoGiordano** [comment]
Maybe wait for a fix first, and on the meanwhile edit with PKHeX combined with TWLSaveTool

**Comment by Tyulis** [comment]
Ok. Thanks for help.

**Comment by B2bewild** [comment]
@Bernard 

Hey dude how do I get my ds games to work with pksm ??? Everytime I put the cartridge in it doesn't load or anything . Is there something I need to do for it to work or it's not possible ??? 


Thank-you :)

**Comment by BernardoGiordano** [comment]
How do you start pksm?

**Comment by B2bewild** [comment]
Home brew launcher .

**Comment by B2bewild** [comment]
I use homestretch launcher then soundhax to get it to start

**Comment by B2bewild** [comment]
Homebrew*

**Comment by BernardoGiordano** [comment]
I imagined, but, did you try to read the readme? did you try to trigger Poketransporter before launching PKSM?

**Comment by B2bewild** [comment]
No. I always go to pksm , I haven't gone near poketransporter .

**Comment by BernardoGiordano** [comment]
here is the problem.

**Comment by B2bewild** [comment]
Do I need to activate poke transporter first ??? Before starting pksm ???

**Comment by BernardoGiordano** [comment]
you have to trigger the poketransporter from the homebrew launcher

**Comment by B2bewild** [comment]
Thank-you for the help Bernard
