### ISSUE TITLE
Feature Request: Quickly changing boxes in Pokemon Editor also

### ISSUE THREAD

**Issue by SonicBlader** [BernardoGiordano/PKSM#345]
Hello!

In Extra Storage we can quickly move among the boxes by holding down L or R button. I was wondering if it was possible to implement the same for Pokemon Editor. Although it has just 32 boxes but it will be quite nice to have that!

Also I was wondering if Extra Storage Ad hoc fix PC program was finished. I am referring to [this](https://github.com/BernardoGiordano/PKSM/issues/261)

Thank you for all your work! :)

**Comment by BernardoGiordano** [comment]
I'll try to return back to that but you may imagine that solving ad-personam problem isn't a priority

**Comment by BernardoGiordano** [comment]
for now, you may be able to open your save with PKHeX so it can highlight the bad spots, and overwrite them with PKSM so they're replaced with correct stuff.
