### ISSUE TITLE
PKBank Glitch: Bulk move/swap skips even box slots

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [BernardoGiordano/PKSM#346]
I have 10 boxes of a single species I hatched (I must have PHD Pokemon Hording Disorder) I slapped them in the pkbank, i needed to look though them and i found it easier to scan the in game then in the bank (If Y toggled the non focused screen for view usage that would be better)
So I swapped a couple empty boxes with my stored box and while i was putting them back in the bank 2 of my boxes only moved every other slot (boxes 5/6 in the bank), leaving every even number pkm in the box on the game's box
I found that clearing the empty box in the bank fixed the issue had to do this for both boxes that acted up
i was doing this with moon version

*There was no game migration involve, it has only been used with a single game

Top screen has 30 pkm
Bottom screen has 0 pkm
swap boxes
Save changes
check pkm via moon
bottom screen 30 pkm
top screen empty
swap boxes
only get 1/2 moved

This may only happen if you clear the box on the game then move them out of the bank (before step 1) I also bulk released the low grade breeding rejects at the start, this was about 1.5 boxes worth that were on 2 boxes that i think may have been the boxes i had a issue with

**Comment by SonicBlader** [comment]
Yup I had a pretty similar problem. A fix is available for this one. In the PKSM.zip file, there is a Homebrew app called "badsectors.3dsx" Copy that file to the /3DS folder in your SD card. Open that using Homebrew launcher and your problem should get fixed.

**Comment by GM-Script-Writer-62850** [comment]
Is that bad sectors on the SD card; where some have worn out?

**Comment by BernardoGiordano** [comment]
nope, it only cleans out your bank file
