### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by PKFireNess** [BernardoGiordano/PKSM#349]
Do you think that it would ever be possible to implement a feature to access the storage of the Gen 1 Boxes on Virtual Console? And if that is possible, we could transfer our pokemon over from gen 1 to 7.

**Comment by Naxann** [comment]
Hello ! 
I'm working on a different Homebrew to bring this possible. Currently it would be a lot of work in the current source code of PKSM.

I would post the link of the project when it is on github :)

**Comment by KofiMatson123** [comment]
Could you also make a pksm version for vc RBY?

**Comment by Naxann** [comment]
It will be an Homebrew which allows you to import Pokemon directly into PKSM Bank, and maybe into Sun and Moon if it is not too hard. The second option will be available after the first public release :)

**Comment by KofiMatson123** [comment]
Will there also ever be a feature to edit gen 1 bc games or the nds games like heartgold and platinum just using a homebrew app? Similar to plsm?

**Comment by Naxann** [comment]
First the Homebrew will allow to just transfers Pokémon you want first in PKSM Bank (0.5 release) and then directly in Sun and Moon games, then maybe an editor will come.
Editing Pokemon is not very hard, I have the methods. The most difficult part is implementing fancy graphism.

For Gen5 Pokémon I don't know yet, it is another "format" for Pokémon different from the one from Gen6 / Gen7 and Gen 1, so we need to get all the methods for getting informations, editing it, and all attacks and other things.

**Comment by Naxann** [comment]
If you want to post feature, here is the project page : https://github.com/Naxann/RgbySM

**Comment by KofiMatson123** [comment]
Yeah for gen4 and 4 it could be similar to the one used on the r4 cards PPSE-DS where it let you edit your gen4 games from hombrew on the r4 cards.

**Comment by BernardoGiordano** [comment]
closing as it is not really related to PKSM.
