### ISSUE TITLE
Unable to pickup Gifts

### ISSUE THREAD

**Issue by ClassifiedChaos** [BernardoGiordano/PKSM#35]
After events are injected, I'm unable to pick them up. The events guy does not show! Please help! ><

**Comment by ClassifiedChaos** [comment]
Seems I can not edit pokemon either. Pokemon Moon from eShop, if that helps.

**Comment by KINGBLOODAXE** [comment]
Noriced that too. Then I noticed the in app update function did not update it to 3.1. I was still on 3.0.2 so I did a hard update by removing and the re-installing and that did work. Try doing it that way.

**Comment by BernardoGiordano** [comment]
Make sure you're in 3.1.0 and SAVE your progresses with START on the main menu. Also, the builtin updater downloads only the cia build, not 3dsx one

**Comment by ClassifiedChaos** [comment]
Thank you!
