### ISSUE TITLE
green screen of death

### ISSUE THREAD

**Issue by cothurn** [BernardoGiordano/PKSM#352]
When opening the app with homebrew launcher in 11.4 with doodlebomb, it is stuck in green screen.

**Comment by BernardoGiordano** [comment]
did you have a working setup before updating to 11.4?

**Comment by cothurn** [comment]
Yep, worked perfectly fine

**Comment by HoodieZz** [comment]
11.4 patched pksm, needs update please update

**Comment by lycan2500** [comment]
Yeah. I use Pkhex and had to use JKSM for backing up my data before going on my PC. After update, does not work. Same issue as PKSM there.

**Comment by Naxann** [comment]
The current payload for 11.4 doesn't allow to access saves of games. It will need an update which will maybe come later, like the 11.3

**Comment by BernardoGiordano** [comment]
new payloads have just been released and they fix the issue.
