### ISSUE TITLE
Green Screen on 11.3?

### ISSUE THREAD

**Issue by ZalexZTK** [BernardoGiordano/PKSM#353]
Hello. I downloaded the PKSM application as a 3dsx for use on homebrew. I also downloaded the latest boot.3dsx recently. When I open up PKSM, and insert my Pokemon Sun, I get a green screen. I am on update 11.3, running Luma.

**Comment by Naxann** [comment]
If you are on Luma, use FBI and the CIA version of PKSM, it is way better :)
You are using an older payload for 11.3 in this case. If you are use Homebrew Launcher Loader (the app on the Home menu of the 3DS), hold down the X button to get the new payload.

**Comment by BernardoGiordano** [comment]
new payloads have just been released and they fix the issue.
