### ISSUE TITLE
Pyroar female

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#355]
Can you add the pyroar female sprite on PKSM please. You did it for meowstic. I get confused when going in to my game and having a male pyroar 3d model with the female sign. I do change the form in the hex editor to be female but it would be much easier with the option of having to choose which form you have. Will you also add the option of having mega evolved pokemon on the form changer aswell (as well as Ash greninja  Zygarde complete form)?

**Comment by BernardoGiordano** [comment]
Meowstic did have a different ability relates to its gender, that's why
