### ISSUE TITLE
Hoenn Born

### ISSUE THREAD

**Issue by Blitzle33** [BernardoGiordano/PKSM#357]
I know this might sound like alot but I was wondering if you could change all the Pokemon except the Alola pokemon  to hoenn born. The reason why that is because there are so many good Pokemon moves that they can't learn in Sun&Moon. Like Tutor moves are the best and I'm sad we can't get them in the alola region

**Comment by BernardoGiordano** [comment]
Inject on gen6 games and they will be gen6 born
