### ISSUE TITLE
I can give you my custom Azure Flute wonder card if you like

### ISSUE THREAD

**Issue by MWatson75** [BernardoGiordano/PKSM#362]
I have created my own custom wonder card for the Azure Flute for DPPt. If you like, I can gave you these files to add to PKSM, making all of the event key items available for those games. Big fan by the way, I love using PKSM.

**Comment by MWatson75** [comment]
I also gave the wonder card the same description as the Member Card and Oak's Letter, to make it as legit as possible.

**Comment by KofiMatson123** [comment]
Can i have it also for pkkegen to inject into DPPT?

**Comment by BernardoGiordano** [comment]
upload it then

**Comment by MWatson75** [comment]
https://mega.nz/#!k0tTxKKT!LZS-rIM96aZDYl-4j7YMGAsSoSrosBQMvjQ-1TDvQ6U

**Comment by BernardoGiordano** [comment]
Can you upload it as a .pgt file?

**Comment by KofiMatson123** [comment]
Yeah i think he would but it says it cant be loaded as .pgt file

**Comment by MWatson75** [comment]
https://mega.nz/#!k1lWFCzb!WikdES_EmdMofu8eO5mAaw0bF4Vw68ny8cz1p1hqX6s

I put the pgt in a new zip file with the original pcd
