### ISSUE TITLE
Issue regarding "Failed to receive a status code!"

### ISSUE THREAD

**Issue by JammyTee** [BernardoGiordano/PKSM#365]
I have followed the 'readme' instructions, however it has not changed. It still comes up with both the "Failed to receive a status code!" and followed by "Failed to download assets!"

And this isn't the first time I've done a clean install to try fixing this. I'll put this up, but if I can fix the problem myself before you respond - which hopefully I will. I'll 'close' this issue? Sorry, I made this account specifically to ask for assistance. Only really need it for the bank. Any help would be greatly appreciated!

**Comment by JammyTee** [comment]
Alright! I got it sorted. Sorry for making a useless issue thing since I sorted it myself! I found the mistake, it was completely on my end. I had been putting the additionalassets in the wrong location, after trying over and over I finally had realised I'd looked over it without properly taking note of the exact location for it to be placed.

**Comment by acetrainerred** [comment]
hey would you mind helping me please it would seem i have the same isue as you, would you be abke to take a look at my issue and help me out please
