### ISSUE TITLE
Traditional Chinese Translation

### ISSUE THREAD

**Issue by hirakujira** [BernardoGiordano/PKSM#372]
Just noticed that there's Chinese translation in latest test build. Wondering if it's possible to have Traditional Chinese version? Since it's very easy to translate (Simplified vs Traditional are just different characters, so only need to use some tool like Google Translation to do this automatically), I think it won't add much more task for the translator.

**Comment by BernardoGiordano** [comment]
Problem is finding a translator.

**Comment by hirakujira** [comment]
Ok I can contribute that.

**Comment by BernardoGiordano** [comment]
any news on this? I'll close the issue within 24 hours if there are no news.
