### ISSUE TITLE
GREEN SCREEN IN 11.3!!!!!! WHAT CAN I DO?

### ISSUE THREAD

**Issue by LuckyNeck** [BernardoGiordano/PKSM#375]
ive been trying to save my data from pokemon suun to install pkhex and jksm gets blocked in a green screen. I have acces to homebrew but then i have no acces to jksm. pls could u help me?

**Comment by LuckyNeck** [comment]
could u send me a link of the payload i need or sthg? idk what to do

**Comment by BernardoGiordano** [comment]
#352
#353
#354

**Comment by LuckyNeck** [comment]
I dont understand u
