### ISSUE TITLE
Pokemon Sun - "Game Not Found" Error

### ISSUE THREAD

**Issue by 8380716** [BernardoGiordano/PKSM#376]
I tried the new pre-release, but after loading fonts and selecting Sun, it states "game not found".

**Comment by BernardoGiordano** [comment]
Better if you state how do you launch PKSM and, if on homebrew, you actually have the PKSM.xml file at the right place

**Comment by 8380716** [comment]
Oh! Whoops, yeah you're right! The xml file was in my old PKSM folder but once it was moved, PKSM is now working. Thank you!
