### ISSUE TITLE
Pokemon Generated With PKSM Are Met On "0/0/2000"

### ISSUE THREAD

**Issue by 8380716** [BernardoGiordano/PKSM#377]
As stated in the title, any Pokemon I try to edit to not be hatched from an egg ends up saying I met it on 0/0/2000. I am running the latest testbuild of PKSM.

**Comment by BernardoGiordano** [comment]
You could manually edit the date in the hex editor. Maybe I can implement some automation to the process

**Comment by 8380716** [comment]
Sorry for the late response! Using the hex editor does not work, it seems that it may be actually what is causing the problem. I made sure the "Is Egg" flag was disabled and also that the date for egg hatched was turned all the way down. This unfortunately didn't fix the issue.

**Comment by 8380716** [comment]
I also tried this on the non-testbuild latest release of PKSM and the same result occurs.

**Comment by BernardoGiordano** [comment]
If I understand correctly, you say everything you EDIT is generated on that date or just everything you generate from the internal db?

**Comment by 8380716** [comment]
Yes, everything edited generates to the date. I tried generating from the internal db as well and it seems to happen there occasionally but not every time like when I am just editing.

**Comment by 8380716** [comment]
I checked out any Pokemon that had the 0/0/2000 date using PKHeX to see what it would show as. It states it hatched from an egg, so I changed all the options in PKHex so that it wasn't changed from an egg. But if I go back and try to change anything via PKSM, the date strangely will go back. For example, I had a Pokemon caught within Pokemon Sun legitimately, but after the edits it was hatched from an egg. 

Is there possibly a setting I'm missing in hex editor that enables the Pokemon's summary to be hatched from an egg? I've double and triple checked the "Is Egg" option and all other egg-related settings.

**Comment by 8380716** [comment]
Okay here's an update. I think I've figured out what is going on... unfortunately I don't think there's a way to fix it on my end. 

Basically, any pokemon generated from the internal db is hatched from an egg, regardless if I set the date all the way to zero in the hex editor. I think the problem is that I am unable to  change the "egg location" hex editor because it is grayed out. If that can be edited so it can go to zero, the Pokemon would no longer say the were hatched from an egg on 0/0/2000. Is there a way I can enable that setting in the hex editor or is that feature not available?

**Comment by MattOlivoto** [comment]
Enter hex editor, hit with your stilus the four counters on the bottom screen. The screen will turn pink and you'll be able to edit that stuff.

**Comment by 8380716** [comment]
Thank you, I appreciate the help!

**Comment by MasterKibosh** [comment]
Can you change the Met Date for pokemon on PKSM, if so how?

**Comment by BernardoGiordano** [comment]
Settings menu has an option to input a default date, otherwise change it with the hex editor

**Comment by MasterKibosh** [comment]
A small issue with hex...It doesn't take into account pokemon learn from move tutors

**Comment by HatsuBe** [comment]
@MattOlivoto "Enter hex editor, hit with your stilus the four counters on the bottom screen. The screen will turn pink and you'll be able to edit that stuff."

I can not do it
Help please
