### ISSUE TITLE
Digital Version of Sun not detected

### ISSUE THREAD

**Issue by PurpleYeezy** [BernardoGiordano/PKSM#378]
Hi,

i downloaded my eShop version from Sun and PKSM failed to detect it.

**Comment by MattOlivoto** [comment]
You should bring information like N3ds version, pksm version, error message, stuff like that can help people that maybe had the same problem and can help you out : )

**Comment by PurpleYeezy** [comment]
I have a O3ds, PKSM version 4.2.2 and the error message is "Game not found!"

**Comment by BernardoGiordano** [comment]
I bet you have homebrew launcher, and you didn't install correctly PKSM, so you're missing the PKSM.xml file alongside the 3dsx file.

**Comment by PurpleYeezy** [comment]
I have Cfw with Luma3DS 7.0.4

**Comment by BernardoGiordano** [comment]
Pretty weird. Can you show me in a video?

**Comment by PurpleYeezy** [comment]
What i should be show in the Video?

PS: Sorry for my bad english

**Comment by PurpleYeezy** [comment]
Ok i fixed by my self.

I have now the Testbuild from PKSM and it's works.
