### ISSUE TITLE
Crash after flag saving

### ISSUE THREAD

**Issue by vicriclopur** [BernardoGiordano/PKSM#379]
After transferring from ORAS to Moon, it asks me if i want to save bank, there's no problem, then it asks me  to save flags then, it starts to save the flags but in the 32 box it freezes and resets, when I check back the pokemon transferred isn't there, the error erased the transferred pokemon. 

O3DS 
Latest vercion of PKSM Installed via Qr code with FBI 
pls help :(

**Comment by BernardoGiordano** [comment]
This problem is known and fixed, you should wait for a new release
