### ISSUE TITLE
Hex Editing For Pokemon Locations (Egg and Met Locations)

### ISSUE THREAD

**Issue by 8380716** [BernardoGiordano/PKSM#381]
Hi,

I was wondering if you guys had the values for each location (for where you caught or hatched a Pokemon) in the Hex Editor. It doesn't say which location is which when I change the value. If you guys don't, do you want me to just mess around with it for a while and report back which values went with each location? I'd be pleased to help, although it may take some time.

**Comment by KofiMatson123** [comment]
Go on Bulbapedia they have the locations for all the games there

**Comment by 8380716** [comment]
Thank you

**Comment by kmigueis1** [comment]
How do you use the Hex editor to change ribbons?
