### ISSUE TITLE
Crashes when saving flags 

### ISSUE THREAD

**Issue by MikazukiR** [BernardoGiordano/PKSM#383]
First things first, great work guys. Had no issues. I upddated to testbuild and may have found an issue. Using the extra storage. After moving some mons up into the "bank", it asks to save bin? Then asks if I wanna save flags? If you pick yes it runs through but when it gets to Box 32 Slot 27 the app freezes then force closes itself. Not sure what's happening, but thought I should make you aware. Great work guys! Keep it up! Looking forward to next build!

**Comment by BernardoGiordano** [comment]
This is already fixed

**Comment by MikazukiR** [comment]
Awesome as stated before looking forward to next release
