### ISSUE TITLE
Doesn't recognize my OR .cia.

### ISSUE THREAD

**Issue by Nemx97** [BernardoGiordano/PKSM#385]
Hi. I just installed the newest PKSM version. It works flawless with my Pokémon X catridge but it doesn't recognize my OR .cia. Instead it shows me that I can pick Nintendo Letter Box (unless when I have my X cartridge inserted) as a game which I can boot through. I boot PKSM through Homebrew Launcher. Any help?

**Comment by BernardoGiordano** [comment]
You only need to press your dpad button to see the other games
