### ISSUE TITLE
Plz help it wont work

### ISSUE THREAD

**Issue by Mudkip0214** [BernardoGiordano/PKSM#388]
When I try to use it for my pokemon moonn it says " game not found" and my game is in the 3ds

**Comment by Mudkip0214** [comment]
I've tried everything and I just want to use pksm I am using homebrew soo  hope that helps

**Comment by Mudkip0214** [comment]
I am using the homebrew one so hope that helps

**Comment by BernardoGiordano** [comment]
It seems you're missing xml file alongside the 3dsx. Go install pksm correctly.

**Comment by Mudkip0214** [comment]
I have the XML file
