### ISSUE TITLE
Wifi Problem

### ISSUE THREAD

**Issue by Nanogold11** [BernardoGiordano/PKSM#390]
ciao bernardo, grazie per il tuo programma e per averlo reso pubblico.
Vorrei esporti un problema ovvero il mal funzionamento del wifi, ho scaricato il servepkhex ed in seguito ho provato anche sul tuo sito ma anche con quello non ricevo i pokemon.
Ho controllato tutto anche l'indirizzo del server ma i pokemon non mi arrivano spero tu possa aiutarmi
Ps: scrivo in italiano perchè presumo dal nome tu lo sia

**Comment by BernardoGiordano** [comment]
mostra in qualche modo come usi servepkx perché l'errore potrebbe avere diverse cause
