### ISSUE TITLE
Suggestion: An alternative of using the shoulder buttons (L and R buttons)

### ISSUE THREAD

**Issue by TMGC1234** [BernardoGiordano/PKSM#391]
My Old 3DS's shoulder buttons are broken and because of that I can't switch between the extra boxes. I know that there are ways to fix the shoulder buttons but my 3ds is not effective on that method. If it isn't a bother to you, can you at least make the L and R UI buttons selectable for the cursor.

**Comment by BernardoGiordano** [comment]
you could compile your custom version with the button map changed, simply.
