### ISSUE TITLE
Request : Edit Byte for "Species #" on god-mod (After tapping the four corner)

### ISSUE THREAD

**Issue by Alistouze** [BernardoGiordano/PKSM#392]
Hello BernardoGiordano, thanks for your hard work!
I dont know why but you dont let us edit the "Version/Country/Région/ConsoleRegion/Language" of a pokémon.
And if I want to create a 100% legit one, i really need yo set all of this  byte the same like mine real pokémon, but we can't édit them.

It's been à long Time waiting for this obviouse feature, dont know why still not able at this Time (4.2.2), so i register here to tell you that lol

Pls can you add this possibilty on exa-editor ? Thanks à lot !! :-)
This is all pksm miss to be perfect for the creation of real legit pokémon ;-)

**Comment by Alistouze** [comment]
Better idea : 
Just let us edit "species id" byte, that way we can hatch à real pokémon egg (with all real data byte with it) from our game, then change only the species in pksm (to save all other "legit data byte" came from the real egg just before).
Like this, the generated species will everytime be full legit ! (Except for some eggmove/event pokémon ofc)

**Comment by Gudf** [comment]
You can edit Version/Country/Région/ConsoleRegion/Language by tapping the four corners on the bottom screen in the right order while you are on the hex-editor, but I don't think you can edit the species id byte.

**Comment by Alistouze** [comment]
Hello, thanks for your answer !
Thanks à lot for this tips  to access god-mod ! :-D

But yeah, we can't edit species byte 1&2 :-(
Do you think it will be able in fews next patch ? :-)

**Comment by Alistouze** [comment]
UP ? :-)

**Comment by BernardoGiordano** [comment]
it will not be available in any moment, because of legality issues it will cause.

**Comment by Alistouze** [comment]
Why closes ? :-(

**Comment by Alistouze** [comment]
Hum i dont know what legality issues it will cause.

It's exactly the same thinks of copying all databyte from another egg-pokemon into another, but more faster if I just copy that egg-pokemon entierely and just change the species idbyte.
