### ISSUE TITLE
Can't Use PKSM for Pokemon Black, Y, or Sun

### ISSUE THREAD

**Issue by Picahaxer** [BernardoGiordano/PKSM#393]
I've tried all three games, and two said "game not recognized" (sun and Y) and the other said "Incorrect Size for this game!"(black) I've put the cartridges in, idk what's wrong.

**Comment by BernardoGiordano** [comment]
Fully read the readme.

**Comment by Picahaxer** [comment]
read what part? I've read most of it and none of what I've read contains useful info for me right now.

**Comment by BernardoGiordano** [comment]
You're using the homebrew launcher, I imagine.

**Comment by Picahaxer** [comment]
yep

**Comment by Picahaxer** [comment]
I read where exactly to put the files. I think I figured it out. update- I did.
