### ISSUE TITLE
Language Change

### ISSUE THREAD

**Issue by semina-augum** [BernardoGiordano/PKSM#395]
Will changing a pokemon's language be available at any point? Since I can't type full-width text in PKSM (because it uses the default 3ds keyboard) and my Sun's in Chinese (which uses full-width English letters), the OT name will affect the genned mon's legality. I can't really gen legal mons with PKSM due to this.
Or, is there a way to type Japanese/full-width characters with homebrew that I supposedly just didn't know? 
(Thanks for everything! This is a really handy program so far.)

**Comment by KofiMatson123** [comment]
You can change a pokemons language in hex editor

**Comment by BernardoGiordano** [comment]
obviously you can do it in the hex editor.

**Comment by semina-augum** [comment]
I checked that, but you can't change it (the two numbers are a dark color and pressing A/X does nothing)
