### ISSUE TITLE
Pokemon Dream Radar

### ISSUE THREAD

**Issue by mp1121** [BernardoGiordano/PKSM#396]
I downloaded Pokemon Dream Radar so I could access my ds games, but everytime I boot it up, it freezes on a red screen. And I can't download pokemon bank because I need a Nintendo Network Id and in order to do that I need to update my system, which I cant do because I use the the sound recording app for homebrew. Is there a previous version of pksm I can download or some solution I am not seeing? Thanks in advance for the help

**Comment by KofiMatson123** [comment]
In your homebrew if you have the option of ctr-httpwn as one of your 'apps' press it and if youre connected to the internet. Once it says 'succesful' press start to go back to homebrew and press x and x again to reboot into the home menu. Now it will allow you to bypass all system updates meaning you can use the e-shop and get a NNID to buy pokebank. But it wears off if you turn the system off. Do the process again to be able to enter e-shop and online conectivity with games. HOPE I HELPED!

**Comment by BernardoGiordano** [comment]
Closing since it's #344 duplicate
