### ISSUE TITLE
Pokemon deleted, Help! 

### ISSUE THREAD

**Issue by icyigor** [BernardoGiordano/PKSM#397]
Hello, i was using PKSM to transfer my pokemon from omega ruby to moon, i quit the extrastorage and left PKSM but forgot to save! When i check back all the pokemon that I transfered are gone! There not in the game, there not in the extra storage, I even check my omega ruby and there not there, is there anyway to recover them? Like data mining or going into the files. Thanks!

**Comment by Gudf** [comment]
You should have a backup of your save in /3ds/data/PKSM/backup/[GAME_DATE]/main (as explained in the README.md).

**Comment by icyigor** [comment]
Yes im on the "main" section, im givin the option to rename, delete, copy and paste, how do i export the backup (Im a big nub XD)

**Comment by BernardoGiordano** [comment]
Try recovering a backup, you can load some with JKSM.

**Comment by icyigor** [comment]
I dont have jksm and i cant download it atm. Is there anything else i can do

**Comment by FahriBilici** [comment]
İ have same issue can u explain more

**Comment by piepie62** [comment]
Do not ask for help on an issue from two years ago, thanks
