### ISSUE TITLE
Please help me...anyone..

### ISSUE THREAD

**Issue by acetrainerred** [BernardoGiordano/PKSM#398]
when i try to start pksm it doesnt work. i launch up homebrew on my old 3ds then run pksn and says loading fronts 1-7 and then says failed to receive a status code. i press A and then it says it failed to download assets 
i load my sd card into my computer and then go to 3ds/data/pksm/additonalassets 
and what i have in the additional assests forlder is  i18n
and then in that flder i have folders like de en es fr it jp kn ln pt ru zh

it looks lie i have all the additonalassets so what can be the problem please someone help me

**Comment by BernardoGiordano** [comment]
you don't have all the additional assets, the program would have booted otherwise. State your PKSM version and do proper screenshots of your sd card structure. I can't see how can *anyone* help you

**Comment by acetrainerred** [comment]
thank you very much for replying
okay the pksm version i have is pksm.3dsx which i downloaded today.
here are the picture of how my sd card looks
![img_1870](https://cloud.githubusercontent.com/assets/29166850/26756681/2795cc60-485d-11e7-88de-9002a5ccd7ab.JPG)
![img_1871](https://cloud.githubusercontent.com/assets/29166850/26756684/2aefe7a6-485d-11e7-9833-4e10510b038b.JPG)
![img_1872](https://cloud.githubusercontent.com/assets/29166850/26756686/2f72b5f6-485d-11e7-9e36-2aad65b1e055.JPG)
![img_1873](https://cloud.githubusercontent.com/assets/29166850/26756687/3158cb58-485d-11e7-81f2-a78a69664e44.JPG)
![img_1874](https://cloud.githubusercontent.com/assets/29166850/26756688/359509ca-485d-11e7-8a8e-b45aed231a19.JPG)
![img_1875](https://cloud.githubusercontent.com/assets/29166850/26756690/3760ddb0-485d-11e7-8322-97610965160c.JPG)

**Comment by BernardoGiordano** [comment]
what do you have in the en folder in the last picture?

**Comment by acetrainerred** [comment]
i just checked and its empty

**Comment by BernardoGiordano** [comment]
Are you sure your internet connection works correctly? Mainly if you're using an outdated firmware version, you should use ctr-httpwn to get internet connection work correctly

**Comment by acetrainerred** [comment]
Alrighty then thank you very much for your help really appreciate it
