### ISSUE TITLE
Jksm not loading pksm backup

### ISSUE THREAD

**Issue by icyigor** [BernardoGiordano/PKSM#399]
Hello, im trying to recover some of my lost pokemon with jksm, i press import save, and it says error: could not load save archive, any way to fix this?(I didn't know whether to put this on jksm issues or pksm issues so i put it on both xD)

**Comment by BernardoGiordano** [comment]
You probably didn't choose the right folder

**Comment by icyigor** [comment]
Sorry what do you mean, i just clicked PKSM and clicked import backup, i didint get to choose a folder.

**Comment by BernardoGiordano** [comment]
It's not that easy. You have to point to the folder relative to the 'main' file you want to restore

**Comment by icyigor** [comment]
Ima nub xD do u have any files that explain that xD

**Comment by Gudf** [comment]
Are you using cia or 3dsx version on JKSM ? 
With the 3dsx version, you have to create a folder named Pokémon_Omega_Ruby (with é, not e) in /JKSV/Saves/ and put the folder with your backup in this folder. 
With the cia, select "browse SD for data", then go to /3ds/data/PKSM/backup and click on Y on the folder with your backup (Should be OR_[date]).

**Comment by icyigor** [comment]
Wait i dont have the browse sd for data, i only have cartridge, sd/cia, system titles, shared extdata, refresh games, download filter, extras and exit, i downloaded the jksm via qr code with fbi so i think that makes it cia version, so help please xD

**Comment by Gudf** [comment]
You must select your game first

**Comment by icyigor** [comment]
How do i select a game?

**Comment by Gudf** [comment]
Cartrige if you're using a cartridge, SD/CIA if using an Eshop version.

**Comment by icyigor** [comment]
I already selected the game, Its PKSM, i click import save and it says error:could not load save archive

**Comment by Gudf** [comment]
No. The game is Pokémon Omega Ruby, since you're trying to recover a save of Omega Ruby where you still have your pokémons.

**Comment by icyigor** [comment]
No i put pokemon into extra storage to transfer form omega ruby to moon, when i put them in the bank, i quit and forgot to save, when i check back, there gone, i see the game automatically saved so im trying to get the backup onto my pksm with jksm but like i said its not working (and thanks for all the help so far)

**Comment by Gudf** [comment]
No. The backup is a backup or an OR save before putting your pokémons in the bank. So you have to get the backup on your OR game and transfer the pokémons again.

**Comment by icyigor** [comment]
Yes but how do i access the backup, like how do i enter it and get my pokemon back

**Comment by Gudf** [comment]
You restore your backup to your OR game, and your pokémons should be back in your game. After doing this, you can use PKSM to transfer them again.

**Comment by icyigor** [comment]
How do i restore the backup tho xD

**Comment by Gudf** [comment]
With JKSM

**Comment by icyigor** [comment]
How tho, i go to sd/cia, then i click on pksm, then import save and it says error: could not open save archive

**Comment by Gudf** [comment]
Not PKSM, Omega Ruby, then Browse SD for data, then go to /3ds/data/PKSM/backup and Y on the folder with your backup (OR_[date])

**Comment by icyigor** [comment]
Omg dude it worked!! I got all my pokemon back and transfered them to moon!! I never would have done it without your help, this was a very long conversation because im a nub who doesent know what he is doing but with your help it worked, Thanks sooo much :D
