### ISSUE TITLE
Feature Request: configurable default TID/SID & Default Hex Values

### ISSUE THREAD

**Issue by Majiya** [BernardoGiordano/PKSM#401]
Would it be possible for an option to be added that allows for us to configure the TID/SID which is assigned to genned Pokemon automatically instead of the default PKSM values of 12345/54321? And potentially to also configure default hex values?
This would be very useful if users wanted to gen many foreign Pokemon, or Pokemon to match another save file etc.

(Thought I'd update/shorten this post since the first issue has since been fixed.)

Thank you!

**Comment by BernardoGiordano** [comment]
fixed in https://github.com/BernardoGiordano/PKSM/commit/dc346915f7213f2ba95f901d70b4fa094725fab7
