### ISSUE TITLE
Pokemon generated to match trainer details are illegal

### ISSUE THREAD

**Issue by Majiya** [BernardoGiordano/PKSM#402]
This one is hard for me to explain, so please ask if you need anything elaborated.
Here is an example save with all its Pokemon generated in PKSM:

https://www.dropbox.com/s/bszpcp1kpmjvrzk/main?dl=0

They are all illegal for being untraded despite it not being a requirement.
Originally, I thought the illegal flagging was a PKHeX error, but after raising an issue I was told that the reason they are failing the check is because they have been created with an empty current handler (the current handler is highlighted green in PKHeX, which shows it is not the OT for these Pokemon). This means that they should have been traded as the latest handler was not the OT, but because the 'Latest Handler' box is empty, they can't have been, and are therefore illegal.

Here is what is causing the issue (information provided by the creator of PKHeX):
> In the provided data, `[0x93 == 1]` sets the current handler to 1, being the Handling Trainer (not OT). 

When genning Pokemon intended to match the game's trainer details (using the button to import TID/SID), PKSM should ensure that the current handler is always set to the OT `[0x93 == 0]` and not the 'Latest Handler' to avoid legality fails.
The 'Held Trainer Friendship' `0xA2` should also be set to 0 for legality, since this is separate to OT friendship. Setting this at 0 will also mean genned Pokemon are more likely to be legal, as handling trainer affection can be increased through the game if there is a different handler.

~~Another way to fix this would be to allow editing of the current handler in PKSM, as right now it's greyed out.~~ If the current handler is set to the OT (0 instead of 1), and held trainer friendship set to 0 by default, Pokemon would always be legal (assuming everything else is correct) as these stats would be updated automatically when the game is launched should the handling trainer differ from the OT.

Thank you

**Comment by Gudf** [comment]
You can edit this via god-mode (accessed by tapping the four corners on the bottom screen while you are on the hex editor).

**Comment by Majiya** [comment]
That's what I meant by greyed out- I can see that current handler is set to 1 on x93 but it doesn't allow editing, I've tried pressing every button.

Is there any way to enable it?
