### ISSUE TITLE
PKSM crash following Pokédex entries save

### ISSUE THREAD

**Issue by Rei366** [BernardoGiordano/PKSM#404]
Hello, I want to notify you about the fact PKSM always crashes while saving modifications (on the exit) if I accepted a pokédex entries save upon leaving the bank during the PKSM session.

Game: Pokémon Moon (E), game card.
Update: 1.2
Console: new3DS XL (E).
Firmware: current one.

**Comment by BernardoGiordano** [comment]
This is known and has been fixed, too
