### ISSUE TITLE
HB Menu v2 Compatibility

### ISSUE THREAD

**Issue by Phalk** [BernardoGiordano/PKSM#405]
As it stands, the 3DSX PKSM version isn't compatible with the new Home Brew Menu v2 and Luma3DS V8 because the targeted app function is deprecated.

**Comment by BernardoGiordano** [comment]
I know it's a serious problem and I don't want to be rude, but why Luma3DS users would complain about this if they can install the cfw version of PKSM?

**Comment by Phalk** [comment]
Don't worry, I don't think you're being rude.
My personal reason for that is that I want to keep my system clean of any homebrew titles on it's home menu to help with a possible new wave of bans in the future since as far as information about the last ban wave points to the culprits being information about homebrew titles installed on the system.

The new Homebrew Menu can run hooked into any application or game leaving no trace of it's exectution anywhere.

**Comment by marcomarotta** [comment]
@BernardoGiordano mi associo con l'utente sopra. Ormai con la paranoia di essere bannati la maggior parte degli utenti "advanced" sta passando dai .cia ai .3dsx, incluso me. Non chiedo ETA ma solo di tenere in considerazione di rendere la tua utilissima applicazione compatibile con il nuovo homebrew launcher. Grazie per il lavoro eccelso e per averci fornito una validissima alternativa alla banca.

**Comment by BernardoGiordano** [comment]
Fixed starting from the latest 4.2.4_TESTBUILD
