### ISSUE TITLE
Feature Request: Option to 'Move' pokemon in editor - or touch screen drag+dropping in editor

### ISSUE THREAD

**Issue by Majiya** [BernardoGiordano/PKSM#407]
I know we can clone the pokemon and delete the existing pokemon, but a move option would make the process far more efficient, especially when moving pokemon between boxes whilst editing. Additionally, the ability to drag and drop pokemon around boxes using the touch screen would be very convenient.

Although not a big issue, I think it would make for a useful feature, especially since pokemon can already be moved around in the bank viewer.

Thank you!

**Comment by BernardoGiordano** [comment]
we prefer to leave the 'move' option in the extra storage feature only.
