### ISSUE TITLE
Getting pksm 

### ISSUE THREAD

**Issue by trainerashketchum** [BernardoGiordano/PKSM#408]
Just had a quick question
I just got a new 3ds xl and want to install pksm 
My system is in 11.4
Am I able to get homebrew to work by using soundhax? 
Will sound hax work with my new 3ds 11.4
Thank you very much for the response

**Comment by Gudf** [comment]
No

**Comment by trainerashketchum** [comment]
Okay thanks for the reply, but there is other ways of accessing homebrew right 
How would you suggest the best way would be

**Comment by Gudf** [comment]
On N3DS, the only way to access HBL on 11.4 is using ninjhax. (But Github is NOT a support forum, for question like this, don't come here.)

**Comment by trainerashketchum** [comment]
Thanks
