### ISSUE TITLE
Problem with the Pikachu-Ash event

### ISSUE THREAD

**Issue by daniel95000** [BernardoGiordano/PKSM#413]
There is a problem with the Pikachu-Ash event . 

Test the new PKSM update and try to add the wonder card 0223 (Five different Ash-hat Pikachu) and it did not work and gave me error. I do not understand why :c

**Comment by lbc493** [comment]
Same here, "error injecting". I'm using cia version.

**Comment by CodyMKW** [comment]
isn't that pikachu just for ultra sun and ultra moon?

**Comment by daniel95000** [comment]
That pikachu is the event for "Sun/Moon" not for "Ultra Sun/Ultra Moon"

As you can see on this page:

https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_region_serial_code_event_Pok%C3%A9mon_distributions_in_Generation_VII#Ash.27s_Pikachu

It is the current Japanese event for "Sun/Moon"

The Ash Pikachu event for "Ultra Sun/ Ultra Moon" will be released on the day the games are played

**Comment by CodyMKW** [comment]
oh I see

**Comment by 8380716** [comment]
I am experiencing this exact problem on the cia version of PKSM while trying to inject to a digital copy of Moon.

**Comment by BernardoGiordano** [comment]
It seems that something messed up while compilation, in the assets. It'a not a big issue though, in fact I don't experience the problem in the latest "stable" build I'm preparing to release very soon. I can release a fix for that testbuild but it's possible I'll release a stable directly

**Comment by lbc493** [comment]
How can I inject the other the other pikachu hats? I can inject only Kanto hat.

**Comment by BernardoGiordano** [comment]
fixed
