### ISSUE TITLE
I have a question...

### ISSUE THREAD

**Issue by daniel95000** [BernardoGiordano/PKSM#414]
1) Can I change the location of where I got a Pokemon? That is to say that if I capture a pokemon in Route 1 I can put it that I got it in Route 2

2) Can it be changed if the Pokémon comes from old generations, kalos, virtual console (GB) or Alola? (Symbols)

If so ... could you tell me how to do it: c?

Note: I really speak Spanish, that's why my English is bad and I use a translator

**Comment by BernardoGiordano** [comment]
you can do it by using the built-in hex editor.
