### ISSUE TITLE
PokeDex flags crash.

### ISSUE THREAD

**Issue by TachiGaroth** [BernardoGiordano/PKSM#416]
After transferring my Pokemon from omega Ruby to sun and accepting the PokeDex flag option, it crashed at box 32 / slot 27 even if I didn't had a Pokemon in that slot.

After trying a couple of times with and without transfering Pokemon to sun it still crashed at the same spot.
Any reason or fix for this?

Transfer without the PokeDex option works fine.

**Comment by diglett88** [comment]
Same here on 4.2.3 test build. Pokedex flag option works fine on Moon with 4.2.2 though

**Comment by Gudf** [comment]
It's a known bug, wait for the next non-beta release.

**Comment by BernardoGiordano** [comment]
known and fixed.
