### ISSUE TITLE
Rosalina HBL-compatible version of PKSM.3dsx does not recognize digital games

### ISSUE THREAD

**Issue by 8380716** [BernardoGiordano/PKSM#417]
Hi! I'm having a bit of trouble with the Rosalina version of PKSM. I thought I forgot the XML file but even with it there, it states "Game Not Found".

**Comment by Naxann** [comment]
Could you tell me which game are you using ?
And if you are using Rosalina, are you on Luma 8.0 ? Rosalina version is just for Luma 8.0 users with Rosalina entry point. 
If you are using an hax, like doodlejump, OoTHax, etc... just use the hax version with the .xml file.

**Comment by 8380716** [comment]
I have tried using Moon, Alpha Sapphire, and Y. They are all digital versions. I just realized I'm running Luma 7.1, so maybe I just need to update.

**Comment by Naxann** [comment]
Rosalina don't exist in 7.1, you have to use the classic .3dsx and .xml file

**Comment by 8380716** [comment]
Oh! I guess I confused myself. Thank you for the help.
