### ISSUE TITLE
Switch Games After Already Picking One

### ISSUE THREAD

**Issue by nwhiteman42** [BernardoGiordano/PKSM#42]
There is no current way to switch between multiple games without closing the application.  I believe this would be a good feature to include.  Maybe be able to do it by pressing b to go back but have it make you decide between not saving and saving as if you are exiting the program.  Good Work So Far

**Comment by BernardoGiordano** [comment]
This is not possible due to various memory allocations that have to be done at application startup. Adding such feature would not repay the work to make it, so I think it's not so bad having to close it before choosing a new game
