### ISSUE TITLE
pksm failed to receive a status code

### ISSUE THREAD

**Issue by supersonic49** [BernardoGiordano/PKSM#424]
can you help me fix this problem please

failed to receive a status code

show me step by step please on how to make it work and what to do 

i really need your help 

because every time i open pksm it always shows this message failed to receive a status code

my nintendo is version 11.2

and i have homebrew already installed

**Comment by BernardoGiordano** [comment]
check the readme, in the installation section, you're missing the additionalassets. your 3ds can't access to the internet connection.

**Comment by supersonic49** [comment]
where do you put the additionalassets

**Comment by BernardoGiordano** [comment]
it's written in the readme. go read it

**Comment by supersonic49** [comment]
i have but it does not say it well and i do not understand it.

can you please tell me where to put the additionalassets please

i really need it

**Comment by BernardoGiordano** [comment]
extract the additionalassets zip. put it in `/3ds/data/PKSM/` . the final result should be a folder filled with assets, located at `/3ds/data/PKSM/additionalassets/`

**Comment by supersonic49** [comment]
can you upload a video as an example so i know what to do

sorry but i am not very good at this thing

thank you

**Comment by BernardoGiordano** [comment]
I can't. ask here https://discord.gg/bGKEyfY

**Comment by supersonic49** [comment]
so if i did the process you showed me

/3ds/data/PKSM/additionalassets/

so pksm should work now if i did this

**Comment by supersonic49** [comment]
and if i used homebrew it should work???

**Comment by supersonic49** [comment]
hey man

the process you showed me does it work on the homebrew launcher

**Comment by BernardoGiordano** [comment]
it does

**Comment by supersonic49** [comment]
ok thanks for that then

On Tue, Jun 27, 2017 at 1:38 PM, Bernardo Giordano <notifications@github.com

**Comment by supersonic49** [comment]
hey

is there anything else that needs to go to the pksm save folder to make it
work???

**Comment by supersonic49** [comment]
and by the way

what is the difference between pksv and pksm

which one is better
