### ISSUE TITLE
Doesn't support inject Mystery Gift's wc7 file.

### ISSUE THREAD

**Issue by TaChao** [BernardoGiordano/PKSM#428]
such as this file

[0223 SM - サトシ Pikachu (Unova Cap) & Pikashunium Z (JPN).zip](https://github.com/BernardoGiordano/PKSM/files/1114066/0223.SM.-.Pikachu.Unova.Cap.Pikashunium.Z.JPN.zip)

**Comment by BernardoGiordano** [comment]
I'm not sure what the issue is

**Comment by TaChao** [comment]
this files is a mystery gift file , use OTA injection will make a black hole in box and make game crash

**Comment by BernardoGiordano** [comment]
1) this is a wc7full, not a wc7
2) you can't inject mystery gifts into the box directly.

**Comment by TaChao** [comment]
thanks
