### ISSUE TITLE
issue loading save with .3dsx version

### ISSUE THREAD

**Issue by zweilous** [BernardoGiordano/PKSM#429]
i'm using luma v8.1 and hb menu v2 to use the .3dsx version of pksm and pksv. when loading a save from an alpha sapphire cart, it says "incorrect size for this game" and loads the data incorrectly. i also tried a digital version of sun and it loaded nothing

**Comment by Gudf** [comment]
Are you using the Rosalina version ?

**Comment by zweilous** [comment]
ah i just tried to place the files manually and it's fine. fsr it didnt pull the proper 3dsx file when i tried to do an automated update. please disregard
