### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Eriun** [BernardoGiordano/PKSM#431]
I have done the extraction and all. Got the otherapp and soundhax and when i try to open it via Nintendo 3DS sound it's giving me an error "Could Not Play"

Am i missing something?

**Comment by Eriun** [comment]
Btw, my 3ds is at 11.4.0.37U

**Comment by BernardoGiordano** [comment]
soundhax doesn't work on 11.4

**Comment by Eriun** [comment]
What should be thw workaround then so i can have it working?
