### ISSUE TITLE
Adding boxes to pksm bank

### ISSUE THREAD

**Issue by Nooblordzzz** [BernardoGiordano/PKSM#434]
hi I just want to ask how to add additional boxes to the pksm. Every time I add boxes it doesn't seem to work,

**Comment by BernardoGiordano** [comment]
Tap on the number, too. It's written

**Comment by Nooblordzzz** [comment]
i tapped it but when i go back it's still 150

**Comment by sxp5702** [comment]
Ack, muh heart >_< any way to enable it or is there something wrong with it?  Like it conflicts or creates bugs?

**Comment by bubby2** [comment]
I am also interested in if you could enable storage resizing again. I currently am having storage issues and would appreciate if you could add a few (tons) more boxes
Thanks, it would be great
