### ISSUE TITLE
Just suggestions

### ISSUE THREAD

**Issue by B2bewild** [BernardoGiordano/PKSM#439]
Hey Bernard I have some suggestions but I don't know if you it's possible . 

Can you guys pretty please put back the wondercards back into the new update as I found that extremely helpful an maybe with more events in it. Or can you guys put more events into the events section or maybe both . I would be forever in your debt if you could pretty please make this happen. 

I don't know if you guys can make this happen but are you able to put in an option where if you click on an event it gives you a picture of the English or a different language  one . As I would find this heaps eaiser. Pretty please Bernard 

Thank-you kindly 
Jacinta :)

**Comment by BernardoGiordano** [comment]
I'm not sure what are you asking for

**Comment by B2bewild** [comment]
Oh . 

Um basically when you get events from the events file or when you go to the gen Pokemon part to make it so you can get a different language on that event. Cause it comes to English in my game . An to bring back the wonder card to the new update for pksm where you can dump alot of events into your game like the Jeremy events and all that . 


An can you please include alot more events pretty please . ??

**Comment by Hyperom** [comment]
@BernardoGiordano I believe that @B2bewild is asking that you implement the ability to  import wondercard pokemon and events as they are, but in another language, for example, if a Japanese Pikachu were to be release, but instead of it being Japanese it would be In english. Although that is 100% a guess on my part as the user's english is very hard to understand.

**Comment by B2bewild** [comment]
Hey Hyperom

That's what I'm trying to say sorry about the confusion. 

Bernard  can you please add more events please . If possible

**Comment by B2bewild** [comment]
Also Bernard one other question. 

What's the lowest pksm version you have as a mate has a 3ds that the version is 9.2 on the console. And wants pksm ??? Or can you suggest anything ?? Thank-you :)

**Comment by B2bewild** [comment]
Hey Bernard can you please also make it easier to put in the sid and tid of the trainers information on the Pokemon . Cause the way it is now is driving me nuts . Pretty please

**Comment by BernardoGiordano** [comment]
What @Hyperom said is already implemented, and you should wait for a new release. Also, if an event is available in a certain language only, it **can't** be shown in another language. For the TID/SID fact, I don't have plans to change that functions as it is, for now.
