### ISSUE TITLE
Not able to edit party

### ISSUE THREAD

**Issue by Tech0verlord** [BernardoGiordano/PKSM#44]
To me, it seems one major thing that is missing is the ability to interact/edit our Party Pokémon.  While it is nice to be able to edit what's in our boxes, I'm surprised that party pokemon aren't available to be messed with.

**Comment by replicaJunction** [comment]
+1. I was actually about to open an issue for this...this is already an amazing project with a great deal of polish, but party support would be hugely helpful.

**Comment by Garro** [comment]
I know stuff like PkHex can't edit the party nor the battle box in XY/ORAS/SM. So I guess it's much harder than edit a few parameters in the save file.

**Comment by rehv** [comment]
> I know stuff like PkHex can't edit the party nor the battle box in XY/ORAS/SM and are kept in read-only

False. You can't edit the battle box, true, but you can edit the party directly.

**Comment by BernardoGiordano** [comment]
Added in the [latest commit](https://github.com/BernardoGiordano/PKSM/commit/c075ef87392837df55ec15aab0e7970489389e5f)

**Comment by replicaJunction** [comment]
Awesome! Thank you very much!
