### ISSUE TITLE
"Failed to receive status code"

### ISSUE THREAD

**Issue by Tempest1012** [BernardoGiordano/PKSM#441]
Good Morning/Evening people, it's been 3 days that i'm trying to get PKSM to work on my 2DS. I have tried using the homebrew version, the cia version and downloading it from the QR (cia again), but it won't work. I'd also like to add that i've tired installing the assets manually and that I'm connected to the internet, and i'm using the latest version (4.3.0), which are the 3 main issues for the program not working, as I read on some online forums. Could you please help me with this? Thanks for reading.

**Comment by BernardoGiordano** [comment]
Install manually the assets correctly as described in the readme.

**Comment by BernardoGiordano** [comment]
Even though it could be possible your pksm version is not the latest one
