### ISSUE TITLE
Offering help with text (and the Portuguese translation)!

### ISSUE THREAD

**Issue by HiddenMane** [BernardoGiordano/PKSM#442]
I apologize if I'm posting this on the wrong place, but I'm a noob at this.

I just found this app and it's just amazing, awesome work.
However, I can't help but notice a few minor issues regarding text such as:

- Inconsistent formatting;
- Minor errors (PokeDex instead of Pokédex, for example);
- General lack of the "é" in the Poké- prefix.

I know this isn't a big deal and not that important compared to other issues, but I believe it does make a difference in improving the already great design of the app.

Therefore, here I am offering my contribution to fix these issues! I just don't know where to submit the updated .txt files so they're used in the "official" build.

Also, I am in the process of doing a better translation of the Portuguese file. The variant supported by the 3DS (as far as I know) is the European Portuguese variant and not the Brazilian one. Currently the translation is a mess of both variants and includes unofficial terminology (which most of the time should be English one), so I've been working on that as well.

Should my contribution be accepted I'm ready and happy to start helping, I just need to know where to submit the files!

**Comment by Gudf** [comment]
You should make a pull request. To learn how to do this, go to https://guides.github.com/activities/hello-world/

**Comment by Gudf** [comment]
Just edit the appropriate files in the repo and make a pull request

**Comment by BernardoGiordano** [comment]
You can attach the patched file here too, there are plenty of ways to upload it. If you don't have experience in doing Pull Requests, I'll upload the code in the repo for you.

**Comment by BernardoGiordano** [comment]
any news on this? I'll close the issue within 24 hours if there are no news.

**Comment by HiddenMane** [comment]
Apologies. I pasted the patched "app" files on pastebin, if that helps.
I tried my best to make sure everything was correct, accurate and consistent, but something could have slipped. Anyway, here they are:

English: https://pastebin.com/fUFst09Z
Portuguese: https://pastebin.com/8G23S7ZR

**Comment by BernardoGiordano** [comment]
thanks, added!
