### ISSUE TITLE
Hex editing for Pokémon Version

### ISSUE THREAD

**Issue by Sheven2409** [BernardoGiordano/PKSM#443]
Hi everyone, this is my first post.
In godmode it is possible to edit "Version" (byte "0xDF") but all values are numeric. Is there a source that lists which Version each value represents?

**Comment by Gudf** [comment]
You can find this on PKHeX repo

**Comment by Sheven2409** [comment]
Thanks for your quick reply, I read through "GameVersion.cs". Now, the default hex value is 1B for my game, I have OR,  I'd like to change a few values to Gen 3 Sapphire. I couldn't find 1B in 
"GameVersion.cs" though, could you point me in the right direction?.. 
Follow up question is my understanding of the "Version" byte correct? I assume it to be the game that the Pokémon originated in.

**Comment by Gudf** [comment]
It's the right file, but values are in decimal in PKHeX, and hexadecimal in PKSM.
Afaik, yes, that's correct.

**Comment by Sheven2409** [comment]
Ah I see, so I just pop the value into an online converter and I have my value!! Thank you so much Gudf

**Comment by Gudf** [comment]
Np
