### ISSUE TITLE
Feature request: Pokémon editor for DPP versions

### ISSUE THREAD

**Issue by metalgroudon** [BernardoGiordano/PKSM#444]
I was starting again my platinum version and was thinking about to complete dex, but I have only two options in the 3ds app, events and save info.

There is a third option named other, but it does not anything.

Thank you.

**Comment by kamronbatman** [comment]
This is not really feasible because Gen 4/5 must be played on a DS flashcart.

**Comment by Gudf** [comment]
@kamronbatman What ? No it doesn't.

**Comment by kamronbatman** [comment]
You can play Gen 4/5 games on certain flash carts such as CycloDS using NTRLauncher.

**Comment by BernardoGiordano** [comment]
Well, PKSM does support original DS carts, so it will be done if I'll ever have the time to dedicate to it

**Comment by metalgroudon** [comment]
My problem in this case is that I'm playing with an original game. I'm not using flashcards or something else.

That's why I request an editor like gens 6 & 7 for all generatinons that are supported by the app.


If it cannot be done, I have no problem with it. :)

**Comment by Gudf** [comment]
It can be done @metalgroudon.

**Comment by metalgroudon** [comment]
I hope so, @Gudf

**Comment by kamronbatman** [comment]
yeah it can be done with original carts, sorry I thought that was already assumed.

**Comment by metalgroudon** [comment]
@kamronbatman, I tried to do, but I cant't do it with the currently version of 3ds app. Unfortunally, as I said in the beginnig of my post, all that I can do with the app, is download the events for every game. No more.

**Comment by Gudf** [comment]
@metalgroudon It's normal, since it's not implemented yet, but Bernardo said it would probably be whenever he'll have time to dedicate to it.

**Comment by metalgroudon** [comment]
I know, @Gudf. I'm glad to receive a response about my request. :)

**Comment by BernardoGiordano** [comment]
Closing. It will come when/if it's done
