### ISSUE TITLE
11.5 Crash

### ISSUE THREAD

**Issue by SAIYAN48** [BernardoGiordano/PKSM#445]
When I try to use the editor for Sun, it causes an ARM11 crash.

N3DSXL: 11.5 Luma 8.1, B9S 1.2

**Comment by BernardoGiordano** [comment]
explain better your issue

**Comment by SAIYAN48** [comment]
Here is the dump from the most recent crash.
[crash_dump_00000017.zip](https://github.com/BernardoGiordano/PKSM/files/1167574/crash_dump_00000017.zip)

**Comment by BernardoGiordano** [comment]
you should still state if using the rosalina/*hax/cia version, the PKSM version and what you did to make the crash occurr

**Comment by SAIYAN48** [comment]
Sorry, I'm using the cia version.

**Comment by BernardoGiordano** [comment]
answer all the questions

**Comment by SAIYAN48** [comment]
PKSM 4.3.0. I selected Sun, it loaded the save, then I pressed editor and the crash occurred.

**Comment by BernardoGiordano** [comment]
can you backup your save with JKSM and send it here? there could be some corrupted slots in the first box of your save

**Comment by SAIYAN48** [comment]
This is Nova Sun (rom hack), but I haven't had any issues with it until today.
[Sun.zip](https://github.com/BernardoGiordano/PKSM/files/1167619/Sun.zip)

**Comment by SAIYAN48** [comment]
You were right about the corruption. I deleted a few Pokemon and everything is fine now.
