### ISSUE TITLE
"Incorrect size for this game" on White 2

### ISSUE THREAD

**Issue by jakedubleyew** [BernardoGiordano/PKSM#446]
I am using PKSM through Homebrew, the cia doesn't have an edit option when I choose White 2.  I have the PKSM.3dsx in my 3ds folder.  No clue why this won't work, I have done PKSM before but that was a good 6-8 months ago.  Never saw this error back then.  Thanks for any help

**Comment by BernardoGiordano** [comment]
It's explained in the readme.
