### ISSUE TITLE
Request: Edit Pokemons original game

### ISSUE THREAD

**Issue by PaS-NaS** [BernardoGiordano/PKSM#448]
It would be great if we could edit where the pokemon was caught (not the route and stuff but in which game it was). As it automatically puts the route and that things, it would be great if I could generate a pokemon in Moon and put that it was hatched in ORAS. The main reason for this is Tutor moves. Pokemon with tutor moves will cause legality problems if they were hatched in SuMo.

**Comment by BernardoGiordano** [comment]
It's possible with the built-in hex editor.
