### ISSUE TITLE
Not able to find data for digital version of Y and AS, or cartridge version of Moon

### ISSUE THREAD

**Issue by SnazzyYoshi** [BernardoGiordano/PKSM#45]
Not sure if it's just me, or if it's because I'm on 11.1 using the HBL. The app says "Game not found! Press A to continue." Upon pressing A, the system boots back into the HBL.

**Comment by BernardoGiordano** [comment]
https://github.com/BernardoGiordano/PKSM/wiki/FAQ

**Comment by SnazzyYoshi** [comment]
Thank you, my fault for not looking first.
