### ISSUE TITLE
Pksm problem please help !!.

### ISSUE THREAD

**Issue by B2bewild** [BernardoGiordano/PKSM#452]
Hello Bernard I have a friend who wants pksm on there 3ds but it's 9.2 firmware . They have tried the updated pksm onto it an it freezes like no tomorrow , it goes to where you choose the cart that your playing and to the page where you edit generate and events that screen freezes . Is there an much older older pksm that can handle the firm ware of 9.2 ???? 

Please an thank-you.

**Comment by Gudf** [comment]
He should really install CFW and update FW at this point.

**Comment by BernardoGiordano** [comment]
I'm pretty sure PKSM perfectly works on FW 9.2. Also, there absolutely **no point** to still be on 9.2, since, for example, Sun/Moon needs at least FW 9.6 to run correctly. Tell your friend to use The Guide and get his firmware updated.
