### ISSUE TITLE
Updater bug/issue

### ISSUE THREAD

**Issue by JFSushi** [BernardoGiordano/PKSM#458]
Heya! 

I just encountered a minor bug/issue using the updater function in 4.4.0. After I ran the updater while on 4.4.0, I exited the application only to find the app disappear from my home menu.

I was able to reproduce this twice (out of two attempts), and it only seems to occur after running the updater.

**Comment by zweilous** [comment]
related to the updater but not this bug in particular, the updater installs the .cia version even when you're running the .3dsx version of the app.

**Comment by BernardoGiordano** [comment]
@zweilous do you mean rosalina .3dsx right?
anyways, it deleted the application because you're installing the same exact .cia twice

**Comment by zweilous** [comment]
@BernardoGiordano yea i'm using the new hb menu with rosalina

**Comment by KevinBlue18** [comment]
Yeah this happened to me using .cia

**Comment by NinjaBoyLao** [comment]
This also happened exactly as first described. I updated from within the app and it completely uninstalled itself. I am already on luma 8.1.1, i just didnt see the update for this until just now. It was a `.cia` version to start with, and afaik it should've attempted to install another cia on top of it
