### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Eriun** [BernardoGiordano/PKSM#459]
Can it be used on version 11.5.0-38U? Thanks!

**Comment by BernardoGiordano** [comment]
Yes, even though I need to push a new release to fix some compatibility issue that have been introduced. I'll close the issue when it's been released

**Comment by Eriun** [comment]
Thanks for the update, it will be beneficial.

**Comment by Eriun** [comment]
Oh, last question:

Will it still be the same installation process? And the soundhax part under homebrew?

**Comment by Eriun** [comment]
I can't seem to have it working tho. Not really techie here and at some point i need guide in installing them

**Comment by BernardoGiordano** [comment]
But I just said you have to wait for a new release

**Comment by Eriun** [comment]
Oh yeah, just wanna try it tho. Just getting excited for this since the time i got an accidental update on my 3ds and got jammed up with the soundhax thing

**Comment by BernardoGiordano** [comment]
the compatibility release has been attached to the latest release, try it.
