### ISSUE TITLE
PKSM Language Changed

### ISSUE THREAD

**Issue by saarawolf** [BernardoGiordano/PKSM#461]
When I entered the first time in PKSM the language was english, but the next time I entered it was changed to korean. How can I fix that?

**Comment by BernardoGiordano** [comment]
Do you mean the PKSM interface language?

**Comment by saarawolf** [comment]
Yes

**Comment by BernardoGiordano** [comment]
Go into the settings menu and switch language from the button on the bottom

**Comment by saarawolf** [comment]
Thank you very much

**Comment by vigilfloyd** [comment]
Bernardo i can´t  change the language options + and - do not work

**Comment by BernardoGiordano** [comment]
Pressing A or X will change it.
