### ISSUE TITLE
Crash when launching game from within PKSM

### ISSUE THREAD

**Issue by DarthVitrial** [BernardoGiordano/PKSM#465]
Steps to reproduce: Open any game in PKSM 4.4.0 (tested X, ORAS, Moon), press start to exit, say yes to opening the game, the system will crash. 

Crash dump: 
https://mega.nz/#!ptMEgQZJ!VFWq6uKuL6ZHZTB537zWz8Ud9Lx9U2YzGbFXxRstbQU

Using B9S 1.2, Luma 8.1.1, Clock+L2, n3DS XL on 11.5.

**Comment by BernardoGiordano** [comment]
known and fixed

**Comment by DarthVitrial** [comment]
Oh, sorry, I checked the latest commits but didn't see anything that resembled this so I didn't realize it was fixed. (then again I don't really know code, so)
