### ISSUE TITLE
Please show Pokémon gender

### ISSUE THREAD

**Issue by rehv** [BernardoGiordano/PKSM#47]
Unless I'm blind, I can't see gender in the summary? It would be really nice to have for bank :)

using: 
-pokémon moon e-shop ver.
-pksm 3.1.0
-luma3ds 6.6

**Comment by BernardoGiordano** [comment]
Added in the [latest commit](https://github.com/BernardoGiordano/PKSM/commit/c075ef87392837df55ec15aab0e7970489389e5f)
