### ISSUE TITLE
Pokemon Pearl PKSM use

### ISSUE THREAD

**Issue by SpaceBroMiles** [BernardoGiordano/PKSM#472]
Confused as to how to get this to work, i read through other issues but I am lost on the phrasing about 'Triggering' through poketransporter. Do i need to use HBL to do this? i only have access to the Poke transporter through my main ds menu,
I think i am mostly confused on accessing this game through PKSM

**Comment by BernardoGiordano** [comment]
This isn't a help Q&A. Consider asking for troubleshooting in [PKSM's Discord](https://discord.gg/bGKEyfY).
