### ISSUE TITLE
Red screen while trying to start app (Homebrew)

### ISSUE THREAD

**Issue by Bas25** [BernardoGiordano/PKSM#475]
When I try to open PKSM using homebrew it starts loading and then it gets freezed on a red screen.
What can I do?

**Comment by BernardoGiordano** [comment]
Download the PKSM homebrew Fix in the releases and use that instead

**Comment by Bas25** [comment]
Ok. I'll try it later.

**Comment by Bas25** [comment]
Thanks! It worked!
