### ISSUE TITLE
"Game Not Found" Error on N3DS 11.1 using Ninjahax and HBL 1.1.1

### ISSUE THREAD

**Issue by vlalo001** [BernardoGiordano/PKSM#48]
I execute the ninjahax payload to boot into The Homebrew Launcher (v 1.1.1). From HBL, I run PKSM 3.1.0, with Moon set as the target (physical US cartridge). PKSM loads successfully, and I choose Moon as my game in its menu. Immediately after I select moon however, I get a message on the top screen saying "Game Not Found, Press A to Continue".

**Comment by rehv** [comment]
You have to select pokémon bank as target when launching via HBL.

**Comment by vlalo001** [comment]
My mistake, thank you it's working now
