### ISSUE TITLE
Simplified Chinese can't display in PKSM 4.5.0

### ISSUE THREAD

**Issue by kuai18** [BernardoGiordano/PKSM#483]
When choose language Simplified Chinese in PKSM 4.5.0,
some words can't display.
I am using Japanese version new 3DS LL.
Hope to fix it in next PKSM version.
Thanks!

**Comment by BernardoGiordano** [comment]
That's because Chinese characters are only available on Chinese consoles. PKSM now uses the console shared font so you have to own the proper console to display the proper character.
