### ISSUE TITLE
No logro instalar la version 4.5.0 :(

### ISSUE THREAD

**Issue by daniel95000** [BernardoGiordano/PKSM#484]
Tengo un 3ds en la version 11.2.0-35U y no habia tenido problema en la instalacion de las anteriores versiones. Tengo la ultima version tambien del homebrew que puso Smealum en su pagina (Starter kit).

Yo como no soy muy bueno con eso de los hack uso Soundhax y ahi entro al homebrew.

Borre todos los archivos de la anterior version (4.4.0) y los únicos archivos que deje son los que aparecen en la carpeta Data. 

Yo descargue "PKSM.zip" , me meti en la carpeta "Standar" copie y pegue el "PKSM.cia" en la parte principal de la SD y el resto lo meti en la carpeta "3ds" en una subcarpeta llamada "PKSM"

Cuando abro el PKSM en el Homebrew me sale un pantallazo rojo y ya he tratado varias veces y aun no me funciona . Nose porque no me funciona , si alguien pudiera ayudarme se lo agradeceria :(

**Comment by BernardoGiordano** [comment]
This isn't a help Q&A. Consider asking for troubleshooting in [PKSM's Discord](https://discord.gg/bGKEyfY).

**Comment by daniel95000** [comment]
oh perdon no sabia :(

**Comment by daniel95000** [comment]
el problema es que no se hablar ingles :(, la otra vez necesite usar el traductor :s

**Comment by BernardoGiordano** [comment]
You don't need to use the PKSM.cia file. you need to use the PKSM.3dsx file.

**Comment by daniel95000** [comment]
igual no me funciona, le quite ese archivo y sigue sin funcionarme :s

**Comment by BernardoGiordano** [comment]
try this and report back if it works. https://github.com/BernardoGiordano/PKSM/releases/download/4.5.0/PKSM-HomebrewFix.zip

**Comment by daniel95000** [comment]
si funciona!! gracias bernardogiordano :)
