### ISSUE TITLE
4th gen and 5th gen not working on 4.5.0

### ISSUE THREAD

**Issue by Coaste** [BernardoGiordano/PKSM#485]
After updating to homebrew 2.0.0 and updating to pksm 4.5.0 my gen 4 and gen 5 games no longer work after opening them through poketransporter it gets stuck with the red screen but gen 6+ games work perfectly fine.

**Comment by BernardoGiordano** [comment]
did those work on 4.4.0 with the exact configuration?

**Comment by daniel95000** [comment]
tengo el mismo problema que él :(

**Comment by BernardoGiordano** [comment]
try this and report back if it works. https://github.com/BernardoGiordano/PKSM/releases/download/4.5.0/PKSM-HomebrewFix.zip

**Comment by Coaste** [comment]
@BernardoGiordano The homebrew fix worked great thank you!
