### ISSUE TITLE
lost storage slots

### ISSUE THREAD

**Issue by smokemus** [BernardoGiordano/PKSM#487]
After updating PKSM and using it to xfer pokes from my ruby version to my moon i lost access to view most of my boxes in pokemon moon via ingame, i can still look at them in PKSM though. Tried reloading an old save from savemanager and still bugged, tried re-dling game and loading the save that way and still bugged. im on luma 8.1 11.5 u bs9 and using the cia of pksm.

**Comment by BernardoGiordano** [comment]
Send a copy of the save file

**Comment by smokemus** [comment]
[main.zip](https://github.com/BernardoGiordano/PKSM/files/1279887/main.zip)

**Comment by smokemus** [comment]
Was able to fix it by loading the sav via pkhex and changing the amount of boxes unlocked from 8 to 32.
