### ISSUE TITLE
Perhaps add a way to return to game select w/o restarting the application?

### ISSUE THREAD

**Issue by SuperOkazaki** [BernardoGiordano/PKSM#49]
Not a big deal, and shouldn't be made a priority, but it would be nice if you could implement a way to quickly switch between games without restarting the whole app. I swap between games a bunch while using the bank feature and that would make things much speedier.
Thanks for the great application!

**Comment by BernardoGiordano** [comment]
[Duplicated](https://github.com/BernardoGiordano/PKSM/issues/42), closing
