### ISSUE TITLE
Mewtwo Illegal?

### ISSUE THREAD

**Issue by renzloX08** [BernardoGiordano/PKSM#490]
Using the legality checker my mewtwo always shows as illegal (generated or my legit mewtwo from X/Y transfered using pokebank). Tried generating other pokes and its legal. BTW are generated pokes usable online? I read somewhere that I should change the TID/SID?

**Comment by BernardoGiordano** [comment]
This isn't a help Q&A. Consider asking for troubleshooting in [PKSM's Discord](https://discord.gg/bGKEyfY).
