### ISSUE TITLE
Feature request : Switch screen bank

### ISSUE THREAD

**Issue by fumoffu80** [BernardoGiordano/PKSM#491]
Hello, thanks for this wonderfull homebrew! 👍 

I would like to know if in your next releases you can add 2 things in bank system :

- add the possibility to choose which screen display for more speed and comfort of use.

  exemple :  UP game box n°1 / DOWN game box n°10
                   UP bank box n°1  / DOWN bank box n°10
                   UP game box / DOWN bank box
                   UP bank box  / DOWN game box

- add the possibility to clone pokemon or clone the box in the bank system.

Thanks in advance

PS : The pokemon form changer isn't easy to find without indication.

**Comment by BernardoGiordano** [comment]
This is not feasible
