### ISSUE TITLE
Feature Request - twloader save editing

### ISSUE THREAD

**Issue by MistieKitteh** [BernardoGiordano/PKSM#492]
Ability to modify DS saves from twloader (.sav)

Maybe by allowing people to configure the location of saves or automatically look for the save /roms/nds/Pokemon Platinum Version.sav for example

**Comment by Jolty95** [comment]
As TWLoader coworker, I want to say saves are not always on that folder. If this ever gets done, you'll need to parse settings.ini file (`SD:\_nds\twlodaer`) to find where is roms\nds folder :)

**Comment by Tinytimrob** [comment]
+1

My save file path format for Platinum is /roms/nds/3797__NTR-CPUE-USA__POKEMON PL.sav. It's probably going to be different for everyone, especially if people have multiple versions and/or they are playing rom hacks, so allowing people to configure the save path by hand would be nice

**Comment by juliocorzo** [comment]
As far as I know, PKSM will never support save editing in any game other than the official Nintendo game cartridges. So no flashcard or twloader support is planned.

**Comment by gaiaweylyn** [comment]
Perhaps not, but maybe TWLSaveTool can help enable Gen IV and V editing through PKSM to begin with.

**Comment by Silver7x** [comment]
And how ?

**Comment by Supermariotyt** [comment]
Just download Pkhex, open it, put your sd card or wherever your save is at, click file then open on pkhex, find your save, double click it, then edit the pokemon you want, then click export sav, then overwrite your save

**Comment by Silver7x** [comment]
thx

**Comment by Supermariotyt** [comment]
Np.
