### ISSUE TITLE
I cant use PSKM with Ds games

### ISSUE THREAD

**Issue by guiballa** [BernardoGiordano/PKSM#493]
I already read the Readme and tried opening poke transporter, however it loads and stops with a black screen

**Comment by BernardoGiordano** [comment]
Did you use the PKSM homebrew fix?

**Comment by guiballa** [comment]
Sorry to ask, but what fix ?

**Comment by BernardoGiordano** [comment]
The homebrew-specific version of PKSM. Check releases page

**Comment by DavidGomez18** [comment]
The new .3dsx file is supposed to replace the original one, correct? If so, I get an error that the size is incorrect for Soul Silver.

**Comment by guiballa** [comment]
I just got it working, thank you
