### ISSUE TITLE
chinese characters error

### ISSUE THREAD

**Issue by Tobyheiam** [BernardoGiordano/PKSM#494]
my friend told me chinese characters can't not display normally. when i changed eng to chs, the app crashed.

**Comment by BernardoGiordano** [comment]
Your friend needs to have a Chinese console now to display them

**Comment by v0idst4r** [comment]
@BernardoGiordano What do I do to set it back to the default language? It crashes when I go into options or the editor part

**Comment by BernardoGiordano** [comment]
remove `/3ds/data/PKSM.i18n.bin`

**Comment by Tobyheiam** [comment]
most Chinese use JAPN console, unless they have a HK console, they are unable to use the app in Chinese.

**Comment by BernardoGiordano** [comment]
that's not PKSM's fault. It's the shared font that has been made that way

**Comment by Tobyheiam** [comment]
but before version 4.5, there is no such error. i will told them they need a HK console.

**Comment by BernardoGiordano** [comment]
Before 4.5.0 we used a different graphic library. With the new one, the font changed
