### ISSUE TITLE
Crash when launching game through PKSM

### ISSUE THREAD

**Issue by Tech0verlord** [BernardoGiordano/PKSM#495]
I saw that this was previously opened then closed about a month ago. Was originally on B9S 1.2, Luma 8.1, 3DS 11.3, then updated thinking that was the issue and am now using B9S 1.3, Luma 8.1.1, 3DS 11.5.  Even after updating the 3DS still crashes with a dump. Then came the thought that it could be because of Luma game patching causing issues, but even with it disabled, I still crashed. I was testing this with a physical version of Pokemon Moon on my N3DS, with the latest update (1.2 as of right now) installed.

[Luma Crash Dumps Download](https://mega.nz/#!ipEQzILJ!OVt4XGZGLaQmtRKAVaMMHEdc8N-U9Gd3z3Az_Agy2y4)

Edit: To be clear, after editing anything through the app, or doing nothing, and regardless of when I exit I choose to save or not, if I attempt to launch Pokemon Moon through PKSM, 3DS will crash with the Luma Dumps I linked to above.

Edit 2: Looking at other posts, didn't know you needed to know which launch method. I'm using the CIA version.

**Comment by KevinBlue18** [comment]
The same thing is happening to me too. I’m using cia version.

**Comment by cetertel** [comment]
I've had this issue as well. 11.6 Pokemon Sun n3DS XL, willing to grab crash dumps and stuff if you would like.

**Comment by User13181408200115** [comment]
Same for me with Sun, X and AS
