### ISSUE TITLE
Servelegality Crashes.

### ISSUE THREAD

**Issue by Kuzzoh** [BernardoGiordano/PKSM#497]
Actually while doing Servelegality on 4.5.0, it crashes after putting the IP's on both devices. 
To be more specific the PKSM Freezes completely.
How may we fix this?

**Comment by BernardoGiordano** [comment]
Can I see your IP addresses in serveLegality?

**Comment by Kuzzoh** [comment]
![servelegality_2017-09-13_04-22-18](https://user-images.githubusercontent.com/31919033/30369945-0de6db06-9844-11e7-8a35-f06cd10f4209.png) Here's the picture

**Comment by BernardoGiordano** [comment]
Are you using some kind of VPNs?

**Comment by BernardoGiordano** [comment]
closing in 24h.
