### ISSUE TITLE
Game not Found.

### ISSUE THREAD

**Issue by HitagiCrab1** [BernardoGiordano/PKSM#499]
Alright, so I literally just got Homebrew about 20 Hours ago, and I installed Hax, via Cubic Ninja, I have system 11.5, and I downloaded PKSM, the most recent version. I installed it to my Homebrew, and downloaded all the assists, but when I launch it to select the game I want to use. It says "Game not found." And returns me to the home-screen. What could I be doing wrong?

**Comment by BernardoGiordano** [comment]
Do you have the PKSM.xml file?

**Comment by HitagiCrab1** [comment]
I don't believe I do, I thought all of the files were strapped in the .zip file, which folder would .xml folder fall into?

**Comment by HitagiCrab1** [comment]
Alright, I've installed the XML File, and all of the games work except for Moon, however when I boot it, it crashes the system; and I've got to hard reset my 3DS. What might cause that? Sorry if I seem like a bother, I'm still new to all this. >-<

**Comment by BernardoGiordano** [comment]
It seems you have an old entry point or payload. It's not a PKSM issue
