### ISSUE TITLE
Can't inject Events in Diamond

### ISSUE THREAD

**Issue by tonsofpuppies** [BernardoGiordano/PKSM#501]
I select the Pokémon and the language, then press start to inject. B to leave the menu and make sure to save the changes. It goes through a fairly lengthy "saving" screen, showing 524kbytes. Once it gets to within a few kB, the PKSM app closes and returns me to the Home Screen. When I load the game, there are no Pokémon in my Party or in my PC. Am I doing something wrong? I'm using CFW, btw.

**Comment by BernardoGiordano** [comment]
You're supposed to redeem the event in a pokemart.

**Comment by tonsofpuppies** [comment]
Aha, gotcha. Were event Pokémon disturbed through the Poke Mart back in Gen IV? It's been so long I can't even remember (I just started a new Diamond playthrough today for the first time in many years). For so long I've been redeeming at the Pokémon Center. lol
