### ISSUE TITLE
[Enhancement] Inject Wondercards from SD

### ISSUE THREAD

**Issue by PlasticJustice** [BernardoGiordano/PKSM#504]
Add a feature that allows users to inject wondercards from their SD cards. Have it like when you click the Events tab in PKSM, it then gives you two options. Event Database and SD Card. Then when someone click on the SD card option it opens SD card navigator where you would then find and select the wondercard you want to inject. This way people can inject wondercards without a PC and not having to wait for the Event Database within PKSM to be updated.

**Comment by BernardoGiordano** [comment]
How would you send a wondercard into the SD card without a computer? The web browser wondercard injection is extremely more feasible than what you suggested, since it works on mobile phones too.

**Comment by PlasticJustice** [comment]
I meant as if the wondercard was already on the SD card (or dumped with MysteryGiftDump). That way you can inject wondercards, that are not in the Event Database, offline. As opposed to using serveLegality's wireless wondercard injection, which requires a wifi connection.
