### ISSUE TITLE
Battle Spot Legality Issues

### ISSUE THREAD

**Issue by Terbrox** [BernardoGiordano/PKSM#505]
[Been desperately trying for the last week to create my team on Pokemon Moon through PKHex. Gallade is the only one who passes legality checks on battle spot no matter what I do. Anyone more educated than I know the cause of the problem?](https://i.imgur.com/Mb5917Z.png)

**Comment by Tyulis** [comment]
Do you used PKHex or PKSM?

**Comment by Terbrox** [comment]
I'm using PKHex. Should I be using PKSM for Gen VII instead?

**Comment by Tyulis** [comment]
So post to the [PKHex repo](https://github.com/kwsch/PKHeX/issues)
