### ISSUE TITLE
Feature request: Select wonder card file from SD

### ISSUE THREAD

**Issue by joemck** [BernardoGiordano/PKSM#506]
We can dump wonder cards to the SD with MysteryGiftDumper, but there doesn't seem to be a way to inject them. It would be the most streamlined if the app simply showed a list of usable wonder card files found in the directory that MysteryGifyDumper puts them in.

For example, I collected my Mewnium Z from Bank in the wrong game and now I'm trying to correct this by dumping its wonder card since it's not in the list built into the app, and then injecting it in the game I actually wanted it in.

**Comment by BernardoGiordano** [comment]
#504

**Comment by joemck** [comment]
I just did get wonder cards into my SD card without using a PC, by using MysteryGiftDumper.3dsx.
