### ISSUE TITLE
Can't Launch Moon EU version

### ISSUE THREAD

**Issue by chrisvannooten** [BernardoGiordano/PKSM#51]
Running CFW 9.2 Luma 3DS 6.6.
Installed it with CIA provided with 3.1 release.
Deleted it and installed it again but from FBI titleDB list.
Tried to run it with Homebrew launcher using Pokebank as target.
In all cases I got "Game not Found! Press A to continue."
When I got pushed into the home menu Moon's icon was visible.
Do I need higher firmware (would be odd) to use the application or is EU not supported yet?
Edit: I can run Alpha Sapphire btw with the CIA installed version

**Comment by BernardoGiordano** [comment]
Try updating your cfw, 9.2 is literally pointless

**Comment by chrisvannooten** [comment]
Ah yes, that did the trick. Never updated my CFW out of paranoia but it booted just fine and now the app works with Moon.
