### ISSUE TITLE
Feature Request: Change abilities

### ISSUE THREAD

**Issue by hypershadic661** [BernardoGiordano/PKSM#510]
Just wondering, since you can put any move onto any Pokémon, could there be a way to put any ability onto any Pokémon? Can that be done? It's doable on Action Replay, I know that, so there's some way it can be done. Just a suggestion, though.

**Comment by cetertel** [comment]
This can be done afaik using the hex editor feature. Can't remember if you need to enable god mode, but it can be done.

**Comment by hypershadic661** [comment]
There's a hex editor feature in PKSM? Didn't know that. Thanks!
