### ISSUE TITLE
Pokédex entry is not changed when sending Pokémon to gen 6 game.

### ISSUE THREAD

**Issue by juliocorzo** [BernardoGiordano/PKSM#511]
## How to reproduce

1. Catch Pokémon in ORAS.
2. Send to PKSM storage.
3. Send Pokémon to different ORAS game.
4. Pokédex entry is not added in the second game.

Tested on latest release.

**Comment by BernardoGiordano** [comment]
that's because pokedex flags are not even implemented for gen6. That's not a bug.

**Comment by XiNaru** [comment]
that ist for gen  pokemon too. when i tranfer ONE pokemon from bank zu game, the pokedex is updating. but if i tranfer a complete box, the pokedex was not updated

**Comment by juliocorzo** [comment]
I agree with XiNaru, I have personally experienced this issue on gen 7 games. Previously, after saving the bank, the game would edit Pokedex flags, it seems like it is not doing so now. 

Right now, the best way to mass transfer Pokémon is using PKHeX. I hope this issue is just an error somewhere. Regardless, thanks for the explanation Bernardo.
