### ISSUE TITLE
Changing Language/Region of Pokemon & serveLegality issue

### ISSUE THREAD

**Issue by yungroyalski** [BernardoGiordano/PKSM#513]
Hi guys. I know this might be a noob question, but I'm new to PKSM and I'm wondering how a couple of things work. 

1. I can't seem to find a way to change the language of my pokemon (USA, France, etc.) as well as the "met location" and from my readings in this thread I need to inject a wondercard to do so, but I have no idea what that means lol can anyone help me with this?

2. I want to grab servelegality, but I can't seem to find a working link. Anyone know where I can find one?

Thanks in advance everyone!

**Comment by BernardoGiordano** [comment]
1) hex editor is able to change that.
2) https://github.com/BernardoGiordano/PKSM-Tools
