### ISSUE TITLE
[Feature Idea] Editing Game Origin Markings

### ISSUE THREAD

**Issue by rikko1203** [BernardoGiordano/PKSM#514]
Maybe we can edit the Pentagon, Black Clover and OG Gameboy markings while creating a pokemon for Gen7 Games. This may remove the issues of Gen7 born pokemon having Gen6 Move tutor only moves.

**Comment by BernardoGiordano** [comment]
you already can through the hex editor.

**Comment by rikko1203** [comment]
can you tell me which string?
