### ISSUE TITLE
Bulk move not setting Dex

### ISSUE THREAD

**Issue by DioVento** [BernardoGiordano/PKSM#517]
When I withdraw an individual Pokemon from PKSM's bank to a game save, the game save updates the Pokedex to have "captured" that species and form, etc. When I use the feature that withdraws entire boxes, however, it doesn't update the Pokedex. This is a massive pain when it comes to maintaining a living National Dex and using it to fill out new save files' Pokedexes.

**Comment by AnalogMan151** [comment]
Maybe to do with this? #536
