### ISSUE TITLE
PKSM is stuck in foreign language; opening options crashes program

### ISSUE THREAD

**Issue by samalonson** [BernardoGiordano/PKSM#518]
I found the same issue [here](https://github.com/BernardoGiordano/PKSM/issues/488) but the poster closed the topic without providing a solution.

I accidentally changed the language from my language (english) and was cycling back through the languages when the program crashed.  Now the program runs in what looks like Japanese and opening the options menu causes a crash. [Picture](https://imgur.com/a/fZqxs)

I am running the .cia version of PKSM which I installed with FBI, and I unzipped the PKSM-master folder and copied it to the root of my SD card.  I tried deleting the software and reinstalling the .cia, but the program is still in the same foreign language.

If you could help me reset the language, or help me fix my install if I did something wrong, I'd be very grateful.

I am using an O3DSXL running software version 11.6 with Luma3DS v8.1.1, and Pokemon Sun (if that matters at all)

**Comment by BernardoGiordano** [comment]
remove the `3ds/data/PKSM/i18n.bin` file from the sd card.

**Comment by samalonson** [comment]
Thank you for the immediate response!  Fixed.

**Comment by jayzone1** [comment]
dosent work

**Comment by jayzone1** [comment]
help
plz
