### ISSUE TITLE
[Feature Request] Inject Wondercards from SD

### ISSUE THREAD

**Issue by PlasticJustice** [BernardoGiordano/PKSM#519]
To clarify what I said in issue #504 and probably what @joemck meant in issue #506, 
I said, "Add a feature that allows users to inject wondercards from their SD cards. Have it like when you click the Events tab in PKSM, it then gives you two options. Event Database and SD Card. Then when someone click on the SD card option it opens SD card navigator where you would then find and select the wondercard you want to inject. This way people can inject wondercards without a PC and not having to wait for the Event Database within PKSM to be updated."

What I mean is, as if the wondercard is already on the SD card (or dumped with MysteryGiftDump). That way you can inject wondercards, that are not in the Event Database, offline. As opposed to using serveLegality's wireless wondercard injection, which requires a wifi connection and a PC.

**Comment by joemck** [comment]
That is exactly what I meant. I had just dumped a fresh wondercard I received from Bank into the wrong game using MysteryGiftDump, and then thought I was going to inject it into the game I actually wanted it in; only to discover that I instead had to transfer the file to a PC and then serve it back to the 3DS.

**Comment by solarsaturn9** [comment]
+1
I am unable to get wireless wondercard injection to work and doing injection from a local file seems like it would be much less frustrating.

**Comment by BernardoGiordano** [comment]
I added a different method to inject wondercards which doesn't require connecting to the internet. Injecting from the SD Card is not feasible, though.

**Comment by solarsaturn9** [comment]
Wifi wondercard injection does not appear to work
