### ISSUE TITLE
"Incorrect size for this game!"

### ISSUE THREAD

**Issue by UhhLegoboy** [BernardoGiordano/PKSM#522]
Here are the details:
O3DS, 11.5.0-38U, method of launching: Notehax, no CFW, HB launcher version: 1.11, latest version of PKSM, trying to edit: Pokemon Heart Gold.
Error message: "Incorrect size for this game!"
Does anybody happen to know what is wrong? I can't seem to figure it out...

**Comment by BernardoGiordano** [comment]
It's explained in the readme.
