### ISSUE TITLE
New totems/forms may stay in the storage if transferred

### ISSUE THREAD

**Issue by Larryturbo** [BernardoGiordano/PKSM#529]
For PKSM 5.0.0
I have a Rockruff with own tempo (not the actual event one) in my PC and I can put it into Bank 1 no problem but then I can no longer put it back into my PC Boxes. When I use the Blue Swap button it just disappears entirely.

**Comment by BernardoGiordano** [comment]
I probably need to be update the form list in the application. Don't transfer it for now, or don't save progresses if it disappeared

**Comment by Larryturbo** [comment]
I tried to make a fresh install just to be sure it's not some remnant of the previous version. I don't think it is.

**Comment by BernardoGiordano** [comment]
nope, that's a bug I need to fix.

**Comment by taksaru** [comment]
This bug extends to the Pikachu form changing

**Comment by VEGETAHuelva** [comment]
The same thing happens to me, but to me with the rockruff of the real event, I can pass it to the bank, but I can not bring it back to the ultra sun pokemon game.
I use version 5.0.0
Thanks, it's a great tool.

**Comment by AnalogMan151** [comment]
Maybe something to do with this? #536

**Comment by BernardoGiordano** [comment]
I'll leave it open until I fix the storage problem, too. Please report me all forms that makes this behaviour evident, and please dump me the .pk7 for such units.

**Comment by CharaDreemurr** [comment]
I'm having any Totem Pokemon, and the new Necrozma forms do this. I can pick em up and put them in the box, but as soon as I try to put them back into the game, they refuse to go back in. Was hoping to use it to resort my boxes.

**Comment by BernardoGiordano** [comment]
this is being investigated
