### ISSUE TITLE
QR Camera difficult to trigger with L+R

### ISSUE THREAD

**Issue by AnalogMan151** [BernardoGiordano/PKSM#531]
I find that the timing to activate the QR camera is extremely sensitive, taking multiple tries before I'm able to activate it. 

I believe that it could be due to this conditional here:
https://github.com/BernardoGiordano/PKSM/blob/bf73691218a6b14eff9aec001b453ad12bb8c3df/source/sections/events/events.c#L372

I think it can be resolved by changing it to:
```cpp
if ((hidKeysDown() & (KEY_L + KEY_R)) && game_is3DS())
```

I would try this edit and do a pull request myself but the build environment isn't working quote right for me on MacOS at the moment. If I get it figured out I'll go ahead and test it myself.

**Comment by BernardoGiordano** [comment]
this will trigger the camera even if just L or R are pressed alone

**Comment by AnalogMan151** [comment]
You're right, I didn't realize how that check worked. Can you use:
```cpp
if ((hidKeysHeld() & KEY_L) && (hidKeysHeld() & KEY_R) && game_is3DS())
```
Instead so it triggers as long as both are being held instead of pushed at the exact same moment?
