### ISSUE TITLE
Zeraora Bug

### ISSUE THREAD

**Issue by Tk77185** [BernardoGiordano/PKSM#533]
Can't add Zeraora in pc

" This pokémon doesn't exist yet "

**Comment by BernardoGiordano** [comment]
You're not supposed to.

**Comment by flarn2006** [comment]
What? Why not? What if I want one?

**Comment by ScytheIronclaw** [comment]
Is there an option to turn generating this Pokemon on? If not, could an option be made to toggle on/off this legitimacy check?

**Comment by flarn2006** [comment]
@ScytheIronclaw I made an edited version that doesn't have this restriction: https://github.com/flarn2006/PKSM/releases/tag/v5.0.1a-mod

**Comment by Phillip12123** [comment]
Zeraora is out now so can you make an update for Zeraora
