### ISSUE TITLE
Options Menu takes me to a hex edit version of the menu

### ISSUE THREAD

**Issue by halosamuel44** [BernardoGiordano/PKSM#540]
As the title says, whenever i press the Options menu on PKSM v5.0.0, instead of the normal menu, a Hex Edit window appears with all the options being they corresponding hex values. I personally don't have a problem with this but with the fact that it won't let me edit those values to change the options, Right now I don't have my 3DS (o3DS) at hand, but if it's necessary, i can attach a photo tomorrow morning (it's 3:00 am here)

**Comment by BernardoGiordano** [comment]
This is intended.
