### ISSUE TITLE
Camera Freezes System

### ISSUE THREAD

**Issue by stoponerr** [BernardoGiordano/PKSM#545]
There was an issue reported where in the use of the QR scanner would cause the users 3ds to freeze a few seconds later without fail.

**Comment by BernardoGiordano** [comment]
Did you press anything to make this happen?

**Comment by stoponerr** [comment]
No, just opened camera and waited.

**Comment by BernardoGiordano** [comment]
which 3ds model are you using? I'm not able to reproduce this issue
