### ISSUE TITLE
Put the ReadMe file in the PKSM.zip

### ISSUE THREAD

**Issue by GrimmHubber** [BernardoGiordano/PKSM#549]
After asking about the "deleted" storage, I was told to read the ReadMe file
Which is hard to do when:
-> you updated w/ QR code
-> the read me file isn't in the PKSM.zip

After reading carefully through the changes I noticed the path of the info was moved from 3ds/data/PKSM and it made sense TO ME, someone w/ previous knowledge about how saving and loading reference file work, that that's why the storage wasn't loading.

I did find the read me file afterwards, in the .zip with the source code, that I didn't download in the 1st place b/c since I'm not a programmer I though I had no business messing around w/ that. 

I hope that by moving the info from the old location to the new the storage will load as was usual. And If you are going to dismiss people with RTFM then put TFM where anyone will be able to easily find it.

**Comment by BernardoGiordano** [comment]
you were supposed to ad least read the changelog, that is something you should do in every case you download/update a program. There you can see what changed, and I explained this thing there as well, so anyone wanting to inform himself could see.
