### ISSUE TITLE
wont detect game cart?

### ISSUE THREAD

**Issue by charge1** [BernardoGiordano/PKSM#55]
i have the cia version of moon and the cart version of moon but for some reason it never detects the cart version the cia works fine though 
. rxTools
. 9.2.0 firmware for emunand

**Comment by BernardoGiordano** [comment]
Do you select the correct game? Which sys ersion do you have? Please be detailed, this doesn't help none of us

**Comment by BernardoGiordano** [comment]
You have to update to the latest firmware. 9.2 is obsolete.

**Comment by charge1** [comment]
alright thank you
