### ISSUE TITLE
Error when Switching out of PKSM

### ISSUE THREAD

**Issue by GriffinG1** [BernardoGiordano/PKSM#552]
If you hit HOME while in editor, then go to launch a game (might just be with usum), gets looped in closing suspended software

**Comment by BernardoGiordano** [comment]
You're not supposed to exit with the home button, you could not save in that way, so stick with START

**Comment by GriffinG1** [comment]
The simple fact that exists is an issue. If someone is trying to leave without saving, and would rather not back out through 4 menus, home is a quicker option.
