### ISSUE TITLE
Question about bank

### ISSUE THREAD

**Issue by miniadri** [BernardoGiordano/PKSM#56]
Hello, I have a quick question about the bank. It's supposed that all the pokémon getting with this are illegal or for example, if I transfer one Rowlett from Sun.cia to Moon cartridge using pksm, this poke will be illegal? I want to get the 3 initial pokes buy I only have one console so I can't send it by Internet or local. 
And the last one, I promise, the pokémon getting with the mass injection and the other are legal, right? 

Thanks for your attention and your homebrew, it's amazing.

**Comment by BernardoGiordano** [comment]
Gen7->gen7 is legitimate.
For the other question, it depends on your ethic about legitimacy.

**Comment by miniadri** [comment]
Ok, thanks for you help. 

You can close this if you want ;)
