### ISSUE TITLE
QR Codes Won't Scan

### ISSUE THREAD

**Issue by NayrTheLovable** [BernardoGiordano/PKSM#560]
Using 5.0.0 on Ultra Moon and no matter which QR code I scan, nothing happens. I press L and I sometimes even try holding L and nothing works. Even used Mystery Gift Bot and nothing. Don't know if I'm doing something wrong or if it's a bug, but hope it gets resolved soon

**Comment by BernardoGiordano** [comment]
QR codes works fine, they're just hard as fuck to scan because their dimensions. Follow the guidelines precisely, keep your camera perpendicular to the QR code and have firm hands

**Comment by NayrTheLovable** [comment]
Guess I gotta try harder then. Though no matter how precise I am, it doesn't seem to work
