### ISSUE TITLE
[Ultra Sun] Event Rockruff stuck inside the bank 

### ISSUE THREAD

**Issue by A7F** [BernardoGiordano/PKSM#563]
just pointing out that event Rockruff (the one which should become dusk Lycanrock) got stuck inside pksm bank: I can't withdraw it.
I moved it inside the bank by pressing the "mass transfer" button, then I tried to move it back in my Ultra Sun pc box but pressing A desn't work to "put it down".

P.s. Also, can confirm on issue #561 cause also my pokedex don't get updated

**Comment by BernardoGiordano** [comment]
Fixed in #529
