### ISSUE TITLE
[old 3DS] "save info" button doesn't work

### ISSUE THREAD

**Issue by A7F** [BernardoGiordano/PKSM#564]
I don't know if this was an intended thing but the button "save info" doesn't do anything, seems like "a button without his action listener" (sorry, java background... I had no clue how to explain this but I'm sure you get it).

I own an old nintendo 3ds B9S and Luma3ds latest along with your latest PKSM.

btw let me thank you for your amazing app! 😄

**Comment by BernardoGiordano** [comment]
that button is not programmed at all
