### ISSUE TITLE
PKSM change ultraSun language

### ISSUE THREAD

**Issue by rayyilin** [BernardoGiordano/PKSM#568]
After i use PKSM 5.0.1 my ultra sun change to ENG but my original language is CHT.
I find there was old issues said can find a event with my language.
But there is no any event is CHT.
is there any other way can change Game Lang?

**Comment by BernardoGiordano** [comment]
What did you change to make it happen?

**Comment by rayyilin** [comment]
i think maybe i use event without CHT

**Comment by rayyilin** [comment]
I try use https://github.com/BernardoGiordano/PKSM/issues/427 to solve the problem.
but i can not find event with CHT

**Comment by BernardoGiordano** [comment]
You shouldn't have that option set. There are no CHAT events sadly, so your only option is to edit your save with PKHeX or inject the automatic backup.

**Comment by rayyilin** [comment]
Oh! I see.
please help my to check step 
1.use SaveDataFiler export ultra sun Save file
2.use PKHeX to exit language
3.use SaveDataFiler import save file

**Comment by BernardoGiordano** [comment]
any other free save manager is good, too

**Comment by JunkyDude** [comment]
Bringing up the dead but just had issue. Easier fix, and O.P's issue most likely came from event injecting pokemon and checking convert language to WC where he selected a different region wondercard (presumably O.P thought it meant it would change that text to English).

Simple fix. Go back into PKSM, chose a English event pokemon and inject it with the option as before enabled. Make sure to save before exiting PKSM all the way.
