### ISSUE TITLE
Pokemon generator

### ISSUE THREAD

**Issue by gloddo** [BernardoGiordano/PKSM#57]
Progetto molto interessante (anche se con una versione precedente ho perso tutti i pokemon che avevo messo in banca..). 
Sarebbe possibile includere un sistema per generare pokemon?

**Comment by BernardoGiordano** [comment]
avresti dovuto leggere le release notes, perchè quel comportamento era descritto più che bene, quindi non mi assumo responsabilità.
Al momento quello non è nelle priorità

**Comment by BernardoGiordano** [comment]
inoltre è tutto ancora recuperabile, dato che puoi trovare i backup automatici nella cartella /3ds/data/PKSM/backup . C'è tutto lì

**Comment by gloddo** [comment]
Stava in EventAssistant, ma ti amo lo stesso. Comunque penso che sarebbe una feature pazzesca da inserire, visto che immagino più o meno il processo è simile a quello della modifica delle statistiche. Per ora l'unico modo di farlo è con il PKHEX che fa piangere. 
Comunque daje forte.
