### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by Tenshouyoku** [BernardoGiordano/PKSM#570]
1. Language interface is broken (at least somehow for me). Instead of a GUI which allows users to select their language quite conveniently in the older versions, it somehow became a bunch of codes.
![img_20171121_213242](https://user-images.githubusercontent.com/33868678/33075403-49693bc8-cf04-11e7-85a5-856008942e70.jpg)

2. New forms are not implemented correctly. Forms such as Dawn Wings/Dusk Mane Necrozma and Dusk form Lycanroc cannot be selected and shown in their respective sprites correctly, although they seem to be working.

**Comment by BernardoGiordano** [comment]
Invalid
