### ISSUE TITLE
Feature Request: Add Chinese font in PKSM

### ISSUE THREAD

**Issue by kuai18** [BernardoGiordano/PKSM#572]
After version 4.3.0, some Chinese text can't be displayed on Japan or American 3DS.
Can you add Chinese font in PKSM for it?
Thank you very much!

**Comment by BernardoGiordano** [comment]
Impossible. Use a Chinese console to read chinese characters

**Comment by kuai18** [comment]
OK, I see.
But why all Chinese characters can be displayed in PKSM 4.3.0 on Japan 3DS?

**Comment by BernardoGiordano** [comment]
The graphic library has changed. https://github.com/BernardoGiordano/PKSM/commit/e3ce6e4d440e0b06edc92fbc8eb174ea92dfdff7

**Comment by ericjwg** [comment]
any chance to use stand alone font file instead of system font?
customize font with utf-8 encoding supports jpn, kor and chs/t all sort of characters.

**Comment by BernardoGiordano** [comment]
Sadly it's not possible anymore
