### ISSUE TITLE
Current Handler Bug

### ISSUE THREAD

**Issue by Qiyao7** [BernardoGiordano/PKSM#573]
the current trainer`s information is 00 00 00 00......... when drawing a pm from pksm bank to USUM. This cause a pm can`t evolve by friendship. Not sure if legality problem arise or not in a competition.

I reply this in another post but that post is old, and not actually the same concern. So I open a new post. 
 Let me talkthis in detail: 

Why I found this is that I sent my hatched Buneary from Moon to Ultra Moon, and later found it cant evolve even the friendship is 255 (I did not change anything through pksm). Then I found the the change occurs to the friendship of original trainer not current trainer, while the data of current trainer ID is 00 00 00 00...... . So I guess when I draw a pm form pksm storage to new game, it do nothing with the current trainer data, which cause system thought this pm is in the original trainers hand (change affects to the friendship of Original Trainer), but the IDs are different so when judging a friendship evolution, it checks the friendship of Current Trainer (which is 00 00...... as no current trainers data). Then for fix it I changed the friendship of Current Trainer to 255 by pksm and left the Current Trainer ID blank as before (I don`t know how to fix this) . then back to the game it evolved.

I think this is a BIG BUG of PKSM. 

Thanks to your contribution to create PKSM. Making it better is what everyone here want to see.

version 5.0

Adding 22 Nov. 2017
This bug happens only when pm is sent to USUM, I tried XY to SM, the current handler is correctly my SM ID.
P.S. sorry but I`m not a native speaker of English so some words such like trainer and handler, not precise.

**Comment by DavidG777** [comment]
This is true for me as well on 5.0.1.

Transferred from the bank in bulk, and on top of not flagging the pokedex correctly, when I opened the savefile in PKHex all Pokemon were illegal due to having a blank current handler.

**Comment by Qiyao7** [comment]
Thanks a lot!
