### ISSUE TITLE
Bulk Move not setting Dex [Repeat]

### ISSUE THREAD

**Issue by DioVento** [BernardoGiordano/PKSM#575]
I think this: https://github.com/BernardoGiordano/PKSM/issues/517 was closed erroneously. Bulk withdrawing Pokémon from PKSM's Bank into a game doesn't set those Pokémon as Owned in the game the way PKSM does when you withdraw one at a time. (as of v5.0.1 this behavior is still present)

**Comment by AgeSlacker** [comment]
There is a ticket for this already #569

**Comment by BernardoGiordano** [comment]
#569 duplicate
