### ISSUE TITLE
Crash when opening Sun/Moon Cart Save

### ISSUE THREAD

**Issue by castsaku** [BernardoGiordano/PKSM#578]
Hey, I get these crash when I try to load a Moon save from cart, using CIA and Rosalina.

[dump.zip](https://github.com/BernardoGiordano/PKSM/files/1500393/dump.zip)

Only solution for now is go back to 4.x

**Comment by BernardoGiordano** [comment]
I need your savefile

**Comment by castsaku** [comment]
Here

[main.zip](https://github.com/BernardoGiordano/PKSM/files/1500817/main.zip)

**Comment by BernardoGiordano** [comment]
the only solution is to fix the corrupted slot you have in your save, Box1-Slot1. Use PKHeX to do that
