### ISSUE TITLE
Bank.bin issues

### ISSUE THREAD

**Issue by robot10210** [BernardoGiordano/PKSM#58]
Tried several times trying to make a bank.bin that follows your listed attributes, being sized N*30*232. Going for 1500 boxes, I did 1500*30*232 = 10440000. I went to HxD, clicked "insert bytes" and put 10440000 while I inserted "00"s. Saved as bank.bin in /3ds/data/PKSM/bank/.

When I go to bank in the program, it says "bank.bin has a bad size!". It even said this with the originally included or created bnk.bin. plz help m8

**Comment by BernardoGiordano** [comment]
Please wait, I'm fixing code related to that and making an automatic generator for the new bank

**Comment by BernardoGiordano** [comment]
fixed in one of the previous commits
