### ISSUE TITLE
The natures editor shows wrong order of stats in Japanese

### ISSUE THREAD

**Issue by genkagen** [BernardoGiordano/PKSM#580]
PKSM/assets/romfs/i18n/en/app.txt
Line 154 - 163
```
-Attack
-Defense
-Speed
-Sp. Atk.
-Sp. Def.
+Attack
+Defense
+Speed
+Sp. Atk.
+Sp. Def.
```

 PKSM/assets/romfs/i18n/jp/app.txt
```
-攻撃
-防御
-特攻
-特防
-素早さ
＋攻撃
＋防御
＋特攻
＋特防
＋素早さ
```

the right order in Japanese should be as following:
```
-攻撃
-防御
-素早さ
-特攻
-特防
＋攻撃
＋防御
＋素早さ
＋特攻
＋特防
```

**Comment by pass0418** [comment]
すみません、日本語でしか喋れませんが、既に修正しました。次の更新時には治っていると思います。
(Sorry,I can't speak English…)

**Comment by pass0418** [comment]
I already fixed.Thank you for your kindness.
(Sorry for my bad English!)

**Comment by genkagen** [comment]
誠にありがとうございます！

**Comment by BernardoGiordano** [comment]
#581
