### ISSUE TITLE
Feature Request: Affection Editor

### ISSUE THREAD

**Issue by royr719** [BernardoGiordano/PKSM#582]
Currently there's no way to edit the affection value.
It would be nice to be able to edit affection the same way as friendship.
This should be pretty easy to add if the offsets are the same as in gen VI pkm structure:

0xA3 | NotOT Affection
0xCB | OT Affection

**Comment by BernardoGiordano** [comment]
This can easily be done through the hex editor

**Comment by royr719** [comment]
Are you referring to PkHex?

**Comment by BernardoGiordano** [comment]
Nope. PKSM has a built-in hex editor.

**Comment by royr719** [comment]
I just checked.
Well, I can edit the affection offsets there.
Thanks.
