### ISSUE TITLE
Can I make suggestions?

### ISSUE THREAD

**Issue by VirgileVILE** [BernardoGiordano/PKSM#585]
I will have two small suggestions to make your tool even more perfect ...
The first: Would it be possible to give names to the boxes of the bank? Believe me it would be very convenient.
The second thing: It's really ... silent. Is it possible to have a background music? for example the relaxing music of the nocturnal diamond / pearl pokemon center.
Thank you in advance for reading this post.

**Comment by BernardoGiordano** [comment]
#170 duplicate. For the silence, I don't think it's an urgent issue, so the bugfixing/feature implementation will have priority
