### ISSUE TITLE
Unable to select certain pokemon in PKSM

### ISSUE THREAD

**Issue by samalonson** [BernardoGiordano/PKSM#586]
I have read that some people have an issue where when they try to transfer a box from their game to the bank certain pokemon do not move.  They are able to deal with this by moving the pokemon individually.

However, in my case, several pokemon do not move and I am unable to select them to move them individually.  I am also unable to select these pokemon in the editor.  Is this a known bug?

If it helps, [here](https://imgur.com/a/uR3Ir) is a picture of the pokemon that I cannot select.

**Comment by BernardoGiordano** [comment]
I bet those are in a battle box

**Comment by samalonson** [comment]
Yeah, you'd be right.  
You've helped me out twice now, so I'll get you a coffee!  Keep up the good work, I appreciate it!
