### ISSUE TITLE
Feature Request: DS Savedata Location

### ISSUE THREAD

**Issue by roryfree** [BernardoGiordano/PKSM#587]
It would be neat if there was a directory in which PKSM would look for .sav files of gen 4/5 games, so that they could be edited with it. Flashcart users could take their saves, put them into a directory like PKSM/ds/ or something the like, and have PKSM access them from there. Once the editing is done, one would manually move them back to the flashcart's SD card.

**Comment by BernardoGiordano** [comment]
Sadly I'll not work to support save loading other than from catridges
