### ISSUE TITLE
Sun and Moon saving issue?

### ISSUE THREAD

**Issue by 5bitx** [BernardoGiordano/PKSM#59]
I go to change the money to max, or to change the language, then I leave the menu and press start to save and close the app to go to Sun, but nothing's changed? Why are Sun and Moon functions not working?
By the way, when will item injecting be available?

**Comment by Golisopod** [comment]
Are you on hbonly? I'm getting the same error, when I go to the menu and press start to save, the process skips instead of saving and goes back to GridLauncher.

**Comment by BernardoGiordano** [comment]
Which PKSM version are you using?

**Comment by 5bitx** [comment]
Newest model you released! I actually just downloaded it today, haha

**Comment by BernardoGiordano** [comment]
are you sure that you clic START to save only when you're in the correct menu page? There's no way it doesn't save your progresses if you do everything as I say. Just tried to do what you did, and it worked fine.

**Comment by 5bitx** [comment]
Yep, just tried it again myself. I clicked start, says it saved, then X to leave the menu. Then I go to my game, and everything is the same. :/

**Comment by BernardoGiordano** [comment]
Maybe you have both cart and digital version and you're trying to inject on one instead of another? I can't get the point of this issue, because this should not be an issue at all

**Comment by Golisopod** [comment]
I'm sure. I know I'm on the most recent version, I started using PKSM 5 days ago, the day of the last release. I press start on the main menu page (where EVENTS/EDITOR/OTHER is) and it skips the saving processes. I've tried on OR and X and it works perfectly.

**Comment by 5bitx** [comment]
Nah, I only have physical carts. I'm running Luma firmware if that means anything? Dunno if there's any sort of compatibility issue or anything, just putting that out there.

**Comment by BernardoGiordano** [comment]
Sure to be on 3.1.0 instead of 3.0.2? The behaviour you're talking about is proper of 3.0.2 release

**Comment by 5bitx** [comment]
I'm 99% sure I'm on the newest, but how can I check to be sure?

**Comment by BernardoGiordano** [comment]
Just go to the main menu, version is written on the right bottom of the top screen

**Comment by 5bitx** [comment]
V3.1.0

**Comment by BernardoGiordano** [comment]
mmmh. Are you sure to click START also when trying to max money or edit language?

**Comment by 5bitx** [comment]
Wait, click start before I do edits?

**Comment by BernardoGiordano** [comment]
You have to click start to trigger that kind of edit

**Comment by BernardoGiordano** [comment]
it will says something like 'Money set successfully'

**Comment by 5bitx** [comment]
Ahh okay. I'll try that real quick. By the way, any ETA on items?
--
Sent from myMail for Android Friday, 25 November 2016, 04:07PM -05:00 from Bernardo Giordano  notifications@github.com :

**Comment by BernardoGiordano** [comment]
I'll not be releasing anything until the end of the next week, at least

**Comment by 5bitx** [comment]
Okay, awesome! Also, do you plan to bring in an editor for festival plaza points?

**Comment by BernardoGiordano** [comment]
Is this considered solved?

**Comment by 5bitx** [comment]
Uh, yep I guess so! Can't wait to see future updates! Keep up the good work!
