### ISSUE TITLE
Hex value for Form on Lurantis, Salazzle, ect, cannot be edited to make them totemlike.

### ISSUE THREAD

**Issue by frozenLake** [BernardoGiordano/PKSM#592]
In the most recent games, you can acquire a handful of pokemon from Professor Oak that are Totem Sized pokemon. this information is stored in the same hex location as gender and faithful encounters, being a seperate form. however, the hex increase with the A button can only go to 2, where as I would need to increase such a value past 8 to affect this. A quick fix to this would be nice, but I realize there are a handful of other things that would need tweaking before release.

**Comment by BernardoGiordano** [comment]
you definitely already can change that byte, too. There's a special hex editor mode that allows you to do that.

**Comment by frozenLake** [comment]
I just stated that the hex editor won't work, though.

**Comment by BernardoGiordano** [comment]
And I stated that you **can** go past 8 to change the form to whatever you want, using the advanced version of that function

**Comment by frozenLake** [comment]
Ah, I understand now.

For those that are unaware and viewing this, you can activate the advanced hex editor by tapping the corners of the regular hex editor: Top Left, top right, bottom left, bottom right.
