### ISSUE TITLE
Need help to build the CIA back

### ISSUE THREAD

**Issue by basilhorX99** [BernardoGiordano/PKSM#595]
First of all, I'm sorry for being a noob. I tried to build the CIA, read a lot of tutorials but still couldn't figure it out. I need the latest build for the flagging for my pokedex with mass transfer. I wasted almost 5 hrs trying to figure this out. It's almost 1 a.m. in my place and I've to be at work at 5 a.m. It'd be kind if someone can guide me to successfully build it back up. Thank you. Also sorry for my formatting, tired and sleepy.

**Comment by BernardoGiordano** [comment]
Explain precisely your issue into the discord server.
