### ISSUE TITLE
Impossible to open menu on a pokemon affected to battle box

### ISSUE THREAD

**Issue by iArcadia** [BernardoGiordano/PKSM#596]
I wanted to edit one of my Pokemon on my sun version, but impossible to open the menu when I click on it: impossible to edit, clone or whatever. Eventually, I found out that the bug is present for all my pokemon which are affected to my battle box.

**Comment by BernardoGiordano** [comment]
That's the intended behaviour.

**Comment by iArcadia** [comment]
If that's intended so no prob. But showing a popup alert to prevent the user may be a good idea. (or disabled menu items like when you want to edit a pokemon in your current party)

Thanks four your answer
