### ISSUE TITLE
Handler not changing when transferring Pokémon through bank.

### ISSUE THREAD

**Issue by asaver** [BernardoGiordano/PKSM#599]
I'm trying to transfer Pokémon I had from my Moon save to my Ultra Moon save. Everything goes well, but I noticed in PkHex they are still listed as if belonging to the original trainer. Is there a way to automatically fill in the Latest Handler (not OT) camp when withdrawn from the Bank feature so they pass legality checks?

**Comment by Qiyao7** [comment]
Already fixed #594 
Waiting for next release too.

**Comment by asaver** [comment]
Thanks!
