### ISSUE TITLE
Dusk Lycanroc and Zeraora

### ISSUE THREAD

**Issue by tiNsLeY799** [BernardoGiordano/PKSM#602]
- There is no data present for Dusk form Lycanroc. Only Midday and Midnight are present.
- Necrozma does not have its other forms showing like Kyurem.
- Zeraora is present in the editor, but you cannot do anything to it, such as generate it, edit it's moveset, IVs, EVs etc. BUT PkHex has data for it, so if you use PkHex to add Zeraora into your game, launch PKSM and move Zeraora to the game's bank, you can move it to the bank BUT you cannot put it back in your game. Simple put, you can't do anything with Zeraora. It is just there.

Just thought I'd put this somewhere...

**Comment by BernardoGiordano** [comment]
Everything is intended.

**Comment by JoshEmpeor** [comment]
Is there a forecast for lycanroc dusk and Zeraora to be inserted in the next update?

**Comment by Helius666** [comment]
When will it be available to add the forms of Necrozma? I had a bug in the game, delete Necrozma-lunala and I can't re-merge :c sorry my english xD
