### ISSUE TITLE
Now working for platinum? 

### ISSUE THREAD

**Issue by trashiis** [BernardoGiordano/PKSM#603]
Before you ask- yes I read all of README, I have BOTH dreamradar AND poketransporter. I've tried pksm with black 2 and it works fine. When I try it with platinum it says "incorrect size for this game!" Help?

**Comment by BernardoGiordano** [comment]
does TWLSaveTool work with it?

**Comment by trashiis** [comment]
TWLSaveTool doesn't work in general for me, I've tried everything

**Comment by BernardoGiordano** [comment]
may be a problem with the cartridge, honestly

**Comment by trashiis** [comment]
Maybe. Oh well  ¯\_(ツ)_/¯
