### ISSUE TITLE
Pokédex not registered when moving the whole box at once from bank

### ISSUE THREAD

**Issue by SabaraSkye** [BernardoGiordano/PKSM#607]
Discovered this issue when I was trying to move my mons from SM to USUM.

When I tried to move the whole box at once using the top right button (storage), the pokédex entries of the mons didn't get registered.

The dex do get registered if you move them one by one, though.

**Comment by tiNsLeY799** [comment]
You have to save Pokedex flags upon closing PKSM, at least from the last
time I tried.

**Comment by SabaraSkye** [comment]
The "save pokédex flags" doesn't appear for me, wether it's only me or pksm doesn't have that anymore.

**Comment by BernardoGiordano** [comment]
It has been fixed already in the latest commits

**Comment by rickmlopes** [comment]
I just had this same issue in USUM with version 5.0.1. Can confirm its fixed? Thanks.
