### ISSUE TITLE
PKSM Pokémon vanished

### ISSUE THREAD

**Issue by Otan1** [BernardoGiordano/PKSM#611]
When I was using the PSKM, suddenly all of the pokémon that I've put in the bank vanished. Accidentally, I saved and left. I've already read the readme, but I dont know what to do with the save backups and stuff. Is there any way to recover my pokémon?

**Comment by BernardoGiordano** [comment]
Check the storage part in the readme. Did you update it recently?

**Comment by Otan1** [comment]
I've just seen that PKSM version's at v4.3.0 :/
I'm doing it for my girlfriend, so I couldn't see it right away (the 3DS isnt with me)
How do I update it? Or I just move the bank.bin as said in the readme?

**Comment by BernardoGiordano** [comment]
you update **and** move the bank like in the readme. if you still can't, I don't know how to help if you didn't make a backup before.

**Comment by Otan1** [comment]
I updated it and moved the bank.bin, but the Pokémon are still missing. However, there are backups (on the backup file, obviously). Is there any way to use one of them?

**Comment by BernardoGiordano** [comment]
Load them with a save manager or replace the bank.bin file if they're bank backups.
