### ISSUE TITLE
need help please...

### ISSUE THREAD

**Issue by acetrainerred** [BernardoGiordano/PKSM#616]
hi i currently need help on getting my homebrew to work again
when i had pokemon sun and moon i was able to get to homebrew with soundhax using nedwill 2016
and then from there i was able to get to pksm.
now i have updated my 3ds version and the soundhax doesnt work anymore but from here how would i go about getting homebrew again thru sooundhax if at all possible. and if not how would i go to get pksm a tutorial or a page would be apperatied 
thanks in advance

**Comment by Vikijaka** [comment]
Updating SYS without Luma is a very bad idea... how ever -> 3ds.guide is all you need 
https://3ds.guide

**Comment by acetrainerred** [comment]
Is there a way to get homebrew on soundhax just like before?

**Comment by rikko1203** [comment]
There is, if you can restore sys to atmost 11.3

**Comment by BernardoGiordano** [comment]
This is the wrong place to ask for help. Ask in the Nintendo Homebrew discord
