### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Balxion** [BernardoGiordano/PKSM#617]
I want to thank you for making this and was wondering if there was anyway I could help to get you to the next Gen IV and possibly the Gen I and II VC.

**Comment by BernardoGiordano** [comment]
Thanks. What do you mean for 'to get you the next Gen IV'?

**Comment by Balxion** [comment]
Like to get the pokemon bank working and not just have the event pokemon.

**Comment by BernardoGiordano** [comment]
Contributing to the code is highly appreciated if you have the required knowledge
