### ISSUE TITLE
The Date of Pokemon

### ISSUE THREAD

**Issue by WhitB2003** [BernardoGiordano/PKSM#619]
This is just a suggestion and isn't really a huge issue, but when you generate a pokemon in either of the Ultra games, the date is at 2/1/2017. It is impossible to meet or hatch pokemon at that time because Ultra wasn't released then. I understand that the hex editor can fix this, but it becomes a nuisance to do so everytime. Thx :P

**Comment by BernardoGiordano** [comment]
You can have an arbitrary date, it's totally possible.
