### ISSUE TITLE
Update bannertool so FBI doesn't display TitleID but Title Name

### ISSUE THREAD

**Issue by Favna** [BernardoGiordano/PKSM#62]
This was an issue in bannertool that was fixed way back in June [see here](https://github.com/Steveice10/bannertool/commit/24288b4ec6fc03c91643ab6e86847157296e617b) that causes FBI (among others but FBI most prominently) to show the TitleID instead of "PKSM" when going to the Titles section. This is a seriously super annoying issue and super easily fixed simply by updating your bannertool and recreating the cia pushing it as release 3.1.1. Shouldn't take more than 5 minutes and it's issue that should've been fixed ***MONTHS*** ago!

**Comment by BernardoGiordano** [comment]
I already use the latest bannertool, man. Where I can see graphically the issue?

**Comment by Favna** [comment]
Example image in FBI

![img_0916](https://cloud.githubusercontent.com/assets/4019718/20647075/e5f6a394-b48a-11e6-9539-8a395da1a451.jpg)

**Comment by BernardoGiordano** [comment]
mh, I already have the latest release of bannertool, that's weird. I'll check what's wrong asap

**Comment by Favna** [comment]
Sorry I conveyed the message so bluntly - Actually it was due to my annoyance over this for other applications back then that got Usagi and myself testing&researching the cause and eventually Usagi making the pull request I linked. I hope you can understand that seeing it return in a project that is so actively in development can get a bit infuriating.

**Comment by BernardoGiordano** [comment]
No problems, I understand your point. I think that the problem should be related to the options that the dev specifies when launching bannertool to get his banner packaged. I'll try to put every single option in it and see if it fixes this issue. If so, it would be nice to alert any dev (maybe for the future) regarding the correct usage of bannertool, maybe

**Comment by BernardoGiordano** [comment]
I still can't build a correct smdh, even with the proper args and with the latest build of bannertool. Are you there to help me creating a correct one? I need it for tomorrow, as I'm going to release the new update!

**Comment by Favna** [comment]
Well I can try that's for sure...

**Comment by BernardoGiordano** [comment]
Details are: 
Name: PKSM
Description: AIO tool for Pokemon games
Author: Bernardo Giordano

Banner.png and icon.png are the files you need

**Comment by Favna** [comment]
Hm getting some build errors before I can even try. I'll throw them in here but perhaps if you have Discord that might be an easier way to communicate. My Discord ID is Favna#2846

Note: This error was after ensuring I have the latest in all dependencies and building from windows coz I don't have a Linux VM set up atm. Also this is right after a `make clean`.

```
D:\UserFiles\DevProjects\PKSM>make
Building for 3DS...
build/3ds-arm/source/aes.o
build/3ds-arm/source/bank.o
build/3ds-arm/source/database.o
build/3ds-arm/source/dex.o
build/3ds-arm/source/editor.o
source/editor.c: In function 'pokemonEditor':
source/editor.c:1072:5: error: too many arguments to function 'printPKViewer'
     printPKViewer(mainbuf, pkmn, isTeam, game, currentEntry, menuEntry, box, ED_MENU);
     ^
In file included from source/editor.c:22:0:
source/graphic.h:72:6: note: declared here
 void printPKViewer(u8* mainbuf, u8* pkmn, int game, int currentEntry, int menuEntry, int box, int mode);
      ^
source/editor.c:1649:9: error: too many arguments to function 'printPKViewer'
         printPKViewer(mainbuf, pkmn, isTeam, game, currentEntry, menuEntry, box, ED_CLONE);
         ^
In file included from source/editor.c:22:0:
source/graphic.h:72:6: note: declared here
 void printPKViewer(u8* mainbuf, u8* pkmn, int game, int currentEntry, int menuEntry, int box, int mode);
      ^
source/editor.c:1673:3: error: too many arguments to function 'printPKViewer'
   printPKViewer(mainbuf, pkmn, isTeam, game, currentEntry, menuEntry, box, ED_STANDARD);
   ^
In file included from source/editor.c:22:0:
source/graphic.h:72:6: note: declared here
 void printPKViewer(u8* mainbuf, u8* pkmn, int game, int currentEntry, int menuEntry, int box, int mode);
      ^
make: *** [build/3ds-arm/source/editor.o] Error 1
```

**Comment by Favna** [comment]
Update:

So I just tried using the method I was using for PKSM on FTPDB (My buildtools implementation of FTPD) which worked perfectly. 

(I do get 1 tiny error but it's nothing major and not affecting the build per se - I'm actually gonna shoot up an issue on buildtools concerning it)

**Comment by BernardoGiordano** [comment]
I wasn't expecting you to compile the whole source: I didn't push the latest code and a complete file (graphic.c). That's why I needed the banner only, so I can include it at compilation time.

**Comment by BernardoGiordano** [comment]
NVM, I think I fixed this. It now shows correctly in titles. And goddamn, I was trying your code and basically risked to lose EVERYTHING because I did a make clean but it deleted the whole source folder and I didn't commit the last 2000 changed lines.... Not your fault obviously, I learnt that I need to update more frequently the repo to stay safe.

**Comment by Favna** [comment]
Alright sounds good - I was actually just about to say I get a lot of crap after pulling in 84725e7a9e878273305de7c2789960466a805754 and that I did push to my fork how I changed the makefile and the buildtools submodule but I guess that is no longer required then. That said - if you still want it that way you can manually add it with:

`git submodule add git@github.com:Steveice10/buildtools.git`
(or `git submodule add https://github.com/Steveice10/buildtools.git` if you do not use SSH verification for github)
`git submodule init`
Then add the makefile from my repo and tweak it to preference
