### ISSUE TITLE
issues with Black 2 and White 2 Event TFE Hunter 

### ISSUE THREAD

**Issue by MasterSara85** [BernardoGiordano/PKSM#631]
When clicking on TFE Hunter Crashes the app then reboots the system I don't know if that's a issues or not but can you please fix it soon thanks

**Comment by MasterSara85** [comment]
I found more that are crashing like Milos Island Thunduru and Singing Piplup

**Comment by BernardoGiordano** [comment]
which region is your 3DS?

**Comment by MasterSara85** [comment]
English

**Comment by MasterSara85** [comment]
Missouri

**Comment by MasterSara85** [comment]
sorry I'm in the midwest

**Comment by BernardoGiordano** [comment]
I'm not able to reproduce the error. What language are you using in PKSM interface?

**Comment by MasterSara85** [comment]
English it's fixed thanks again

**Comment by MasterSara85** [comment]
you can close it now keep up the good work its working

**Comment by MasterSara85** [comment]
when are you going to make bank available an editer Available?
