### ISSUE TITLE
Hex editor not allowing edit to met location/egg location

### ISSUE THREAD

**Issue by Edug3154** [BernardoGiordano/PKSM#633]
Hex editor doesn't allow me to edit the location of the eggs(i.e.where was it breeded at)/Pokemon met location despite appearing. Im new to this but i wonder if its just locked atm or being developed and thats why it doesn't let me. Thanks in advance

**Comment by BernardoGiordano** [comment]
You can edit them in the advanced editor mode, find out how to unlock it

**Comment by htownshawina** [comment]
Hhey
