### ISSUE TITLE
Set Orignal Trainer to Self when Generating

### ISSUE THREAD

**Issue by highkeyflammable** [BernardoGiordano/PKSM#646]
Hey so I wanted to have new generated Pokemon automatically have my TID, SID and OT name so I went into the options and changed all those things to match what I have in my game. For some reason though, whenever I generate a new Pokemon and I go to change the friendship and affection on the new Pokemon, it is treated as HT friendship and affection and not OT friendship and affection, and I'm not sure what I am supposed to do to fix this, since the TID and SID of the generated Pokemon match the Pokemon I caught in game.

**Comment by BernardoGiordano** [comment]
#640 duplicate

**Comment by highkeyflammable** [comment]
Hi, so I don't believe that my problem is a duplicate to the other problems. That problem has to do with using the storage built into PKSM, but mine has to do with generating a new Pokemon using the generate feature.
