### ISSUE TITLE
Some pokémons generated in Sun can't be selected anymore

### ISSUE THREAD

**Issue by tuturutut** [BernardoGiordano/PKSM#647]
I have a few pokémons that I generated in Sun that I can't select to move to the bank, edit, clone or whatever, they just aren't selectable at all while others are working just fine. I don't know if its related to the problem but I believe that at some point I edited them on PKHEX. I can provide my save file if needed.

**Comment by BernardoGiordano** [comment]
You can select them if you're on sun.

**Comment by tuturutut** [comment]
My bad. The pokémons where in the battle box, probably that was the reason I couldn't select then.
