### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by Paconxy** [BernardoGiordano/PKSM#65]
Sorry if the question looks dumb, I just don't know how to install external apps to 3DS...

I'd be so thankful if someone could tell me please
Thankyou :)

**Comment by masterchivo** [comment]
You need a custom firmware and any cia installer like Fbi

**Comment by BernardoGiordano** [comment]
this is not related to the app itsel, so I have to close it. Find your question on /r/3dshacks
