### ISSUE TITLE
Mystery Gift injection doesn’t work

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#651]
When I’m trying to use Pokémon Ultra Moon to inject mystery gifts, none of them work and they just leave me with a weird egg mystery egg in my wonder cards. 
Steps to reproduce: 
1.) Use clear mystery gift script 
2.) Inject any mystery gift to any empty slot
3.) Note how none of the slots have actually been written to
4.) Save and open the game and note how there is only a strange egg wonder card

**Comment by BernardoGiordano** [comment]
Change the default date in the PKSM settings and it'll work

**Comment by lior4revivo** [comment]
how do I Change the default date in the PKSM settings?
please help
