### ISSUE TITLE
Pressing up or down on game select screen acts odd

### ISSUE THREAD

**Issue by trainboy2019** [BernardoGiordano/PKSM#653]
When you press down, it an act a bit odd. ultra sun goes to platinum, when it looks like it should go to heartgold. Ultra moon goes to heartgold, when it looks like it should go to soulsilver. Diamond goes to soulsilver, when it looks like it should go to black. Pearl goes to black when it looks like it should go to white. Vice versa for up.

**Comment by BernardoGiordano** [comment]
It doesn't behave that oddly, it just jumps 4 entries. The fact that it seems to work properly in the first rows is just coincidence.

Closing because the engine will be changed in the near future
