### ISSUE TITLE
PKSM configuration for DS Save Access

### ISSUE THREAD

**Issue by ajbos2018** [BernardoGiordano/PKSM#655]
Afternoon, 

I usually do not have issues figuring out how exactly to get various bits of homebrew working on the 3ds, but after hours of mucking around with this i realize that i need a bit more of an explanation.

------------------------------
DS cartridges (*hax)
To let PKSM load your DS save correctly, you need to select a target title that has DS save access when selecting PKSM from the homebrew launcher.
A title satisfying those specifics is, for example, Pokétransporter.
------------------------------

Can you please explain the process you describe above, in a different way or perhaps a bit more clearly for me? Im not sure what you mean by "select a target title that has DS save access when selecting PKSM from the homebrew launcher. A title satisfying those specifics is, for example, Pokétransporter." I cannot for the life of me find the latest version of Pokétransporter, and even if i did i still am lost as to how im supposed to select Pokétransporter while in the homebrew launcher about to launch PKSM. Completely a mystery somehow, and im sure ill feel stupid when you explain. 

I know your time is valuable and stretched short, as is my own - im behind on some remote work due to the amount of time ive spent basically banging my head against my desk. 

Please let me know if you need to know anything specific about how my 3DS is setup; thank you.

**Comment by SpiredMoth** [comment]
You can only get Pokémon Transporter via a subscription to the official Pokémon Bank.
Another option is the eShop game Pokémon Dream Radar, but it's more expensive than a Bank subscription.

When using the *hax version of PKSM, you're asked to select an app before PKSM even loads (this is before PKSM's game choice screen). This is when you would choose Transporter/Dream Radar.

When using the Rosalina version of PKSM, you should inject your Homebrew Launcher into Transporter/Dream Radar via the Rosalina menu.

**Comment by BernardoGiordano** [comment]
I'll correct SpiredMoth in a couple things:

1) Dream Radar is not confirmed to fully work with PKSM
2) you don't need to inject the rosalina HBL to such a title anymore if you're using Luma3DS 9.0+

**Comment by ajbos2018** [comment]
And now I feel slightly less stupid. Thank you for spelling it out for me
like that - and amazing work BTW, pksm is a work of hex editing art
