### ISSUE TITLE
Are the commits supposed to be added when pressing update?

### ISSUE THREAD

**Issue by Mr-Andy-ygo** [BernardoGiordano/PKSM#66]
I see in the commits a lot of fixes that would make the program better, but when pressing update, the wifi light tilts but these featureds don't get installed. I thought they wouldn't be implemented until the next version was out, but I'm not sure if it's like that or not.

Does the updater only work when the next version is out, or does it also update what's in the commits?

**Comment by BernardoGiordano** [comment]
Next version, not next commit. Also, when you reach to download a build with this, you have to install manually through FBI
