### ISSUE TITLE
Help with the new features

### ISSUE THREAD

**Issue by PlasticJustice** [BernardoGiordano/PKSM#660]
I'm having issues finding where in PKSM I can now dump wondercards, and does the qr code scanner scan and inject wondercards (from MysteryGiftBot) because it does nothing when I try to scan a qr code.

**Comment by BernardoGiordano** [comment]
Wondercard dump is possible into the mystery gift slot selection menu. For the QR scanner it's just a positioning problem

**Comment by ccfman2004** [comment]
How do I dump mystery gifts.  I don't see an option in the Mystery Gift Menu on 5.1.1

**Comment by BernardoGiordano** [comment]
Ask in the discord server for support
