### ISSUE TITLE
PKSM Scripts

### ISSUE THREAD

**Issue by supersonic49** [BernardoGiordano/PKSM#661]
where do you put the PSKM Scripts

can you please help me

email me through superzed.sonic93@gmail.com

**Comment by greenDarkness** [comment]
Taken from the ReadMe:
```
Scripts are located under /3ds/PKSM/scripts/<game>. You can add your own by placing them in the right folder.
```

**Comment by PlasticJustice** [comment]
To be more exact:

/3ds/PKSM/scripts/<GAME NAME>/
