### ISSUE TITLE
Repository request: 3dsx

### ISSUE THREAD

**Issue by Leafgreen26** [BernardoGiordano/PKSM#665]
I know that the 3dsx file are located in the .zip, but to make it easier on us who use MultiUpdater, can you put the 3dsx file by itself just like the cia please? i am talking about the rosalina version, not the hax version.

**Comment by SpiredMoth** [comment]
It's not hard to add a Rosalina PKSM entry for MultiUpdater
```
        {
            "name": "PKSM - Rosalina",
            "url": "https://github.com/BernardoGiordano/PKSM",
            "inrelease": "PKSM\\.zip",
            "inarchive": "rosalina/PKSM\\.3dsx",
            "path": "/3ds/PKSM/PKSM.3dsx"
        },
```
