### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by tyrawwrr** [BernardoGiordano/PKSM#666]
The file I downloaded /5.1.1 will not read in English. Has converted to Spanish?

**Comment by BernardoGiordano** [comment]
?

**Comment by tyrawwrr** [comment]
Every time I load up the pksm, everything is in spanish, and there is no
way to adjust. I've uninstalled and installed several times

**Comment by TLATER** [comment]
Have you tried setting the PKSM language option? I figure this is a good time to test-run my docs: [options](https://github.com/TLATER/PKSM/blob/documentation/doc/options.md)

**Comment by tyrawwrr** [comment]
So what would code be for English? I'm sorry just got this new 3ds and
haven't tried homebrew yet, still learning

**Comment by TLATER** [comment]
Hrm, figure it needs more work then.

If you open the settings menu, the very first "byte" you have selected (the little squares in the top screen) determines the language PKSM uses.

Use the x button to reduce that to 01 (if it's Spanish that's 4x, as you can see from the documentation).
