### ISSUE TITLE
I can't change the language 

### ISSUE THREAD

**Issue by scratchking** [BernardoGiordano/PKSM#667]
I opened options and and since then my game has been in Japanese I go to the pksm interface language I try to change it but my N3ds freezes

**Comment by BernardoGiordano** [comment]
please provide more informations

**Comment by scratchking** [comment]
I can't change my ultra sun game language it was originally English and know it is Japanese. When I try to change it my N3ds freezes and goes to a red screen and the top screen has these lines in the color of the rainbow like if homebrew crashs

**Comment by BernardoGiordano** [comment]
use scripts
