### ISSUE TITLE
Will Shiny Sprites Ever Come Back?

### ISSUE THREAD

**Issue by Inkblot777** [BernardoGiordano/PKSM#668]
This really isn't an issue, but I just wanted to know. I really liked it in the old builds where when you had a shiny pokemon in your box, the menu sprite had its shiny colors. However the recent releases don't have them anymore, which is a shame. Will they ever come back, or are they gone for good?

**Comment by sxp5702** [comment]
Lol guess he answered your question in an asshole way huh? XD cracked me up
