### ISSUE TITLE
Feature request: Edit pokéball type

### ISSUE THREAD

**Issue by EduardoJordao** [BernardoGiordano/PKSM#67]
Great application!!

**Comment by Garro** [comment]
I second this! With the inclusion of a single Johto ball per playthrough. Editing the Pokemon's Pokeball would be awesome.

**Comment by BernardoGiordano** [comment]
Added in the [latest commit](https://github.com/BernardoGiordano/PKSM/commit/c075ef87392837df55ec15aab0e7970489389e5f)
