### ISSUE TITLE
USUM "Set Max Money" script doesn't work.

### ISSUE THREAD

**Issue by Takatsuki** [BernardoGiordano/PKSM#670]
I've tried other scripts for USUM (specifically, I'm playing Ultra Sun) and they seem to work, but "Set Max Money" doesn't seem to actually do anything. Could you please fix this script?

**Comment by BernardoGiordano** [comment]
Wrong repo. And it has been already fixed

**Comment by Takatsuki** [comment]
Sorry. Then where should I be looking? Can you link me to the fixed version because I can't seem to find it.

**Comment by BernardoGiordano** [comment]
https://github.com/BernardoGiordano/PKSM-Tools/releases/latest

**Comment by Takatsuki** [comment]
Thank you. :) 
One last question while you're here. I can't seem to get the QR code updater to work for PKSM (not sure if it's the fault of FBI, the code or my system itself), so how do I go about updating PKSM itself without the QR code? Can I just install the newest CIA or do I have to delete the existing one from my system first?

**Comment by BernardoGiordano** [comment]
just install the new cia

**Comment by Takatsuki** [comment]
Thanks again :) Sorry for the trouble.
