### ISSUE TITLE
[request] Virtual console games compatibility 

### ISSUE THREAD

**Issue by johnwraight** [BernardoGiordano/PKSM#671]
Just wondering if In the near future any updates will include compatibility with the gen 1 and gen 2 virtual console games?
Thanks

**Comment by piepie62** [comment]
No, the virtual console saves are only accessible through ARM9, whereas PKSM runs on ARM11.

**Comment by ihaveamac** [comment]
"... only accessible through ARM9"

you're thinking of gba vc games, not the game boy games which are normal userland titles.
