### ISSUE TITLE
[Feature Request] Hex Editor

### ISSUE THREAD

**Issue by ralphwicked** [BernardoGiordano/PKSM#677]
Ability to edit:
*Met Location
*3ds Region / Sub Region
*Game Version

In addition:
Ability to randomize PID & *EncryptionConstant in one box using 1 button only
*Make all pokemon in one box Shiny

I hope this can be added on the future updates O:)

I really love your app/work I hope to see further improvements. Thank you for your effort I really appreciate it <3

**Comment by BernardoGiordano** [comment]
That's already possible in the advanced hex editor mode. Find how to enter it

**Comment by ralphwicked** [comment]
Where do I find the advance hex editor?

**Comment by trainboy2019** [comment]
Read the source code
