### ISSUE TITLE
Problems about serveLegality.exe

### ISSUE THREAD

**Issue by tumyeong** [BernardoGiordano/PKSM#678]
There are several problems about serveLegality.exe.

1. Florges

Just problematic. Florges knows Quiver Dance when it is created even though it CANNOT learn! I want it to learn Moonblast, Wish, Calm Mind, and Toxic. I checked legality by using serveLegality.exe, and it says it is legal. However, Florges is not able to participate random match. After I feed Florges by myself with the sames moves, it is able to participate online match. Three things that I only edited are Florges' Individual Values, Effort Values and Level. It seems that serveLegality.exe has problem. 

2. Gastrodon

Just Problematic 2. I want Gastrodon to learn Scald, Recover, Stockpile and Fissure. Though it is able to learn these moves, serveLegality says it is NOT legal. Of course this Gastrodon cannot participate online match. I checked it. I fed Gastrodon by myself with the same moves, and it is able to participate online match. Like Florges, there are three things that I edited: IV, EV, Level. Strange serveLegality.exe.

3. Inherited Moves

It needs to be updated. ServeLegality.exe does not support updated moves. For example, Lucario can Meteor Mash in USUM if its mother or father know this move. Of course serveLegality says it is not legal, and of course I can use Lucanrio which learned Meteor Mash in online match. I checked it. Additional example: Linoone. Now Extreme Speed can be inherited to Linoone, thanks to GameFreak. 
 Probably, there are more examples. Would you update new moves? 

4. Moves taught by NPCs

Thanks to USUM NPCs, some pokemons can learn new moves. For example, Feraligatr can learn Liquidation in USUM. Of course serveLegality says Feraligatr which knows Liquidation is not legal, and I can use Feraligatr which knows Liquidation in online match. 
 Probably, there are more examples. Would you update new moves?

5. Infernape

I want Infernape to learn Vacuum Wave and it is able. Infernape learns Vacuum Wave in Pt. Only in Pt. I checked legality with serveLegality.exe, and it says it is legal. However, that Infernape cannot participate online match. After that, I checked that Inferape, and it says that this Infernape is born in Pokémon Day Care. It should come from Sinnoh region. I wonder why serveLegality.exe does not reflect this because Umbreon and Seviper knowing Sucker Punch is well reflected: it says they came from Sinnoh region after Legality check. Does only Infernape have problem? Or would there be more problems alike this case? 

I think serveLegality.exe should be fixed some more. Thanks for giving your time to read this.

**Comment by tumyeong** [comment]
One more problem: PKSM does not support some Korean words. ‘Consonant ㅅ + some vowel + (consonant)’ cannot be typed. They are typed like ‘  ‘ or ‘a’ or so. Would you check it?

**Comment by BernardoGiordano** [comment]
Submit this issue in the proper repository, https://github.com/BernardoGiordano/PKSM-Tools
