### ISSUE TITLE
Invalid Size Error

### ISSUE THREAD

**Issue by Sychophantom** [BernardoGiordano/PKSM#68]
Message occurs while selecting digital copy of Moon on Stock N3DS at 11.2 using Cubic Ninja.

**Comment by BernardoGiordano** [comment]
I just tried my HBL version of the app. I managed to get it working both with my cart version, both with a digital version. I don't understand what are you doing wrong

**Comment by BernardoGiordano** [comment]
Update your Homebrew Launcher setup. This fixed the issue for another user.

**Comment by skagno** [comment]
what is your version of hbl? i have same error

**Comment by BernardoGiordano** [comment]
Are you sure to  be selecting the right game with DPAD in the game selector menu within the app?

**Comment by skagno** [comment]
yes, sure, i tried couple of time

**Comment by Sychophantom** [comment]
Add this to the root of your memory card:  https://github.com/ihaveamac/9.6-dbgen-xmls/

There are still occasional errors and yellow screens, but it has allowed PKSM to load via HBL for me.

**Comment by skagno** [comment]
thanks, and i load with pokemon sun inserted and choose them on hbl. Solved for me :)
