### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by melsbacksfriend** [BernardoGiordano/PKSM#685]
I have a plan to make a device that emulates video games and hacks real life so it can hack pokemon into real life.  I was dumping  pokémon and when I tried to dump Type: null, it crashed my 3ds.  Can you plz patch out this glitch.  
![20180219_140939](https://user-images.githubusercontent.com/36408599/36395542-3d1d57f2-157f-11e8-891a-29fd7b4a95e3.jpg)

**Comment by GriffinG1** [comment]
Please don’t shitpost here.

**Comment by melsbacksfriend** [comment]
I'm dead serious.
