### ISSUE TITLE
few Bytes configuration  options

### ISSUE THREAD

**Issue by guillersevilla** [BernardoGiordano/PKSM#687]
Hi, I dont know why, in the screen captures of the lastest pskm versions, i see a lot of bytes configuration (almost the complete screen) but in mine one only appears three lines of configurations, anyone knows why?

Thanks

**Comment by SpiredMoth** [comment]
The screen capture in the readme is the hex editor for editing Pokémon

PKSM Options is a separate hex editor that only has about 3 lines of bytes

**Comment by guillersevilla** [comment]
It's true! thanks!! I have another question, is any way to set the date of created pokemons automatically to the current date? or i have to change it manually? Thanks again!

**Comment by BernardoGiordano** [comment]
it can't be done automatically

**Comment by guillersevilla** [comment]
Ok!! Thank you!!
