### ISSUE TITLE
GameBoy Virtual Console games

### ISSUE THREAD

**Issue by ccfman2004** [BernardoGiordano/PKSM#688]
Will there ever be support for the GameBoy VC Pokémon games like the real Pokémon bank can do?  It is the only thing that would make this better then the official bank.

**Comment by trainboy2019** [comment]
There are no plans to support VC games.

**Comment by ccfman2004** [comment]
Any particular reason?  It's the only reason I keep paying Nintendo for PokéBank use since they support them

**Comment by GriffinG1** [comment]
Bernardo has no want or need to develop it. If you want it, feel free to contribute it yourself.

**Comment by ccfman2004** [comment]
I have ZERO knowledge of the programming langue this project uses.  I thought the purpose of this project was to eliminate the need for the Online only bank.

**Comment by GriffinG1** [comment]
You don't need the online bank. [You can dump the gba save](https://3ds.hacks.guide/godmode9-usage#backup-gba-vc-saves), and pkhex can edit it (at least gen II and up, not sure about gen I)

**Comment by ccfman2004** [comment]
The VC Pokémon games are not GBA.  They are GB/GBC

**Comment by nabithahmed** [comment]
The point is that while PKSM can't edit those saves directly on the 3ds,
you can edit them in PKHeX and inject the Pokémon into your save or even
keep them in their original games.

**Comment by ccfman2004** [comment]
PKHex doesn't run on my system.  Is there a reason why PKSM can't edit those files if JKSM can dump them?

**Comment by GriffinG1** [comment]
Yes. They are a different type of file. I’m going to repeat this one last time. PKSM does not, will not, and unless someone other than Bernardo makes the contribution, probably will NEVER support VC games.

Sent from Mail for Windows 10

**Comment by ccfman2004** [comment]
Then I guess I'm stuck paying Nintendo then.  You don't have to get so nasty.

**Comment by ccfman2004** [comment]
I think this should remain open for someone who wants to help out.

**Comment by Arkangelo** [comment]
Backup your game from VS with Checkpoint [https://github.com/BernardoGiordano/Checkpoint/releases](url)
Send your file to your PC.
Edit the File in PKHex
Send it back to the SD
Restore the File with Checkpoint
If you want to send your Pokemons to other version just open 2 instances of PkHex 1 with the VC save and the other to the save you want to end and easy like grab and drop

**Comment by ccfman2004** [comment]
As I said before PKHex doesn't work on my computer since I don't use Windows.

**Comment by trainboy2019** [comment]
Look on project Pokemon in the pkhex subform. You'll find a thread called pkhex for Mac.

**Comment by ccfman2004** [comment]
Did that days ago. I couldn’t get it to work.

**Comment by trainboy2019** [comment]
Try this. 
https://gist.github.com/trainboy2019/7f7c8ef62e1c2c5cb6d22545575ae715#file-pkhex-on-mac-force-fix

**Comment by PokePro384** [comment]
Do you guys support VC now?

**Comment by GriffinG1** [comment]
Please do not post on closed issues, and see #1181

**Comment by FM1337** [comment]
See pinned issue regarding VC.
