### ISSUE TITLE
PKSM: 

### ISSUE THREAD

**Issue by Cirlias** [BernardoGiordano/PKSM#693]
Everytime i open my pokemon Ultra sun it says: wrong size for this game. First it worked but then i used JKS save manager and checkpoint cus i didnt get the main files from jks and also not from checkpoint so just used Pksm but it keeps saying this. No i didnt select the wron game
I have looked through the issues here with the same problem but didnt find anything

I am using cfw and a homebrew launcher with the rosalina menu
also read the readme
Thanks in advance

Edit: seems my ultra sun save file is corrupted someway i can fix this?

**Comment by BernardoGiordano** [comment]
Restore a backup, you can find backup locations in the readme.
