### ISSUE TITLE
I have problems with PKSM 5.1.1

### ISSUE THREAD

**Issue by xMrCaosx** [BernardoGiordano/PKSM#694]
The recently new update PKSM 5.1.1, Maybe exist one bug important.

With the "Events": all events injected have the same day receives "01/01/2000" :(

is possible im wrong Injected Event or is a bug for the New 5.1.1? in the older versión no have this problem because, when i injected the event The Pokémon receive in correctly date, but a i update the PKSM in the last versión.

**Comment by BernardoGiordano** [comment]
Change date in the settings.

**Comment by xMrCaosx** [comment]
How i can change the date?

**Comment by trainboy2019** [comment]
1. Select your game
2. Select options
3. Move your cursor to the byte you want to change.
        • 0x22 is the day, 0x23 is the month, and 0x24 is the year.
        • Keep in mind that all numbers are hexadecimals.
4. Tap the plus button to increase the value of those bytes and minus to decrease.
5. Once you've made your changes, press B to exit

**Comment by xMrCaosx** [comment]
Thanks so much!! is working!
but i have question, why change in a Manually?
i explain, in the versión 5.0.1 al events created automatically the date the Pokémon but in the 5.1.1 only work Manually :o
