### ISSUE TITLE
Importing exported Mystery Gifts

### ISSUE THREAD

**Issue by ccfman2004** [BernardoGiordano/PKSM#695]
Is there a way to take the Mystery Gifts that were exported from one Gen 7 game and import into another?  Would I have to recompile PKSM to add them?

**Comment by trainboy2019** [comment]
* Start Wireless Inject on PKSM
* Go to [http://htmlpreview.github.io/?https://github.com/BernardoGiordano/PKSM-Tools/blob/master/servepkx/servepkx-browser/index.html](http://htmlpreview.github.io/?https://github.com/BernardoGiordano/PKSM-Tools/blob/master/servepkx/servepkx-browser/index.html)
* Type in your 3ds IP Where the site asks
* Click the Pokeball to upload a valid .pk6/.pk7/.wcx/.wcxfull

**Comment by ccfman2004** [comment]
I tried that but it gives me a bad Egg that I can’t delete.

**Comment by trainboy2019** [comment]
Did you inject the wonder card in the wonder card menu? You select a wonder card and before you inject it, you san start a wireless inject with servepkx.

**Comment by ccfman2004** [comment]
That’s how I did it but now I can’t inject any Wonder Cards into my save. Even the built in ones.

**Comment by BernardoGiordano** [comment]
Did you make sure to change your PKSM date in the settings menu?

**Comment by ccfman2004** [comment]
To what?

**Comment by BernardoGiordano** [comment]
to a date that makes sense

**Comment by ccfman2004** [comment]
Such as?  I can't use the current date?

**Comment by BernardoGiordano** [comment]
did you make sure what date is it?

**Comment by ccfman2004** [comment]
I don't know if I'm doing this correctly.  In the options menu of PKSM on byte 0x22 is 1 as is byte 0x23.  0x24 is 0.  I don't know how to set a date in PKSM as there is no obvious setting for it.

**Comment by BernardoGiordano** [comment]
A increases, X decreases. Increase a little bit, clear mystery gift data and reinject

**Comment by ccfman2004** [comment]
How do I clear Mystery Gift Data?

**Comment by BernardoGiordano** [comment]
it's not possible if you cleared mystery gift data and you setup a proper date. can you say me which wondercard triggers the issue?

**Comment by ccfman2004** [comment]
I set today's date and I tried several of the PKSM built-in Wonder Cards.

**Comment by BernardoGiordano** [comment]
would you mind saying which one you tried? being vague is not helpful

**Comment by ccfman2004** [comment]
I Tried Mew Z and Lunar Magikarp as well as several others.  To many to list.

**Comment by ccfman2004** [comment]
Update.  It seems that if there is no mystery gift data, PKSM can't properly inject a WonderCard.  Once I used PkHex to inject a Wonder Card, PKSM can inject Wonder Cards, even the ones that didn't work.

**Comment by BernardoGiordano** [comment]
That's absolutely absurd, it can't be like that

**Comment by ccfman2004** [comment]
It's what happened.  I'll try a different Pokémon Game and confirm my results.

**Comment by ccfman2004** [comment]
Results confirmed.  Just started a brand new game on Pokémon Ultra Moon and PKSM cannot inject Wonder Cards when the game has none.

**Comment by joshbgosh10592** [comment]
I have this same issue with a newly installed Ultra Sun.
No wondercards were appearing. I'm using PKSM v6.1.0. I'm also not able to press X to dump the wonder card.
Just so happens that Pokemon is currently giving away some type of online mystery gift, thinking this would trigger the game to start recognising wondercard injections, I accepted it.
I then open PKSM again, and there are still 8 injected showing. I then overwrite one card with the Bottlecap, of which I know should be valid for all games, still no mystery gift prompt on the title screen, nor the man in the Pokemon Center.
