### ISSUE TITLE
Issue: Some PokeBank Slots don't work (v5.1.1)

### ISSUE THREAD

**Issue by kamenrider-darkglass** [BernardoGiordano/PKSM#696]
When I was moving boxes of my Pokemon en masse to some boxes in the PokeBank, some slots don't work and I can't place Pokemon on them. After thorough testing, I've determined the following:

Box 1: Slot 26 (6th Row, 2nd Column slot) and Slot 30 (6th Row, 6th Column Slot) cannot have Pokemon Placed on them.

Box: 150: Slot 26 (6th Row, 2nd Column slot) cannot have Pokemon Placed on it.

I'd really like to utilize all available space in PKSM to their fullest degree. Please look into this issue and fix it in the next update.

**Comment by BernardoGiordano** [comment]
Fix bad sectors using PKSM's settings menu.
