### ISSUE TITLE
Pokemon Moon - setting FC (by setting BP) sets only FC earned, not actual FC

### ISSUE THREAD

**Issue by m2pt5** [BernardoGiordano/PKSM#70]
There are two numbers, total FC earned, and current FC on hand. This seems to only edit earned, not on-hand.

Also I've lost the 'Fe' from my 'Festival Plaza'. (Wherever someone would say 'Festival Plaza', it comes out 'stival Plaza'.)

Edit: Ok, I was only a few plaza levels away from being able to set my plaza name, which let me fix the missing letters.

**Comment by BernardoGiordano** [comment]
feature removed
