### ISSUE TITLE
Simple solution to downgrade to 11.3?

### ISSUE THREAD

**Issue by eskimodog** [BernardoGiordano/PKSM#700]
My old 3Ds XL is updated to 11.6, but is there any way to downgrade to 11.3? I'm new to this.

**Comment by GriffinG1** [comment]
No, it is not possible. As a note, this github is not for assistance with 3ds hacking. Please direct any further questions to the Nintendo Homebrew server [here](https://discord.gg/C29hYvh).

**Comment by ihaveamac** [comment]
you just said it was 11.3 in #699. and this isn't the right place.
