### ISSUE TITLE
Issue: PokeBank Slot doesn't work (v5.1.1)

### ISSUE THREAD

**Issue by kamenrider-darkglass** [BernardoGiordano/PKSM#701]
I came across a glitch that doesn't seem to have a solution to it at present: 

Box 150: Slot 26 (6th Row, 2nd Column slot) cannot have a Pokemon Placed on it.

This was an issue that was brought up before and the solution to this problem as suggested by BernardoGiordano is to "Fix bad sectors using PKSM's settings menu." I've done this, but the problem still remains with Box 150, Slot 26. 

I'd really like to utilize all available space in PKSM to their fullest degree. Please look into this issue and fix it in the next update.

P.S. The "Fix bad sectors using PKSM's settings menu" did the job for Box 1 of which this glitch has also affected, but the problem still remains for Box 150.

**Comment by BernardoGiordano** [comment]
Try clearing that slot using the dedicated button, it should wipe that memory location entirely

**Comment by kamenrider-darkglass** [comment]
What do you mean by dedicated button? Can you provide clear and specific
instructions?

**Comment by BernardoGiordano** [comment]
Join our discord server (link in the readme) for real time support.
