### ISSUE TITLE
Pokebank after updating

### ISSUE THREAD

**Issue by NotMarusero** [BernardoGiordano/PKSM#705]
I was using an old 3ds that had pksm and I didnt notice it wasnt the latest build so it didnt have USUM. I used Alpha Sapphire to put some pokemon in the bank so I could get them on USUM. Then I noticed I had to update the build but after doing it I lost the pokemon inside bank storage... Is there a way to get them back? I've tried to do the backup thing but it doesn't seem to be the right backup since the extra storage remains empty. I just dexnaved a shiny ralts with the right gender and nature and lost it...

**Comment by BernardoGiordano** [comment]
Read the readme

**Comment by NotMarusero** [comment]
I did read the readme before I wrote this issue. I copied the bankbin into the right location but it's still empty, is it possible that when I booted pksm and left it saved over both bins? I copied the files to my pc before even trying to solve it and it didn't work...

**Comment by NotMarusero** [comment]
![screen shot 2018-03-21 at 16 26 46](https://user-images.githubusercontent.com/37629134/37722775-ba86651e-2d24-11e8-8ce1-a1ee6bfefbd7.png)
![screen shot 2018-03-21 at 16 27 01](https://user-images.githubusercontent.com/37629134/37722776-baa6cb4c-2d24-11e8-8177-e3b44be2d9ae.png)
