### ISSUE TITLE
Redirection Failed

### ISSUE THREAD

**Issue by FlamingFlareon** [BernardoGiordano/PKSM#708]
I was doing an install and i followed the process and it keeps telling me redirection error when i do my first open and i hit A and it says it again for all 10 assets and then it tells me to restart the application and then repeats. please help and thank you

**Comment by BernardoGiordano** [comment]
Install them manually, check the readme for that

**Comment by FlamingFlareon** [comment]
i couldn't find anything in the readme about a redirect error and you give me a walk through
