### ISSUE TITLE
Problema PKSM editor con pokémon per NDS

### ISSUE THREAD

**Issue by Lorysgenchi95** [BernardoGiordano/PKSM#710]
Ho visto che il creatore è italiano ( meglio cosi, meno problemi di comunicazione ) quando inserisco un gioco NDS e apro pksm vado su editor mi compare la scritta ( this hasn't been implemented ( yet) ) premi A per continuare poi torna in dietro , come si risolve ? grazie ,  è possibile anche spostare i pokemon  da nds a 3ds ? ad esempio da perla a sole  ? 
v5.1.1

**Comment by BernardoGiordano** [comment]
Quelle funzioni non sono ancora implementate, non vedo quale sia il problema.
