### ISSUE TITLE
chinese language bug

### ISSUE THREAD

**Issue by moxiaoou** [BernardoGiordano/PKSM#715]
hi i use jp verson 3ds and play chinese language pokemon ultra moon. and i use the rosalina verson pksm chinese language. this show me all caracter with this ????  , that is bug? u can look in this link with photo.(https://tieba.baidu.com/p/5439123458)

**Comment by moxiaoou** [comment]
can u repaire that? my english is bad  and i cant understand japonese

**Comment by moxiaoou** [comment]
@BernardoGiordano

**Comment by BernardoGiordano** [comment]
You need to change PKSM's language from settings. There's Chinese too.

**Comment by moxiaoou** [comment]
yes i changed in settings to chinese and need close pksm. then i open pksm again the language is chinese but not all is chinese caracter, There are some caracters are question marks

**Comment by piepie62** [comment]
I'm pretty sure that that's a problem with the 3DS itself; it only loads the system font of the language you're using. Since PKSM uses the system fonts and the Japanese system font doesn't include many Chinese characters, they will not be displayed properly

**Comment by moxiaoou** [comment]
yeah This is the problem. I use the Japanese 3DS version. So there is no Chinese in the system. Can you fix this problem?

**Comment by BernardoGiordano** [comment]
we can't fix this problem.

**Comment by moxiaoou** [comment]
Can't add language to the program?

**Comment by moxiaoou** [comment]
I know but you are based on the system language but I cannot change the system language to Chinese but the previous 4.3 version did not have this problem, displayed Chinese is normal.

**Comment by BernardoGiordano** [comment]
That's because we were using a different font rendering system in the past. We won't return back to that one, so the issue isn't fixable by us directly.
