### ISSUE TITLE
In Game PC Pokemon Preview is not Centered? (5.1.2)

### ISSUE THREAD

**Issue by McEzra** [BernardoGiordano/PKSM#719]
After downloading and installing PKSM, I injected a Marshadow event. After transferring it to Ultra Moon through the storage feature, the in game Pokemon preview within the PC are all off-centered. Some Pokemon are too large, and aren't fully on screen anymore.

This seems to be harmless and doesn't affect battles etc, but after switching consoles, and several reboots, it does seem to be a permanent bug to the save file. I've attached some (rough) pictures of what the PC previews look like. 
![20180509_174208](https://user-images.githubusercontent.com/39140919/39845469-50bce602-53b3-11e8-9061-c2efbd8413fc.jpg)
![20180509_174319](https://user-images.githubusercontent.com/39140919/39845476-55f25918-53b3-11e8-849d-e2767d6de7cf.jpg)
![20180509_174519](https://user-images.githubusercontent.com/39140919/39845478-5c526f64-53b3-11e8-94be-429ef8bba205.jpg)

**Comment by BernardoGiordano** [comment]
This can't be related to the save file.

**Comment by McEzra** [comment]
Strange, I wonder what happened then. I know it's closed but would it be useful to post a copy of the save file? Something happened, and I think it's related to trying to edit Marshadow while Marshadow was in my current party. 

Regardless, thanks for the response, and for your time.
