### ISSUE TITLE
Injected event "items" causes game FREEZE

### ISSUE THREAD

**Issue by Ronanklan** [BernardoGiordano/PKSM#722]
Hello! 

I just want to say, I love PKSM!

I've been using it quite a lot since I installed it! 

Yes, I am currently running the most recent updated version! 

Thank you so much!

Now about the bug I found...

Now I noticed when I inject some of the event items, PKSM says injected correctly but then when I open the game to receive them, I will get an "EGG" instead...

Which causes this...

Whenever I open my bag now, for any reason, the game will freeze, causing the entire console to lock up! 

I have to reset the entire console... 😧

Is there anyway I can edit my inventory through PKSM, to delete those "EGGs" out of my bag so I can play my game again?!

I'm pretty confident if I can remove the eggs from my bag  then it should stop freezing and crashing?!?!

I just wanted to bring this to your attention....
Also hoping to find a way to get those eggs out of my bag! LOL!

Thank you so much and have a great day!

P.S.- you would never realize how hard it is to play Pokemon X without the ability to open your bags... Ugh!😫👎

**Comment by BernardoGiordano** [comment]
To fix receiving eggs, you must change the default date into your PKSM settings. To fix the other issue with bag, try to edit your game with PKHeX and remove leftovers. Otherwise, I can't help, using this always means you're up to some risks.
