### ISSUE TITLE
Virtual Console Injector (NOT asking about support for the Nintendo Published VC Pokemon Games)

### ISSUE THREAD

**Issue by turtleisaac1** [BernardoGiordano/PKSM#730]
Is there any form of support for gba Pokémon games installed/ injected with the Virtual Console Injector? I plan on using it to install Ruby and Leaf Green on my 3ds once I get my ntrboot flashcart next week. I love those games and playing through them on the 3ds would be nice, especially if I could transfer them forward. If the Virtual Console Injector GBA Games don’t work, how about other methods of playing GBA on 3ds, like other emulators? Obviously I’d loose one of the features that I’m currently using my physical copy of Ruby for, trading with Colosseum and XD, but it would still be nice. If the reason for not being able to do this is the same as the reason for not being able to do the Nintendo Published VC Games, ok. I am learning to code things like this and if I am able to figure out a way to do this, I will make a sort of plugin or something that can work with PKSM (with your permission, obviously)

**Comment by BernardoGiordano** [comment]
It's not possible to get GBA games working with PKSM
