### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by KofiMatson123** [BernardoGiordano/PKSM#732]
Im having a few problems with the current release of PKSM like when I want to inject wondercards for gen 4 Only one of the events appears ingame, when trying to inject for gen 5 some events freeze as soon as you select them and in gen 6 and 7 theres something wrong with the wondercards as when I try to inject the wondercard count wont go up amd for example will stay on the first wondercard and when I go ingame to get it it gives me an egg which doesnt appear in the party. 
Hopefully a new release will be soom with all these fixes but keep up the great work Bernardo!

**Comment by BernardoGiordano** [comment]
#722
