### ISSUE TITLE
Problem with event pokemons

### ISSUE THREAD

**Issue by GeckoNiko** [BernardoGiordano/PKSM#735]
When i inject a event pokemon and i speak with the delivery guy instead of giving me the pokemon he gives me an egg that does not appear on my team or in my PC

**Comment by Multimegamander** [comment]
Which event?

**Comment by GeckoNiko** [comment]
Like the Rockruff (A special Rockruff!) Or the ash greninja they just appear like eggs and i can't use them

**Comment by Multimegamander** [comment]
Use a PC to send them over WiFi to PKSM

**Comment by GeckoNiko** [comment]
I don't have pc...

**Comment by GeckoNiko** [comment]
I try to send the pokemon over wifi but when i want to my IP my 3ds freeze and then it restart

**Comment by BernardoGiordano** [comment]
You need to change the default date from PKSM's settings.
