### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by Multimegamander** [BernardoGiordano/PKSM#736]
$ make
linking PKSM.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lcurl
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lmbedtls
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lmbedx509
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lmbedcrypto
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lz
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/3ds_rules:40: /home/(name)/Desktop/PKSM-5.
1.2/out/PKSM.elf] Error 1
make: *** [Makefile:168: build] Error 2

**Comment by Multimegamander** [comment]
does the same for make all, make cia, make 3dsx, and make

**Comment by Multimegamander** [comment]
Nevermind, they helped some, I got all but .cia and .3dsx, I have .elf, and .smdh

**Comment by BernardoGiordano** [comment]
Fix your devkitARM installation then. This is not an issue with PKSM
