### ISSUE TITLE
Gen 4 and 5 Games not working (followed all instructions given)

### ISSUE THREAD

**Issue by turtleisaac1** [BernardoGiordano/PKSM#738]
I can’t access my saves of Gen 4 and 5 games, and am running PKSM v5.1.2. I have a physical copy of the games, on legit  gamecards, and have downloaded both Poké Transporter and Pokémon Dream Radar. I have booted both of them up, and I can’t transfer pokemon from my old games to the new ones. Can you please explain what you meant by “select a target title”, and how would I do that? Please help me with this issue

**Comment by SpiredMoth** [comment]
The readme is unfortunately worded: using Transporter to access DS games is only necessary with the hax build; Rosalina and CFW builds can freely access them without help.
If you're using the hax build, then when you select PKSM you're asked to choose a title twice: first in the HBL and second within PKSM. For the first choice you select Transporter, then the second you choose your Gen 4/5 game.

Secondly, the storage and editor and editor have not been implemented in the released builds of PKSM yet. Currently only event injection and scripts work on Gen 4/5 games. Editor and Storage will be in the next major release (no timeframe on that yet though)

**Comment by turtleisaac1** [comment]
Ooooooooh.
