### ISSUE TITLE
Zerora is now officially released

### ISSUE THREAD

**Issue by PKMWM1** [BernardoGiordano/PKSM#740]
Zerora is now available legitimately available with the release of the pre-release tickets for the movie in Japan, but I can't interact with it in the PKSM bank at all. I can't withdraw it, I can't move it, it is just stuck in the bank, can you release a build that unlocks Zerora in the Bank?

**Comment by Joey-nINJJa** [comment]
While Zeraora is listed in the "Generate" menu, PKSM will not generate Zeraora. Even when I try editing the bytes in the advanced editing menu thing, it won't let me set the species to Zeraora, limiting those bytes to one number before Zeraora. I was wondering about this myself. Any workaround or solution?

**Comment by BernardoGiordano** [comment]
Yes. Wait.
