### ISSUE TITLE
Asset/update/naming issue?

### ISSUE THREAD

**Issue by DabblerExtraordinaire** [BernardoGiordano/PKSM#742]
Hello, there. 

I'm just downloading the assets manually, but I wanted to make you aware that the version of PKSM updated July 13 on TitleDB.com is getting "redirection failed/failed to download asset!" on assets 1-4.

I know in the past you've said this means you're using an outdated version, but since the date is so recent, I'm shooting you an FYI just in case. 

Thanks for all your work!

**Comment by BernardoGiordano** [comment]
TitleDB is probably trying to let you download an old version. Don't use it, rather download PKSM from official sources
