### ISSUE TITLE
Sending pokemon to PKSM through the wireless server keeps overwriting the first slot of the Wireless 1 Box

### ISSUE THREAD

**Issue by FM1337** [BernardoGiordano/PKSM#747]
For some reason it doesn't move the Pokemon to a empty slot, it just overwrites Box 1 Slot 1 with whatever gets sent.

Not sure if this a bug or intended (I hope that this isn't the intended behavior, because it kinda throws a wrench in an idea that I had.)

**Comment by BernardoGiordano** [comment]
That is the intended behaviour, the wireless storage is just meant to be a buffer. The behaviour you want to have is within the normal pc viewer function, before entering the editor

**Comment by FM1337** [comment]
Thanks!
