### ISSUE TITLE
Red Screen Freeze that happens only on new version of PKSM

### ISSUE THREAD

**Issue by ncs982** [BernardoGiordano/PKSM#748]
I've been running version 5.0.1 of pksm just fine on my 2ds using soundhax entry point to homebrew. However I just tried to update to version 5.1.4 being sure to update boot.3dsx and I can't get past the red screen when I open pksm. However, I went back to 5.0.1 and it still works fine.

**Comment by EdgarOmega** [comment]
Same here

**Comment by BernardoGiordano** [comment]
Fixed, please redownload it from the latest release.

**Comment by ncs982** [comment]
Hey the fix worked! thanks for being so quick.

**Comment by P1Phoenix** [comment]
Hello could you help me with the red screen on the 6.2.1 version of pksm

**Comment by piepie62** [comment]
Don't necropost, and literally everything changed with 6.0.0, so any issues from before it released except feature requests are invalid
