### ISSUE TITLE
Asset files wont load

### ISSUE THREAD

**Issue by PrinceOfShadows** [BernardoGiordano/PKSM#749]
I've looked on the issues thread and I haven't seen this, maybe I'm blind, but I added the asset files to the accets folder, and i still get an issue stating its failing all 10 of the checks, making me restart PKSM and then it fails again, making it an endless loop. I'm new to PKSM, and i got the latest version. I'm fully connected to the internet.. any feedback or help would be greatly appreciated

**Comment by BernardoGiordano** [comment]
You didn't put them in the correct folder, or you're trying to load an outdated build. Can you please tell me what version the build is and the folder structure?

**Comment by PrinceOfShadows** [comment]
Im trying to use Build 5.1.4 and im putting the files in the 3ds/data/PKSM/additonalassets. The files that i put in the addtional assets folder is a folder named "i18n" and altspritesheetfinal, balspritesheetfinal, and norspritesheetfinal. Im using Rosalina for my CFW if that helps.

**Comment by BernardoGiordano** [comment]
please send a screenshot

**Comment by PrinceOfShadows** [comment]
![20180717_130805 2](https://user-images.githubusercontent.com/41314976/42833797-3771e166-89c3-11e8-80d7-04c6521e052e.jpg)
![20180717_130846 3](https://user-images.githubusercontent.com/41314976/42833800-3871b4b0-89c3-11e8-8186-89a594576505.jpg)

**Comment by PrinceOfShadows** [comment]
I'm not sure if these will help any, but these are the screenshots

**Comment by BernardoGiordano** [comment]
seems that you're not really running the latest PKSM version available. where did you get it?

**Comment by PrinceOfShadows** [comment]
I got it from the Github download page

**Comment by BernardoGiordano** [comment]
I probably got the issue. It's not `3ds/data/PKSM/additionalassets` but `3ds/PKSM/additionalassets`

**Comment by PrinceOfShadows** [comment]
Ok I'll try that to see if it works, thank you so much for the help

**Comment by BernardoGiordano** [comment]
**make sure you're running 5.1.4**, of course you're not
