### ISSUE TITLE
Changing Pokemon Species 

### ISSUE THREAD

**Issue by Blitzle33** [BernardoGiordano/PKSM#75]
As it says above ^ That would really be helpful if that was added. Also, Met location would be great if added. BTW You're doing a great job keep it going!

**Comment by Blitzle33** [comment]
Hello?

**Comment by ig88b1** [comment]
Seconded, I would love to see this feature. Not being able to change the pokemon's species is the only thing holding this back, everything else is excellent. If there is a paypal or something I can donate to to help with development let me know. Thank you!

**Comment by BernardoGiordano** [comment]
It's planned, just wait until the new release is ready! Also, you don't have to, but if you want, you can go at the bottom of the readme :)

**Comment by ig88b1** [comment]
excellent, Buy yourself a beer or something ;)

**Comment by BernardoGiordano** [comment]
added
