### ISSUE TITLE
Pksm 5.1.3 /5.1.4 freeze get stuck

### ISSUE THREAD

**Issue by Brosowski** [BernardoGiordano/PKSM#755]
Pksm versions 5.1.3 and 5.1.4 gets stuck / freeze on games Sun,moon, ultra Sun, ultra moon.
But.... Works Fine in Pokémon x, y ,
Omega rubi , Alpha saphire .
And someones ultra Beats nota working "shiny" online, includes someones mythical pokemon...

**Comment by BernardoGiordano** [comment]
Ask for help in https://discord.gg/bGKEyfY
