### ISSUE TITLE
trying to downloads fails and says "Failed to verify TLS certificate"

### ISSUE THREAD

**Issue by r2d2401** [BernardoGiordano/PKSM#757]
everytime I try to scan the qr code, it doesn't start installing and the desc says that it "Failed to verify TLS certificate", what does this even mean?

**Comment by Mike007899** [comment]
Read: https://www.reddit.com/r/3dshacks/comments/7zof0c/reminder_github_has_dropped_tlsv111_support_as_of/
Use: https://github.com/BernardoGiordano/QRaken/releases

@r2d2401
