### ISSUE TITLE
Wont let me  edit any of my ds games

### ISSUE THREAD

**Issue by connyyy** [BernardoGiordano/PKSM#760]
I have a copy of white 2 that i want to edit pokemon into but when i select the editor option it says that nothing is implemented. Im new to this so idk if this is just my game or the app?

**Comment by SpiredMoth** [comment]
PKSM doesn't have Editor or Storage support for DS games (Gens 4 & 5) yet, so this is expected behavior

**Comment by connyyy** [comment]
Oh okay thank you so much. Is there any possibility for an editor for gen 4&5 in the future?

**Comment by SpiredMoth** [comment]
PKSM is currently being rewritten into another programming language. Expanded support won't come until at least that is finished

**Comment by felixlee0530** [comment]
Then, is PkHEX the only way to edit DS games for now?

Are there any other applications for editing and managing storage directly in the 3DS?
