### ISSUE TITLE
Events can not be played online

### ISSUE THREAD

**Issue by Lement22** [BernardoGiordano/PKSM#765]
Event of Greninja Ash does not accept it online, I think it's because the level of meeting is 5 when it should be 36.

Event Tapu Koko Shiny does not accept either try to change the date of meeting to one between the dates of distribution but even so I was not allowed to play with him.

**Comment by Lement22** [comment]
It is necessary to do it to the game for which they were released, if so it is my mistake since I play Ultra Moon. And both left for Sun Moon.

**Comment by Mike007899** [comment]
Thats the issue, if they werent injected to the proper game.

**Comment by Lement22** [comment]
Thank you very much for clarifying my doubt. I practically must get it from someone who made it legal and clone it, maybe that works.
