### ISSUE TITLE
3ds crashes after closing PKSM

### ISSUE THREAD

**Issue by st3ph0n** [BernardoGiordano/PKSM#766]
So today I got pksm and everytime I exit pksm using the start button it crashes my 3ds leaving it in a black and red screen. Is this an issue with my 3ds? if so how can I fix it?

**Comment by st3ph0n** [comment]
is this an issue with my 3ds?

**Comment by Brosowski** [comment]
Im using Pokémon Sun/moon/ultra Sun/ultra moon in these games crash after to go back on homebrew menu. But... In other games like X / Y/Omega/Alpha. Go back Very well.
"In 3ds old"

**Comment by st3ph0n** [comment]
I as using my Alpha Sapphire And It Does That Everytime. It always results in a red and black screen

**Comment by st3ph0n** [comment]
cartridge

**Comment by BernardoGiordano** [comment]
https://discord.gg/bGKEyfY
