### ISSUE TITLE
Installing PKSM on 11.0.8.0-41U

### ISSUE THREAD

**Issue by Eriun** [BernardoGiordano/PKSM#769]
Hello there!

I want to ask on how I can start again on adding PKSM for my 3ds. It updated as stated in the title but i want to know how to install it again.

What should be the tools to add before pksm?
Should i still use homebrew or a different app?

If u have links or guides, please let me know. I appreciate it. Thanks!

**Comment by PanchitoWolfy** [comment]
You must have a cia installer, fbi is the most common. To do thus you ofc need to mod your 3ds, homebrew or cfw. Once you have these these things and have FBI, open it and click SD. Then click on "cias" which is a folder you create and put Pksm.cia into. After that click on Pksm.cia and push install and delete cia. Boom, now go to your home screen and it should appear as a wrapped gift. Hope this helps

**Comment by Eriun** [comment]
But i read that on the latest update, HB is not working at some point? And how do i mod my 3ds? I need a refresher i hope u guys can help

**Comment by Eriun** [comment]
But i read that on the latest update, HB is not working at some point? And how do i mod my 3ds? I need a refresher i hope u guys can help

**Comment by PanchitoWolfy** [comment]
You can actually still mod ur 3ds tho you won't be able to use games from FreEShop or CiaAngel. You can only play .cia games on os 11.8 so you don't get banned. Let me get a link to mod ur 3ds.

**Comment by GriffinG1** [comment]
Ok full stop here. This is not a place to talk about piracy, period. This is also not a place for us to help you mod your 3ds. Use this link, https://3ds.hacks.guide, and if you still need help with modding your 3ds, please go ask on the Nintendo homebrew discord. Not here. Please close this issue ASAP.

**Comment by Eriun** [comment]
Thank you so much!

**Comment by Eriun** [comment]
I understand, not really used to this. Sorry and thanks. Closing now.

**Comment by PanchitoWolfy** [comment]
All right, will stop.
