### ISSUE TITLE
Gen 4-6 doesn't work.

### ISSUE THREAD

**Issue by joshcast96** [BernardoGiordano/PKSM#774]
I read all the readme file, im using hombrew, but i dont have the poke traslator,   i cant find it on the eshop... the pokebank doesnt work either... is there another app that i could use?

**Comment by BernardoGiordano** [comment]
Poketransporter can be downloaded from the pokebank if you purchased a license.

**Comment by joshcast96** [comment]
I cant, venezuelan debit/credit cards just keep givin me error, i have the money but this it let me buy it.

No other apps are compatible?
