### ISSUE TITLE
Pokémon Diamond, Pearl and Platinum support

### ISSUE THREAD

**Issue by ccfman2004** [BernardoGiordano/PKSM#83]
Will there be support for these 3 DS games?

**Comment by InkDragon** [comment]
@BernardoGiordano 
Possibly look at https://github.com/Chase-san/PokeLib and/or contact chase-san for permision importing old PPSE-DS features for 4th gen game editing.

He gave me permission to point you his work and told me he doesn't care if you use, it but feel free to confirm for yourself.

**Comment by BernardoGiordano** [comment]
added
