### ISSUE TITLE
Pokemon transferred with the bank are invalid?

### ISSUE THREAD

**Issue by sebas123d** [BernardoGiordano/PKSM#84]
Any pokemon transferred from other generations, whether or not modified, can not be used online or exchanged,  And you can not use eggs from the transferred pokemon

**Comment by BernardoGiordano** [comment]
Don't you say?

**Comment by sebas123d** [comment]
When I try to trade pokemon from other versions it doesn't allow me because "there is a problem with the pokemon" exists or doesn't exist in alola. Is it a bug?The  Pokemon are not modified, only transferred by pksm

**Comment by BernardoGiordano** [comment]
They're not officially released, that's not a bug. It's totally normal

**Comment by sebas123d** [comment]
Thanks
