### ISSUE TITLE
[Feature] Support for editing Pokemon in Party

### ISSUE THREAD

**Issue by ShadowOne333** [BernardoGiordano/PKSM#85]
The option to be able to edit the Party pokemon would be a nice addition.
I usually have my fav Pokemon on my party and having to deposit them to edit them, then put them back does take a while. Editing them directly from the Party could be a great addition to the app.

**Comment by Moitix** [comment]
Yeah, it will be a good addition to the app, but it is actually just a way to save a little time, it's not that much of work just to put pokemon in a box.

**Comment by Demirramon** [comment]
While it's not so hard to put them in a box, I think it would be pretty nice to be able to edit a Pokémon from your team.

**Comment by altr0n** [comment]
What are the technical limitations behind this? Will it just take a little more RE? I might have some time to work on this if someone can point me in the right direction initially

**Comment by BernardoGiordano** [comment]
Added in the [latest commit](https://github.com/BernardoGiordano/PKSM/commit/c075ef87392837df55ec15aab0e7970489389e5f)
