### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by giveup** [BernardoGiordano/PKSM#87]
> find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
linking PKSM.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/lib/armv6k/fpu/3dsx_crt0.o: In function `ClrLoop':
(.crt0+0x8c): undefined reference to `main'
collect2: error: ld returned 1 exit status

Build with latest devkitARM on Mac.

**Comment by BernardoGiordano** [comment]
Your path is messy.
Also, this will not compile or work, as I said, the code is under maintenance. There are few pieces that I didn't upload. You're wasting your time
