### ISSUE TITLE
Alolan forms abilities don't work

### ISSUE THREAD

**Issue by Moitix** [BernardoGiordano/PKSM#88]
There are some sprites that don't change, like ninetales or sandlash, and because of that when you change the ability to that pokemon, it don't change to the actuall alolan form ability... Imagine an alola ninetales with drought as the ability... It will totally break the game... Can you fix that?

**Comment by BernardoGiordano** [comment]
already fixed, wait for the enxt update.

**Comment by Moitix** [comment]
Awesome ^^
