### ISSUE TITLE
App crashes when opening Event Menu in Pokemon Black / White (BW2 are okay)

### ISSUE THREAD

**Issue by felixlee0530** [BernardoGiordano/PKSM#890]
Hello,

I have a White cartridge and a Black 2 cartridge.

I tried accessing the event menu (where PKSM lists all event wonder cards that I can inject in my save) with both cartridges, and found a bug that the developers need to fix.

When I load the save of my Black 2 cartridge using PKSM, the event menu shows a huge list of event wonder cards (around 500, I guess.. I didn't know that there's a lot of events in Gen 5) so I'm happy to have a look at them. However, in my White, whenever I access the event menu, the app crashes and returns to the home menu. I borrowed my friend's White 2 and tested the event menu, but it worked fine. Thus, I believe that the event menu crashes in cartridges for Black and White ONLY.

I hope this can be fixed in the update.

**Comment by BernardoGiordano** [comment]
You seem to have garbage data into your mystery gift section. Open the save with PKHeX and remove the garbage data
