### ISSUE TITLE
Allow us to view ESVs, TSVs

### ISSUE THREAD

**Issue by Sturmrufer** [BernardoGiordano/PKSM#9]
Would be super helpful for me and many others. Thank you for this awesome software!

**Comment by BernardoGiordano** [comment]
[TSV added, ESV will be added when the app will officially support eggs](https://github.com/BernardoGiordano/EventAssistant/commit/dd71a21238a63979ac68622571e7fe80860f4fb5)

**Comment by BernardoGiordano** [comment]
[Fixed](https://github.com/BernardoGiordano/PKSM/commit/fb50791cd2af00268ccd979d43897018e1413ce4)
