### ISSUE TITLE
Can't use the pokemon editor

### ISSUE THREAD

**Issue by Moitix** [BernardoGiordano/PKSM#92]
I know you have just released the new update. I already installed it and for sure it's really awesome. The sprites are solved, the new UI is just incredible, the little movement that PKSM have now make it more "pretty" to look, but I can't access to the Pokemon Editor... Is because this is an alpha release?

**Comment by BernardoGiordano** [comment]
![image](https://cloud.githubusercontent.com/assets/17624378/21473199/432431f0-caff-11e6-8006-6e663d52d721.png)

Why don't you fully read release notes

**Comment by Moitix** [comment]
Ohh yes, i'm stupid lol. Still is awesome. Continue working like that.
