### ISSUE TITLE
Alpha 4.0 - Game Icons dont show - Pokedex doesnt work

### ISSUE THREAD

**Issue by initPRAGMA** [BernardoGiordano/PKSM#93]
Title says it all

**Comment by BernardoGiordano** [comment]
Go read release notes and readme

**Comment by initPRAGMA** [comment]
Oh my bad! You should make these auto-download upon launch when its loading graphics, be good.

**Comment by Samuel8488** [comment]
Imposible to open the Pokémon Edit menú ._.

**Comment by KINGBLOODAXE** [comment]
Read the readme before posting...

**Comment by Samuel8488** [comment]
I't cannot open the read ._.

**Comment by Samuel8488** [comment]
I un Android no PC

**Comment by Samuel8488** [comment]
In*

**Comment by DuraAdri** [comment]
Edit Pokemon not open for me, i need working this :(
