### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by SciresM** [BernardoGiordano/PKSM#94]
This uses my [memecrypto implementation](https://github.com/SciresM/memecrypto_test), which is licensed under the [GPLv3](https://github.com/SciresM/memecrypto_test/blob/master/LICENSE).

Your project is not currently licensed under the GPL, and per section 5 (c) it must be to use my code.

Please re-license, or do not use my memecrypto implementation :)

**Comment by Blitzle33** [comment]
Damn 🐸☕

**Comment by SciresM** [comment]
I should add, this is actually a double issue -- you also use [mini-gmp](https://github.com/Cl3Kener/gmp/tree/master/mini-gmp), which is doubly licensed under the GPL/LGPL. If you elect not to re-license under the GPL, you will also have to remove that dependency.

**Comment by BernardoGiordano** [comment]
I was about to adopt a real license, thanks for making me notice.

**Comment by BernardoGiordano** [comment]
Re-licensed to GPLv3
