### ISSUE TITLE
[Bug?] "Managment"/"Other" sections not working

### ISSUE THREAD

**Issue by InkCheeto** [BernardoGiordano/PKSM#95]
Hi! Awesome work with new interface btw n.n
On last version (3.1.2 I wonder?) everything worked just fine (except for the save editing feature). Now, with 4.0.0, I noticed lots of sections don't even load.
More precisely, this is the list of sections that won't load on my system:

Through _Managment:_

- Editor
- Save
- Mass injector

Through _Other:_

- Everything, excepting the credits.

In all of them, I face the same problem; they just don't pop up when I press "A" (I also tried tapping on touch screen). Is there something I'm missing or it's just not implemented on 4.0.0?

Thanks in advance~!

**Comment by BernardoGiordano** [comment]
If you only read release notes...
