### ISSUE TITLE
modify Sun cart with PKSM and then Save Data is Corrupt

### ISSUE THREAD

**Issue by Diego788** [BernardoGiordano/PKSM#96]
well, i was using PKSM but first i made a backup of my game there, then i go to the game, but that message appeared, what can i do now?

p.s.: i made a backup in PKSM and JKSV
p.s2: i'm using CFW, not homebrew launcher

**Comment by BernardoGiordano** [comment]
Weird, this should not happen. What do you did to your save?

**Comment by Diego788** [comment]
i saved outside the second Pokémon Center outside the second city in the second island lol

**Comment by Diego788** [comment]
i tried to restore my backups but it keeps showing that  corrupt data message, and PKSM now say Incorrect Save Size

maybe is something

**Comment by BernardoGiordano** [comment]
I mean while using PKSM

**Comment by BernardoGiordano** [comment]
I think your cartridge released you a wrong sized save, that's why. Does the one done with JKSM works?

**Comment by Diego788** [comment]
btw i'm using latest stable, not 4.0

the save size backup from JKSM and PKSM are the same
i tried restoring them but it keep showing that error

**Comment by Diego788** [comment]
(https://cloud.githubusercontent.com/assets/19751404/21486184/52e4ab6c-cb8e-11e6-9ba6-b193fc6ec258.png)

same size

**Comment by Diego788** [comment]
tried to load my backup with pkhex... it seems nice
(https://cloud.githubusercontent.com/assets/19751404/21486193/91c583d8-cb8e-11e6-8039-d60cbab9385d.jpg)

**Comment by Diego788** [comment]
LOLOLOLI FIXED IT!!!! I WAS TOO WORRIED
i remembered something, FBI have access to Save data folder

so i go to Pokémon Sun save data and there was nothing, so i copied my backup to that Save data folder and renamed it "main" then i started my game and done, my save loaded

now i'll wait a little longer before using this xd
i only use it in Y and OR

thanks anyways for helping :D

**Comment by NinjaBoyLao** [comment]
thats really interesting that JKSV extracted the save wrong too.. i wonder what FBI did to fix the file when putting it on the cart

**Comment by NinjaBoyLao** [comment]
@Steveice10
