### ISSUE TITLE
Pksm  has frozen

### ISSUE THREAD

**Issue by Daboposki** [BernardoGiordano/PKSM#97]
What can i do? While I was opening the pokemon editor, pksm froze and when i closed it because i couldnt do anything the app doesnt close, the message Cerrando programa... (Spanish) doesnt disappear and i cant do anything, what should i do? Thx

**Comment by KINGBLOODAXE** [comment]
Are you using 4.0.0? If so those functions are disabled.

**Comment by BernardoGiordano** [comment]
Did you exit through the home button?

**Comment by Daboposki** [comment]
Yes, I exit through the home button because the pksm froze and i couldnt do anything else

**Comment by BernardoGiordano** [comment]
You must not exit with the home menu. BTW, it did not froze: the editor is simply locked in the latest alpha.

**Comment by Daboposki** [comment]
So, what should i do if i have exit through the home button?

**Comment by BernardoGiordano** [comment]
just force shut down, you're fine

**Comment by Daboposki** [comment]
It worked, thanks you!
