### ISSUE TITLE
PP of moves

### ISSUE THREAD

**Issue by Moitix** [BernardoGiordano/PKSM#99]
I know that we can actually put a lot of PP Max to our Pokémon with the ítem selection, then go to the Game, retrieve the ítem and then use them... But is annoying... Can you solve that by making the Max PP of the moves right where we select them?

**Comment by Moitix** [comment]
Thanks for the info dude

**Comment by BernardoGiordano** [comment]
added preliminary support for PPs with the last series of commits.
